"""Single source of truth for transfer and S3 geometry limits.

Two concept families:

* **S3 server-side multipart copy** — AWS MPU limits for CopyObject vs multipart
  upload and copy (5 MiB-5 GiB per part, 10_000 parts).
* **Client upload policy** — platform envelope for browser/direct multipart
  uploads. (resolved policy clamps; distinct from raw env validation on some
  fields).
"""

from __future__ import annotations

# --- S3 multipart geometry (server-side copy / MPU) — AWS-documented bounds ---

S3_MULTIPART_MAX_PARTS = 10_000
S3_MULTIPART_MIN_PART_SIZE_BYTES = 5 * 1024 * 1024
S3_MULTIPART_MAX_PART_SIZE_BYTES = 5 * 1024 * 1024 * 1024

# Single-object copy is limited to 5 GB (5,000,000,000 bytes); larger objects
# use multipart copy.
COPY_OBJECT_MAX_BYTES = 5_000_000_000

# --- Client upload policy envelope (resolved transfer policy) ---

CLIENT_UPLOAD_MIN_PART_SIZE_BYTES = 64 * 1024 * 1024
CLIENT_UPLOAD_MAX_PART_SIZE_BYTES = 512 * 1024 * 1024

TARGET_UPLOAD_PART_COUNT_MIN = 1
TARGET_UPLOAD_PART_COUNT_MAX = 10_000

SIGN_BATCH_SIZE_HINT_MIN = 32
SIGN_BATCH_SIZE_HINT_MAX = 128

MAX_CONCURRENCY_HINT_MIN = 1
MAX_CONCURRENCY_HINT_MAX = 32

MULTIPART_THRESHOLD_MIN_BYTES = 5 * 1024 * 1024

RESUMABLE_TTL_MIN_SECONDS = 60
RESUMABLE_TTL_MAX_SECONDS = 30 * 24 * 60 * 60

# Raw env `FILE_TRANSFER_PART_SIZE_BYTES` allows 5 MiB-5 GiB before policy
# resolution clamps to client upload bounds; keep aligned with Settings
# validation.
ENV_PART_SIZE_BYTES_MIN = 5 * 1024 * 1024
ENV_PART_SIZE_BYTES_MAX = 5 * 1024 * 1024 * 1024

ENV_EXPORT_COPY_PART_SIZE_BYTES_MIN = 1 * 1024 * 1024 * 1024
ENV_EXPORT_COPY_PART_SIZE_BYTES_MAX = 5 * 1024 * 1024 * 1024

ENV_LARGE_EXPORT_WORKER_THRESHOLD_MIN_BYTES = 5 * 1024 * 1024 * 1024

DEFAULT_POLICY_ID = "default"
DEFAULT_POLICY_VERSION = "2026-04-03"

DEFAULT_TARGET_UPLOAD_PART_COUNT = 2000
DEFAULT_ACTIVE_MULTIPART_UPLOAD_LIMIT = 200
DEFAULT_DAILY_INGRESS_BUDGET_BYTES = 1024 * 1024 * 1024 * 1024
DEFAULT_SIGN_REQUESTS_PER_UPLOAD_LIMIT = 512

# Server-side export copy part sizing (policy layer; distinct from S3 MPU
# absolute bounds).
EXPORT_COPY_POLICY_MIN_PART_SIZE_BYTES = 1 * 1024 * 1024 * 1024
EXPORT_COPY_POLICY_MAX_PART_SIZE_BYTES = 5 * 1024 * 1024 * 1024

__all__ = [
    "CLIENT_UPLOAD_MAX_PART_SIZE_BYTES",
    "CLIENT_UPLOAD_MIN_PART_SIZE_BYTES",
    "COPY_OBJECT_MAX_BYTES",
    "DEFAULT_ACTIVE_MULTIPART_UPLOAD_LIMIT",
    "DEFAULT_DAILY_INGRESS_BUDGET_BYTES",
    "DEFAULT_POLICY_ID",
    "DEFAULT_POLICY_VERSION",
    "DEFAULT_SIGN_REQUESTS_PER_UPLOAD_LIMIT",
    "DEFAULT_TARGET_UPLOAD_PART_COUNT",
    "ENV_EXPORT_COPY_PART_SIZE_BYTES_MAX",
    "ENV_EXPORT_COPY_PART_SIZE_BYTES_MIN",
    "ENV_LARGE_EXPORT_WORKER_THRESHOLD_MIN_BYTES",
    "ENV_PART_SIZE_BYTES_MAX",
    "ENV_PART_SIZE_BYTES_MIN",
    "EXPORT_COPY_POLICY_MAX_PART_SIZE_BYTES",
    "EXPORT_COPY_POLICY_MIN_PART_SIZE_BYTES",
    "MAX_CONCURRENCY_HINT_MAX",
    "MAX_CONCURRENCY_HINT_MIN",
    "MULTIPART_THRESHOLD_MIN_BYTES",
    "RESUMABLE_TTL_MAX_SECONDS",
    "RESUMABLE_TTL_MIN_SECONDS",
    "S3_MULTIPART_MAX_PARTS",
    "S3_MULTIPART_MAX_PART_SIZE_BYTES",
    "S3_MULTIPART_MIN_PART_SIZE_BYTES",
    "SIGN_BATCH_SIZE_HINT_MAX",
    "SIGN_BATCH_SIZE_HINT_MIN",
    "TARGET_UPLOAD_PART_COUNT_MAX",
    "TARGET_UPLOAD_PART_COUNT_MIN",
]
