"""Contract checks for public TypeScript SDK package manifests."""

from __future__ import annotations

import json
import re
from pathlib import Path
from typing import cast

REPO_ROOT = Path(__file__).resolve().parents[3]
TS_PACKAGE_DIR = "nova_sdk_ts"


def _load_package_json(package_dir_name: str) -> dict[str, object]:
    package_path = REPO_ROOT / "packages" / package_dir_name / "package.json"
    return cast(
        dict[str, object],
        json.loads(package_path.read_text(encoding="utf-8")),
    )


def _load_source_text(package_dir_name: str, file_name: str) -> str:
    source_path = REPO_ROOT / "packages" / package_dir_name / "src" / file_name
    return source_path.read_text(encoding="utf-8")


def test_public_sdk_packages_use_subpath_only_exports() -> None:
    """Public TS SDK packages must expose explicit subpaths only."""
    package_data = _load_package_json(TS_PACKAGE_DIR)
    assert package_data.get("name") == "@nova/sdk"
    assert "main" not in package_data
    assert "module" not in package_data
    assert "types" not in package_data
    exports = package_data.get("exports")
    assert isinstance(exports, dict)
    assert "." not in exports
    assert set(exports) == {"./client", "./sdk", "./types"}


def test_typescript_sdk_source_manifests_remain_private() -> None:
    """Source TS SDK manifests stay private until staged publish preparation."""
    package_data = _load_package_json(TS_PACKAGE_DIR)
    assert package_data.get("private") is True


def test_public_sdk_package_is_runtime_lean() -> None:
    """Public TS SDK package must stay free of the deleted runtime stack."""
    package_data = _load_package_json(TS_PACKAGE_DIR)
    dependencies = package_data.get("dependencies", {})
    assert isinstance(dependencies, dict)
    dependency_map = cast(dict[str, object], dependencies)
    assert "zod" not in dependency_map
    assert "@nova/sdk-fetch" not in dependency_map
    assert "openapi-fetch" not in dependency_map
    assert "@hey-api/client-fetch" not in dependency_map


def test_public_sdk_types_omit_raw_model_aliases() -> None:
    """Public TS SDK types must not expose raw OpenAPI-wide aliases."""
    banned_exports = (
        "export type Components =",
        "export type Paths =",
        "export type Operations =",
        "export type OperationId =",
    )

    source = _load_source_text(TS_PACKAGE_DIR, "client/types.gen.ts")
    for banned_export in banned_exports:
        assert banned_export not in source


def test_public_sdk_types_exclude_internal_job_result_aliases() -> None:
    """Public file SDK types must exclude worker-only job result aliases."""
    source = _load_source_text(TS_PACKAGE_DIR, "client/types.gen.ts")
    assert "export type JobResultUpdateRequest" not in source
    assert "export type JobResultUpdateResponse" not in source


def test_public_sdk_types_exclude_wrapper_specific_aliases() -> None:
    """Public file SDK types must not expose deleted transport-wrapper types."""
    source = _load_source_text(TS_PACKAGE_DIR, "client/types.gen.ts")
    assert "export type RequestOptions =" not in source
    assert "export type Result =" not in source
    assert re.search(r"\b\w+RequestOptions\b", source) is None
    assert re.search(r"\b\w+Result\b", source) is None


def test_public_sdk_uses_only_explicit_public_entrypoints() -> None:
    """Public TS entrypoints stay on explicit subpaths, not root barrels."""
    package_root = REPO_ROOT / "packages" / TS_PACKAGE_DIR / "src"
    assert not (package_root / "index.ts").exists()
    assert not (package_root / "client" / "index.ts").exists()
    assert (package_root / "client" / "client" / "index.ts").exists()


def test_public_sdk_internal_index_is_not_a_public_entrypoint() -> None:
    """The internal generator index remains a private scaffold only."""
    source = _load_source_text(TS_PACKAGE_DIR, "client/client/index.ts")

    assert source.startswith(
        "// This file is auto-generated by @hey-api/openapi-ts"
    )
    assert "./client/index.js" not in _load_source_text(
        TS_PACKAGE_DIR,
        "client/types.gen.ts",
    )


def test_public_sdk_top_level_modules_use_esm_specifiers() -> None:
    """Top-level generated modules must use explicit ESM import specifiers."""
    client_source = _load_source_text(TS_PACKAGE_DIR, "client/client.gen.ts")
    sdk_source = _load_source_text(TS_PACKAGE_DIR, "client/sdk.gen.ts")

    assert "./client/index.js" in client_source
    assert "./types.gen.js" in client_source
    assert "./client.gen.js" in sdk_source
    assert "./client/index.js" in sdk_source
    assert "./types.gen.js" in sdk_source


def test_public_sdk_exposes_generated_sdk_functions_only() -> None:
    """SDK module must export only public generated operations."""
    source = _load_source_text(TS_PACKAGE_DIR, "client/sdk.gen.ts")
    assert "export const getExport" in source
    assert "export const createExport" in source
    assert "export const updateJobResult" not in source
