#!/usr/bin/env python3
"""Enforce the public TypeScript module policy for generated SDK packages."""

from __future__ import annotations

import re
from collections.abc import Iterator
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
TS_ROOT = REPO_ROOT / "packages"
ALLOWED_INTERNAL_INDEX = (
    Path("packages") / "nova_sdk_ts" / "src" / "client" / "client" / "index.ts"
)
AUTOGENERATED_HEADER = "// This file is auto-generated by @hey-api/openapi-ts"
BARREL_BLOCK_RE = re.compile(
    r"^\s*export\s+(?:type\s+)?(?:\*|\{[^}]+\})\s+from\s+['\"](?P<target>[^'\"]+)['\"]",
    re.MULTILINE | re.DOTALL,
)
ALLOWED_INTERNAL_EXPORT_TARGETS = frozenset(
    {
        "../core/auth.gen.js",
        "../core/bodySerializer.gen.js",
        "../core/params.gen.js",
        "../core/queryKeySerializer.gen.js",
        "./client.gen.js",
        "./types.gen.js",
        "./utils.gen.js",
    }
)


def _iter_ts_files() -> Iterator[Path]:
    yield from sorted(TS_ROOT.glob("**/src/**/*.ts"))


def _line_number(text: str, offset: int) -> int:
    return text.count("\n", 0, offset) + 1


def _validate_allowed_internal_index(rel: Path, text: str) -> list[str]:
    violations: list[str] = []
    first_line = text.splitlines()[0] if text.splitlines() else ""
    if first_line != AUTOGENERATED_HEADER:
        violations.append(
            f"{rel}: generator-owned internal index must keep the "
            "Hey API autogenerated header"
        )

    for match in BARREL_BLOCK_RE.finditer(text):
        line_no = _line_number(text, match.start())
        target = match.group("target")
        statement = match.group(0)
        if statement.lstrip().startswith("export *"):
            violations.append(
                f"{rel}:{line_no}: wildcard re-export syntax is disallowed"
            )
            continue
        if target not in ALLOWED_INTERNAL_EXPORT_TARGETS:
            violations.append(
                f"{rel}:{line_no}: internal generator barrel target "
                f"is not allowlisted: {target}"
            )
    return violations


def _validate_public_module_policy() -> list[str]:
    violations: list[str] = []
    for path in _iter_ts_files():
        rel = path.relative_to(REPO_ROOT)
        try:
            text = path.read_text(encoding="utf-8")
        except (OSError, UnicodeDecodeError) as exc:
            violations.append(f"{rel}: failed to read file: {exc}")
            continue

        if path.name == "index.ts":
            if rel != ALLOWED_INTERNAL_INDEX:
                violations.append(
                    f"{rel}: public index.ts entrypoints are disallowed"
                )
                continue
            violations.extend(_validate_allowed_internal_index(rel, text))
            continue

        for match in BARREL_BLOCK_RE.finditer(text):
            line_no = _line_number(text, match.start())
            violations.append(
                f"{rel}:{line_no}: public re-export barrel syntax is disallowed"
            )
    return violations


def main() -> int:
    """Validate TypeScript modules against the public package policy."""
    violations = _validate_public_module_policy()

    if violations:
        print("TypeScript public module policy violations detected:")
        for item in violations:
            print(f" - {item}")
        return 1

    print("TypeScript public module policy check passed.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
