#!/usr/bin/env python3
"""Generate lightweight TypeScript and R SDK catalogs from committed OpenAPI."""

from __future__ import annotations

import argparse
import json
from dataclasses import dataclass
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
OPENAPI_ROOT = REPO_ROOT / "packages" / "contracts" / "openapi"
HTTP_METHODS = ("get", "post", "put", "patch", "delete", "options", "head")


@dataclass(frozen=True)
class Operation:
    """Single OpenAPI operation used for generated client catalogs."""

    operation_id: str
    method: str
    path: str
    summary: str | None


@dataclass(frozen=True)
class GenerationTarget:
    """Output targets for one committed OpenAPI document."""

    spec_path: Path
    ts_output_path: Path
    r_output_path: Path
    catalog_function_name: str


TARGETS = (
    GenerationTarget(
        spec_path=OPENAPI_ROOT / "nova-file-api.openapi.json",
        ts_output_path=REPO_ROOT
        / "packages"
        / "nova_sdk_file_core"
        / "src"
        / "generated.ts",
        r_output_path=REPO_ROOT
        / "packages"
        / "nova_sdk_r_file"
        / "R"
        / "generated.R",
        catalog_function_name="nova_file_operation_catalog",
    ),
    GenerationTarget(
        spec_path=OPENAPI_ROOT / "nova-auth-api.openapi.json",
        ts_output_path=REPO_ROOT
        / "packages"
        / "nova_sdk_auth_core"
        / "src"
        / "generated.ts",
        r_output_path=REPO_ROOT
        / "packages"
        / "nova_sdk_r_auth"
        / "R"
        / "generated.R",
        catalog_function_name="nova_auth_operation_catalog",
    ),
)


def _load_operations(spec_path: Path) -> list[Operation]:
    spec = json.loads(spec_path.read_text(encoding="utf-8"))
    paths = spec.get("paths")
    if not isinstance(paths, dict):
        raise ValueError(f"OpenAPI spec missing paths object: {spec_path}")

    operations: list[Operation] = []
    for path, path_item in paths.items():
        if not isinstance(path, str) or not isinstance(path_item, dict):
            continue
        for method in HTTP_METHODS:
            operation = path_item.get(method)
            if not isinstance(operation, dict):
                continue
            operation_id = operation.get(
                "operationId"
            ) or _default_operation_id(
                method=method,
                path=path,
            )
            summary = operation.get("summary")
            operations.append(
                Operation(
                    operation_id=str(operation_id),
                    method=method.upper(),
                    path=path,
                    summary=str(summary) if summary else None,
                )
            )
    operations.sort(
        key=lambda item: (item.path, item.method, item.operation_id)
    )
    return operations


def _default_operation_id(*, method: str, path: str) -> str:
    sanitized = (
        path.strip("/").replace("/", "_").replace("{", "").replace("}", "")
    )
    sanitized = sanitized.replace("-", "_") or "root"
    return f"{method.lower()}_{sanitized}"


def _render_typescript(operations: list[Operation]) -> str:
    lines = [
        (
            "// Code generated by scripts/release/generate_clients.py. "
            "DO NOT EDIT."
        ),
        "",
        "export interface OperationDescriptor {",
        "  readonly operationId: string;",
        (
            '  readonly method: "GET" | "POST" | "PUT" | "PATCH" | '
            '"DELETE" | "OPTIONS" | "HEAD";'
        ),
        "  readonly path: string;",
        "  readonly summary?: string;",
        "}",
        "",
        "export const operations = {",
    ]

    for operation in operations:
        summary_line = (
            f"    summary: {json.dumps(operation.summary)},"
            if operation.summary
            else None
        )
        lines.extend(
            [
                f"  {json.dumps(operation.operation_id)}: {{",
                f"    operationId: {json.dumps(operation.operation_id)},",
                f"    method: {json.dumps(operation.method)},",
                f"    path: {json.dumps(operation.path)},",
            ]
        )
        if summary_line is not None:
            lines.append(summary_line)
        lines.append("  },")

    lines.extend(
        [
            "} as const satisfies Record<string, OperationDescriptor>;",
            "",
            "export type OperationId = keyof typeof operations;",
            "export type GeneratedOperationCatalog = typeof operations;",
            "",
        ]
    )
    return "\n".join(lines)


def _render_r(operations: list[Operation], catalog_function_name: str) -> str:
    lines = [
        "# Code generated by scripts/release/generate_clients.py. DO NOT EDIT.",
        "",
        f"{catalog_function_name} <- function() {{",
        "  list(",
    ]

    for index, operation in enumerate(operations):
        suffix = "," if index < len(operations) - 1 else ""
        summary_value = (
            json.dumps(operation.summary) if operation.summary else "NULL"
        )
        lines.extend(
            [
                f'    "{operation.operation_id}" = list(',
                f'      operation_id = "{operation.operation_id}",',
                f'      method = "{operation.method}",',
                f'      path = "{operation.path}",',
                f"      summary = {summary_value}",
                f"    ){suffix}",
            ]
        )

    lines.extend(["  )", "}", ""])
    return "\n".join(lines)


def _write_or_check(path: Path, content: str, *, check: bool) -> list[str]:
    issues: list[str] = []
    if check:
        current = path.read_text(encoding="utf-8") if path.exists() else None
        if current != content:
            issues.append(f"stale generated client artifact: {path}")
        return issues

    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    return issues


def _generate_target(target: GenerationTarget, *, check: bool) -> list[str]:
    operations = _load_operations(target.spec_path)
    issues: list[str] = []
    issues.extend(
        _write_or_check(
            target.ts_output_path,
            _render_typescript(operations),
            check=check,
        )
    )
    issues.extend(
        _write_or_check(
            target.r_output_path,
            _render_r(operations, target.catalog_function_name),
            check=check,
        )
    )
    return issues


def parse_args() -> argparse.Namespace:
    """Parse CLI arguments for generated client catalog management."""
    parser = argparse.ArgumentParser(
        description="Generate lightweight TS/R SDK catalogs from OpenAPI.",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Fail if generated outputs are stale.",
    )
    return parser.parse_args()


def main() -> int:
    """Generate client catalogs or fail when committed artifacts drift."""
    args = parse_args()
    issues: list[str] = []
    for target in TARGETS:
        issues.extend(_generate_target(target, check=args.check))

    if issues:
        for issue in issues:
            print(issue)
        return 1

    message = (
        "generated client artifacts are current"
        if args.check
        else "generated client artifacts updated"
    )
    print(message)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
