#!/usr/bin/env python3
# ruff: noqa: E501
"""R SDK generation helpers."""

from __future__ import annotations

import re
import sys
from pathlib import Path

if __package__ in {None, ""}:  # pragma: no cover - direct script execution
    sys.path.insert(0, str(Path(__file__).resolve().parents[2]))

from scripts.release.sdk_common import (
    GenerationTarget,
    Operation,
    _load_operations,
)

_R_PACKAGE_MAINTAINER = (
    'person("Nova SDK Team", email = "sdk@nova.invalid", '
    'role = c("aut", "cre"))'
)
_DEFAULT_R_PACKAGE_VERSION = "0.1.0"


def _r_operation_function_name(prefix: str, operation_id: str) -> str:
    """Return the exported R function name for one operation."""
    return f"{prefix}_{operation_id}"


def _r_exported_function_names(
    prefix: str, operations: list[Operation]
) -> tuple[str, ...]:
    """Return the exported R function names for a client prefix."""
    exports = [
        f"create_{prefix}_client",
        f"{prefix}_bearer_token",
    ]
    exports.extend(
        _r_operation_function_name(prefix, operation.operation_id)
        for operation in operations
    )
    return tuple(exports)


def _r_package_doc_filename(target: GenerationTarget) -> str:
    """Return the Rd filename for the generated R package docs."""
    return f"{target.r_package_name}.Rd"


def _r_parameter_name(name: str) -> str:
    normalized = re.sub(r"[^a-z0-9]+", "_", name.strip().lower()).strip("_")
    if not normalized:
        return "param"
    if normalized[0].isdigit():
        return f"param_{normalized}"
    return normalized


def _r_operation_signature(prefix: str, operation: Operation) -> str:
    parts = ["client"]
    if operation.has_request_body:
        parts.append("body")
    if operation.has_path_params:
        parts.extend(
            _r_parameter_name(parameter.name)
            for parameter in operation.path_parameters
        )
    if operation.has_query_params:
        parts.extend(
            (
                _r_parameter_name(parameter.name)
                if parameter.required
                else f"{_r_parameter_name(parameter.name)} = NULL"
            )
            for parameter in operation.query_parameters
        )
    parts.append("headers = NULL")
    return f"{prefix}_{operation.operation_id}({', '.join(parts)})"


def _r_operation_manual_section(prefix: str, operation: Operation) -> list[str]:
    signature = _r_operation_signature(prefix, operation)
    description = (
        operation.summary.strip()
        if operation.summary is not None and operation.summary.strip()
        else f"Calls the {operation.method} {operation.path} endpoint."
    )
    lines = [
        f"\\section{{{prefix}_{operation.operation_id}}}{{",
        f"  \\code{{{signature}}}",
        "",
        f"  {description}",
        "",
        "  \\describe{",
        f"    \\item{{client}}{{Thin client created by \\code{{create_{prefix}_client()}}.}}",
    ]
    if operation.has_request_body:
        lines.append(
            "    \\item{body}{Request payload for this operation, encoded as JSON.}"
        )
    for parameter in operation.path_parameters:
        lines.extend(
            [
                f"    \\item{{{parameter.name}}}{{Path parameter \\code{{{parameter.name}}}.}}",
            ]
        )
    for parameter in operation.query_parameters:
        qualifier = "Query" if parameter.required else "Optional query"
        lines.extend(
            [
                f"    \\item{{{parameter.name}}}{{{qualifier} parameter \\code{{{parameter.name}}}.}}",
            ]
        )
    lines.extend(
        [
            "    \\item{headers}{Optional named list of per-request headers.}",
            "    \\item{Returns}{Parsed JSON response as a named list, or NULL when the response body is empty.}",
            "  }",
            "}",
            "",
        ]
    )
    return lines


def _render_r_license_text(target: GenerationTarget) -> str:
    """Render the internal R package license notice text."""
    return "\n".join(
        [
            f"{target.r_package_title}",
            "",
            "Copyright (c) 2026 3M Cloud. All rights reserved.",
            "",
            "This package is generated for internal Nova use only.",
            "All rights reserved.",
            "",
        ]
    )


def _render_r(operations: list[Operation], catalog_function_name: str) -> str:
    prefix = catalog_function_name.removesuffix("_operation_catalog")
    lines = [
        "# Code generated by scripts/release/r_sdk.py. DO NOT EDIT.",
        "",
    ]

    for operation in operations:
        function_name = _r_operation_function_name(
            prefix, operation.operation_id
        )
        signature_parts = ["client"]
        call_parts = [
            "    client = client,",
            f'    operation_id = "{operation.operation_id}",',
            f'    method = "{operation.method}",',
            f'    path = "{operation.path}",',
        ]
        if operation.has_request_body:
            signature_parts.append(
                "body" if operation.has_required_request_body else "body = NULL"
            )
            call_parts.append("    body = body,")
        if operation.has_path_params:
            path_args = [
                _r_parameter_name(parameter.name)
                for parameter in operation.path_parameters
            ]
            signature_parts.extend(path_args)
            path_params = ", ".join(
                f"{parameter.name} = {_r_parameter_name(parameter.name)}"
                for parameter in operation.path_parameters
            )
            call_parts.append(f"    path_params = list({path_params}),")
        if operation.has_query_params:
            signature_parts.extend(
                (
                    _r_parameter_name(parameter.name)
                    if parameter.required
                    else f"{_r_parameter_name(parameter.name)} = NULL"
                )
                for parameter in operation.query_parameters
            )
            query_params = ", ".join(
                f"{parameter.name} = {_r_parameter_name(parameter.name)}"
                for parameter in operation.query_parameters
            )
            call_parts.append(f"    query = list({query_params}),")
        signature_parts.append("headers = NULL")
        call_parts.append("    headers = headers,")
        call_parts.extend(
            [
                f"    requires_body = {'TRUE' if operation.has_required_request_body else 'FALSE'},",
                f"    accepts_body = {'TRUE' if operation.has_request_body else 'FALSE'}",
            ]
        )
        lines.extend(
            [
                f"{function_name} <- function(",
                "  " + ",\n  ".join(signature_parts),
                ") {",
                f"  {prefix}_api_call(",
                *call_parts,
                "  )",
                "}",
                "",
            ]
        )
    return "\n".join(lines)


def _render_r_client(target: GenerationTarget) -> str:
    prefix = target.r_client_prefix
    client_constructor = f"create_{prefix}_client"
    error_class_name = f"{prefix}_api_error"
    bearer_env_var = f"{prefix.upper()}_BEARER_TOKEN"
    lines = [
        "# Code generated by scripts/release/r_sdk.py. DO NOT EDIT.",
        "",
        f"{prefix}_null_coalesce <- function(value, fallback) {{",
        "  if (is.null(value)) {",
        "    fallback",
        "  } else {",
        "    value",
        "  }",
        "}",
        "",
        f"{prefix}_normalize_named_list <- function(value, label) {{",
        "  if (is.null(value)) {",
        "    return(list())",
        "  }",
        "  if (is.atomic(value) && !is.list(value)) {",
        "    value <- as.list(value)",
        "  }",
        "  if (!is.list(value)) {",
        '    stop(sprintf("%s must be a named list", label), call. = FALSE)',
        "  }",
        "  item_names <- names(value)",
        "  if (is.null(item_names)) {",
        '    stop(sprintf("%s must be a named list", label), call. = FALSE)',
        "  }",
        "  cleaned <- list()",
        "  for (index in seq_along(value)) {",
        "    item_name <- item_names[[index]]",
        "    if (is.na(item_name) || !nzchar(item_name)) {",
        '      stop(sprintf("%s names must be non-empty", label), call. = FALSE)',
        "    }",
        "    item_value <- value[[index]]",
        "    if (is.null(item_value)) {",
        "      next",
        "    }",
        "    cleaned[[item_name]] <- item_value",
        "  }",
        "  cleaned",
        "}",
        "",
        f"{prefix}_normalize_base_url <- function(base_url) {{",
        "  if (!is.character(base_url) || length(base_url) != 1L || !nzchar(base_url)) {",
        '    stop("base_url must be a non-empty string", call. = FALSE)',
        "  }",
        '  trimmed <- sub("/+$", "", base_url)',
        "  if (!nzchar(trimmed)) {",
        '    stop("base_url must remain usable after trimming trailing slashes", call. = FALSE)',
        "  }",
        "  trimmed",
        "}",
        "",
        f"{prefix}_resolve_path <- function(path, path_params) {{",
        f'  path_params <- {prefix}_normalize_named_list(path_params, "path_params")',
        "  resolved_path <- path",
        "  if (length(path_params) > 0L) {",
        "    for (param_name in names(path_params)) {",
        "      resolved_path <- gsub(",
        '        sprintf("{%s}", param_name),',
        "        utils::URLencode(as.character(path_params[[param_name]]), reserved = TRUE),",
        "        resolved_path,",
        "        fixed = TRUE",
        "      )",
        "    }",
        "  }",
        "  missing_path_params <- regmatches(",
        '    resolved_path, gregexpr("\\\\{[^}]+\\\\}", resolved_path, perl = TRUE)',
        "  )[[1]]",
        "  if (length(missing_path_params) > 0L) {",
        '    stop(sprintf("missing path parameter(s): %s", paste(missing_path_params, collapse = ", ")), call. = FALSE)',
        "  }",
        "  resolved_path",
        "}",
        "",
        f"{prefix}_parse_json_response <- function(response) {{",
        "  if (length(httr2::resp_body_raw(response)) == 0L) {",
        "    return(NULL)",
        "  }",
        "  httr2::resp_body_json(response, simplifyVector = FALSE, check_type = FALSE)",
        "}",
        "",
        f"{prefix}_parse_success_response <- function(response) {{",
        f"  {prefix}_parse_json_response(response)",
        "}",
        "",
        f"{prefix}_response_body_text <- function(response) {{",
        "  if (length(httr2::resp_body_raw(response)) == 0L) {",
        '    return("")',
        "  }",
        "  httr2::resp_body_string(response)",
        "}",
        "",
        f"{prefix}_default_user_agent <- function() {{",
        f'  sprintf("{target.r_package_name}/%s", utils::packageVersion("{target.r_package_name}"))',
        "}",
        "",
        f"{prefix}_bearer_token <- function(token = NULL, env_var = {bearer_env_var!r}) {{",
        "  if (!is.null(token)) {",
        "    token_chr <- as.character(token)",
        "    if (length(token_chr) == 0L) {",
        "      return(NULL)",
        "    }",
        "    token_value <- token_chr[[1L]]",
        "    if (is.na(token_value) || !nzchar(token_value)) {",
        "      return(NULL)",
        "    }",
        "    return(token_value)",
        "  }",
        "  env_var_chr <- as.character(env_var)",
        "  if (length(env_var_chr) == 0L) {",
        "    return(NULL)",
        "  }",
        "  env_var_value <- env_var_chr[[1L]]",
        "  if (is.na(env_var_value) || !nzchar(env_var_value)) {",
        "    return(NULL)",
        "  }",
        "  env_value <- Sys.getenv(env_var_value, unset = '')",
        "  if (!nzchar(env_value)) {",
        "    return(NULL)",
        "  }",
        "  env_value",
        "}",
        "",
        f"{prefix}_normalize_user_agent <- function(user_agent = NULL) {{",
        "  if (is.null(user_agent)) {",
        "    return(NULL)",
        "  }",
        "  user_agent_chr <- as.character(user_agent)",
        "  if (length(user_agent_chr) == 0L) {",
        "    return(NULL)",
        "  }",
        "  user_agent_value <- user_agent_chr[[1L]]",
        "  if (is.na(user_agent_value) || !nzchar(user_agent_value)) {",
        "    return(NULL)",
        "  }",
        "  user_agent_value",
        "}",
        "",
        f"{prefix}_decode_error_envelope <- function(response, status = NULL) {{",
        "  parsed_body <- tryCatch(",
        f"    {prefix}_parse_json_response(response),",
        "    error = function(...) NULL",
        "  )",
        "  fallback_status <- if (is.null(status)) 'unknown' else as.character(status)",
        '  fallback_code <- paste0("http_", fallback_status)',
        f"  fallback_message <- if (!nzchar({prefix}_response_body_text(response))) {{",
        '    sprintf("HTTP %s response", fallback_status)',
        "  } else {",
        f"    {prefix}_response_body_text(response)",
        "  }",
        "  if (!is.list(parsed_body) || is.null(parsed_body$error) || !is.list(parsed_body$error)) {",
        "    return(",
        "      list(",
        "        code = fallback_code,",
        "        message = fallback_message,",
        "        details = list(),",
        "        request_id = NULL",
        "      )",
        "    )",
        "  }",
        "  error_body <- parsed_body$error",
        "  request_id <- error_body$request_id",
        "  if (length(request_id) == 0L) {",
        "    request_id <- NULL",
        "  }",
        "  error_code <- error_body$code",
        "  if (length(error_code) == 0L) {",
        "    error_code <- fallback_code",
        "  } else {",
        "    error_code <- as.character(error_code[[1L]])",
        "    if (is.na(error_code) || !nzchar(error_code)) {",
        "      error_code <- fallback_code",
        "    }",
        "  }",
        "  error_message <- error_body$message",
        "  if (length(error_message) == 0L) {",
        "    error_message <- fallback_message",
        "  } else {",
        "    error_message <- as.character(error_message[[1L]])",
        "    if (is.na(error_message) || !nzchar(error_message)) {",
        "      error_message <- fallback_message",
        "    }",
        "  }",
        "  list(",
        "    code = error_code,",
        "    message = error_message,",
        f"    details = {prefix}_null_coalesce(error_body$details, list()),",
        "    request_id = request_id",
        "  )",
        "}",
        "",
        f"{prefix}_error_body <- function(response) {{",
        f"  error <- {prefix}_decode_error_envelope(response, status = httr2::resp_status(response))",
        '  sprintf("[%s] %s", error$code, error$message)',
        "}",
        "",
        f"{prefix}_error_condition <- function(error, status, operation_id, method, path, response = NULL, parent = NULL) {{",
        "  structure(",
        "    list(",
        "      message = error$message,",
        "      call = NULL,",
        "      code = error$code,",
        "      status = status,",
        "      request_id = error$request_id,",
        "      details = error$details,",
        "      operation_id = operation_id,",
        "      method = method,",
        "      path = path,",
        "      resp = response,",
        "      parent = parent",
        "    ),",
        f'    class = c("{error_class_name}", parent, "error", "condition")',
        "  )",
        "}",
        "",
        f"conditionMessage.{error_class_name} <- function(c) {{",
        '  sprintf("[%s] %s", c$code, c$message)',
        "}",
        "",
        f"{prefix}_apply_request <- function(http_request, request_headers, bearer_token, user_agent) {{",
        "  if (length(request_headers) > 0L) {",
        "    http_request <- do.call(httr2::req_headers, c(list(http_request), request_headers))",
        "  }",
        "  if (!is.null(user_agent) && nzchar(user_agent)) {",
        "    http_request <- httr2::req_user_agent(http_request, user_agent)",
        "  }",
        '  has_authorization <- any(tolower(names(request_headers)) == "authorization")',
        "  if (!is.null(bearer_token) && nzchar(bearer_token) && !has_authorization) {",
        "    http_request <- httr2::req_auth_bearer_token(http_request, bearer_token)",
        "  }",
        "  http_request",
        "}",
        "",
        f"{prefix}_api_call <- function(",
        "  client,",
        "  operation_id,",
        "  method,",
        "  path,",
        "  body = NULL,",
        "  path_params = NULL,",
        "  query = NULL,",
        "  headers = NULL,",
        "  requires_body = FALSE,",
        "  accepts_body = FALSE",
        ") {",
        f'  if (!inherits(client, "{prefix}_client")) {{',
        f'    stop("client must be created by create_{prefix}_client()", call. = FALSE)',
        "  }",
        f'  query <- {prefix}_normalize_named_list(query, "query")',
        f'  request_headers <- {prefix}_normalize_named_list(headers, "headers")',
        "  merged_headers <- c(client$default_headers, request_headers)",
        "  if (length(merged_headers) > 0L) {",
        "    merged_headers <- merged_headers[!duplicated(tolower(names(merged_headers)), fromLast = TRUE)]",
        "  }",
        f"  resolved_path <- {prefix}_resolve_path(path, path_params)",
        "  if (is.null(body) && isTRUE(requires_body)) {",
        '    stop(sprintf("operation %s requires a request body", operation_id), call. = FALSE)',
        "  }",
        "  if (!is.null(body) && !isTRUE(accepts_body)) {",
        '    stop(sprintf("operation %s does not accept a request body", operation_id), call. = FALSE)',
        "  }",
        "  http_request <- httr2::request(paste0(client$base_url, resolved_path))",
        "  http_request <- httr2::req_method(http_request, method)",
        "  if (length(query) > 0L) {",
        "    http_request <- do.call(httr2::req_url_query, c(list(http_request), query))",
        "  }",
        f"  http_request <- {prefix}_apply_request(http_request, merged_headers, client$bearer_token, client$user_agent)",
        "  http_request <- httr2::req_options(http_request, timeout = client$timeout_seconds)",
        "  if (!is.null(body)) {",
        '    http_request <- httr2::req_body_json(http_request, body, auto_unbox = TRUE, null = "null")',
        "  }",
        "  http_request <- httr2::req_error(http_request, body = function(resp) {",
        f"    {prefix}_error_body(resp)",
        "  })",
        "  tryCatch(",
        "    {",
        "      response <- httr2::req_perform(http_request)",
        f"      {prefix}_parse_success_response(response)",
        "    },",
        "    httr2_http = function(cnd) {",
        f"      error <- {prefix}_decode_error_envelope(cnd$resp, status = cnd$status)",
        "      stop(",
        f"        {prefix}_error_condition(",
        "          error = error,",
        "          status = cnd$status,",
        "          operation_id = operation_id,",
        "          method = method,",
        "          path = resolved_path,",
        "          response = cnd$resp,",
        "          parent = class(cnd)",
        "        )",
        "      )",
        "    }",
        "  )",
        "}",
        "",
        f"{client_constructor} <- function(",
        "  base_url,",
        "  bearer_token = NULL,",
        f"  bearer_token_env = {bearer_env_var!r},",
        "  default_headers = NULL,",
        "  timeout_seconds = 30,",
        "  user_agent = NULL",
        ") {",
        f"  base_url <- {prefix}_normalize_base_url(base_url)",
        "  if (!is.numeric(timeout_seconds) || length(timeout_seconds) != 1L || is.na(timeout_seconds) || !is.finite(timeout_seconds) || timeout_seconds <= 0) {",
        '    stop("timeout_seconds must be a finite positive number", call. = FALSE)',
        "  }",
        f'  default_headers <- {prefix}_normalize_named_list(default_headers, "default_headers")',
        "  client <- list(",
        "    base_url = base_url,",
        f"    bearer_token = {prefix}_bearer_token(token = bearer_token, env_var = bearer_token_env),",
        "    default_headers = default_headers,",
        "    timeout_seconds = timeout_seconds,",
        f"    user_agent = {prefix}_null_coalesce({prefix}_normalize_user_agent(user_agent), {prefix}_default_user_agent())",
        "  )",
        f'  class(client) <- c("{prefix}_client", "list")',
        "  client",
        "}",
        "",
    ]
    return "\n".join(lines)


def _resolve_r_package_version(package_root: Path) -> str:
    description_path = package_root / "DESCRIPTION"
    if not description_path.exists():
        return _DEFAULT_R_PACKAGE_VERSION

    version_pattern = re.compile(r"(?m)^Version:\s*([^\n]+)\s*$")
    match = version_pattern.search(description_path.read_text(encoding="utf-8"))
    if match is None:
        raise ValueError(
            f"DESCRIPTION version field not found: {description_path}"
        )

    version = match.group(1).strip()
    if not version:
        raise ValueError(
            f"DESCRIPTION version field must be non-empty: {description_path}"
        )
    return version


def _render_r_description(target: GenerationTarget) -> str:
    package_root = target.r_output_path.parent.parent
    version = _resolve_r_package_version(package_root)
    lines = [
        f"Package: {target.r_package_name}",
        "Type: Package",
        f"Title: {target.r_package_title}",
        f"Version: {version}",
        f"Authors@R: {_R_PACKAGE_MAINTAINER}",
        f"Description: {target.r_package_description}",
        "License: file LICENSE",
        "Encoding: UTF-8",
        "Roxygen: list(markdown = TRUE)",
        "RoxygenNote: 7.3.3",
        "Imports:",
        "    httr2",
        "Suggests:",
        "    testthat (>= 3.2.3),",
        "    withr (>= 3.0.2)",
        "Config/testthat/edition: 3",
        "",
    ]
    return "\n".join(lines)


def _render_r_namespace(target: GenerationTarget) -> str:
    _, operations = _load_operations(target.spec_path)
    exports = _r_exported_function_names(target.r_client_prefix, operations)
    error_class_name = f"{target.r_client_prefix}_api_error"
    lines = [
        "# Generated by roxygen2: do not edit by hand",
        "",
        f"S3method(conditionMessage,{error_class_name})",
        "",
    ]
    lines.extend(f"export({name})" for name in exports)
    lines.append("")
    return "\n".join(lines)


def _render_r_readme(target: GenerationTarget) -> str:
    client_prefix = target.r_client_prefix
    constructor = f"create_{client_prefix}_client"
    operation_prefix = client_prefix
    lines = [
        f"# `{target.r_package_name}`",
        "",
        f"{target.r_package_description}",
        "",
        "This package is generated from committed OpenAPI and is kept in-repo so",
        "Nova release tooling can build and check the real package tree.",
        "The generated client is intentionally thin and follows the current",
        "public Nova API contract: bearer JWT auth, JSON bodies, concrete",
        "path/query parameters, and plain R list responses.",
        "",
        "## Surface",
        "",
        f"- `{constructor}`",
        f"- `{target.r_client_prefix}_bearer_token`",
        f"- endpoint wrappers named `{target.r_client_prefix}_<operation_id>`",
        "",
        "## Example",
        "",
        "```r",
        f"client <- {constructor}(",
        '  "https://nova.example/",',
        '  bearer_token = "eyJhbGciOi…",',
        ")",
        "",
        f"result <- {operation_prefix}_create_export(",
        "  client,",
        "  body = list(",
        '    source_key = "uploads/scope-1/source.csv",',
        '    filename = "source.csv"',
        "  ),",
        '  headers = list("Idempotency-Key" = "req-123")',
        ")",
        "result$export_id",
        "result$status",
        "",
        f"exports <- {operation_prefix}_list_exports(client, limit = 25)",
        f"export <- {operation_prefix}_get_export(client, export_id = result$export_id)",
        "```",
        "",
    ]
    return "\n".join(lines)


def _render_r_package_manual(target: GenerationTarget) -> str:
    _, operations = _load_operations(target.spec_path)
    exports = _r_exported_function_names(target.r_client_prefix, operations)
    constructor = f"create_{target.r_client_prefix}_client"
    bearer_helper = f"{target.r_client_prefix}_bearer_token"
    bearer_env_var = f"{target.r_client_prefix.upper()}_BEARER_TOKEN"
    package_name = target.r_package_name
    lines = [
        f"\\name{{{package_name}}}",
        "",
    ]
    lines.extend(f"\\alias{{{name}}}" for name in (package_name, *exports))
    lines.extend(
        [
            "\\docType{package}",
            f"\\title{{{target.r_package_title}}}",
            f"\\description{{{target.r_package_description}}}",
            "\\usage{",
            f'  {constructor}(base_url, bearer_token = NULL, bearer_token_env = "{bearer_env_var}", default_headers = NULL, timeout_seconds = 30, user_agent = NULL)',
            f'  {bearer_helper}(token = NULL, env_var = "{bearer_env_var}")',
            "}",
            "",
            "\\arguments{",
            "  \\item{base_url}{Base URL for the Nova API, without a trailing slash requirement.}",
            "  \\item{bearer_token}{Explicit bearer token used for Authorization headers when request headers do not already provide one.}",
            "  \\item{bearer_token_env}{Environment variable name used as an optional bearer-token fallback.}",
            "  \\item{default_headers}{Named list of default request headers applied to every request.}",
            "  \\item{timeout_seconds}{Positive request timeout in seconds.}",
            "  \\item{user_agent}{Optional explicit user agent string.}",
            "  \\item{token}{Explicit bearer token string.}",
            "  \\item{env_var}{Environment variable name used to resolve a bearer token.}",
            "}",
            "",
            "\\value{",
            "  The constructor returns a thin client configuration object.",
            "  The bearer-token helper returns an explicit or environment-derived token, or NULL when none is available.",
            "}",
            "",
        ]
    )
    for operation in operations:
        lines.extend(
            _r_operation_manual_section(target.r_client_prefix, operation)
        )
    lines.extend(
        [
            "\\keyword{package}",
            "",
        ]
    )
    return "\n".join(lines)


def _render_r_tests_entrypoint(target: GenerationTarget) -> str:
    lines = [
        "library(testthat)",
        f'library("{target.r_package_name}", character.only = TRUE)',
        f'test_check("{target.r_package_name}")',
        "",
    ]
    return "\n".join(lines)


def _render_r_tests(target: GenerationTarget) -> str:
    client_prefix = target.r_client_prefix
    constructor = f"create_{client_prefix}_client"
    default_user_agent = f"{client_prefix}_default_user_agent()"
    bearer_env_var = f"{client_prefix.upper()}_BEARER_TOKEN"
    namespace = target.r_package_name
    operation_prefix = client_prefix
    api_error_class = f"{client_prefix}_api_error"
    lines = [
        'test_that("constructor resolves explicit and environment bearer tokens", {',
        f'  withr::local_envvar({bearer_env_var} = "env-token-123")',
        f'  env_client <- {constructor}("https://nova.example/")',
        '  expect_equal(env_client$bearer_token, "env-token-123")',
        f'  explicit_client <- {constructor}("https://nova.example/", bearer_token = "explicit-token-123")',
        '  expect_equal(explicit_client$bearer_token, "explicit-token-123")',
        "})",
        "",
        'test_that("constructor treats zero-length bearer tokens as absent", {',
        f"  withr::local_envvar({bearer_env_var} = NA_character_)",
        f'  client <- {constructor}("https://nova.example/", bearer_token = character(0))',
        "  expect_null(client$bearer_token)",
        "})",
        "",
        'test_that("constructor rejects unusable base URLs after trimming", {',
        f'  expect_error({constructor}("/"), "base_url must remain usable after trimming trailing slashes", fixed = TRUE)',
        "})",
        "",
        'test_that("constructor normalizes invalid user agents to the default", {',
        f'  client <- {constructor}("https://nova.example/", user_agent = character(0))',
        f"  expect_equal(client$user_agent, {default_user_agent})",
        f'  client_na <- {constructor}("https://nova.example/", user_agent = NA_character_)',
        f"  expect_equal(client_na$user_agent, {default_user_agent})",
        "})",
        "",
        'test_that("generated package exports thin endpoint wrappers", {',
        f'  exports <- getNamespaceExports("{namespace}")',
        f'  expect_true("{operation_prefix}_create_export" %in% exports)',
        f'  expect_true("{operation_prefix}_get_export" %in% exports)',
        f'  expect_true("{operation_prefix}_list_exports" %in% exports)',
        f'  expect_true("{operation_prefix}_cancel_export" %in% exports)',
        f'  expect_false("{operation_prefix}_request_descriptor" %in% exports)',
        f'  expect_false("{operation_prefix}_execute_operation" %in% exports)',
        "})",
        "",
        'test_that("request construction uses concrete params and bearer auth", {',
        "  observed_request <- NULL",
        "  mocked_response <- httr2::response(",
        "    status_code = 200,",
        '    url = "https://nova.example/v1/exports/export-123",',
        '    headers = list(`content-type` = "application/json"),',
        '    body = charToRaw(\'{"export_id":"export-123","source_key":"uploads/scope-1/source.csv","filename":"source.csv","status":"queued","output":null,"error":null,"created_at":"2026-03-25T00:00:00Z","updated_at":"2026-03-25T00:00:00Z"}\')',
        "  )",
        f"  withr::local_envvar({bearer_env_var} = NA_character_)",
        "  result <- httr2::with_mocked_responses(",
        "    function(req) {",
        "      observed_request <<- req",
        "      mocked_response",
        "    },",
        "    {",
        f'      client <- {constructor}("https://nova.example/", bearer_token = "token-123", timeout_seconds = 12)',
        f'      {operation_prefix}_get_export(client, export_id = "export-123", headers = list(`X-Request-Id` = "req-123"))',
        "    }",
        "  )",
        '  expect_equal(result$export_id, "export-123")',
        '  expect_equal(result$status, "queued")',
        '  expect_equal(observed_request$url, "https://nova.example/v1/exports/export-123")',
        '  expect_equal(observed_request$method, "GET")',
        '  expect_true("Authorization" %in% names(observed_request$headers))',
        '  expect_equal(observed_request$headers$`X-Request-Id`, "req-123")',
        "  expect_equal(observed_request$options$timeout, 12)",
        "})",
        "",
        'test_that("lowercase authorization headers suppress bearer injection", {',
        "  observed_request <- NULL",
        "  mocked_response <- httr2::response(",
        "    status_code = 200,",
        '    url = "https://nova.example/v1/exports/export-123",',
        '    headers = list(`content-type` = "application/json"),',
        '    body = charToRaw(\'{"export_id":"export-123","source_key":"uploads/scope-1/source.csv","filename":"source.csv","status":"queued","output":null,"error":null,"created_at":"2026-03-25T00:00:00Z","updated_at":"2026-03-25T00:00:00Z"}\')',
        "  )",
        "  result <- httr2::with_mocked_responses(",
        "    function(req) {",
        "      observed_request <<- req",
        "      mocked_response",
        "    },",
        "    {",
        f'      client <- {constructor}("https://nova.example/", bearer_token = "token-123")',
        f'      {operation_prefix}_get_export(client, export_id = "export-123", headers = list(authorization = "Bearer custom"))',
        "    }",
        "  )",
        '  auth_positions <- which(tolower(names(observed_request$headers)) == "authorization")',
        "  expect_length(auth_positions, 1L)",
        '  expect_identical(names(observed_request$headers)[auth_positions[[1L]]], "authorization")',
        '  expect_equal(result$export_id, "export-123")',
        "})",
        "",
        'test_that("request construction encodes query params and JSON bodies", {',
        "  observed_requests <- list()",
        "  mocked_response <- httr2::response(",
        "    status_code = 200,",
        '    url = "https://nova.example/v1/exports",',
        '    headers = list(`content-type` = "application/json"),',
        "    body = charToRaw('{\"exports\":[]}')",
        "  )",
        "  httr2::with_mocked_responses(",
        "    function(req) {",
        "      observed_requests[[length(observed_requests) + 1L]] <<- req",
        "      mocked_response",
        "    },",
        "    {",
        f'      client <- {constructor}("https://nova.example/", bearer_token = "token-123")',
        f"      {operation_prefix}_list_exports(client, limit = 25)",
        f"      {operation_prefix}_create_export(",
        "        client,",
        "        body = list(",
        '          source_key = "uploads/scope-1/source.csv",',
        '          filename = "source.csv"',
        "        ),",
        '        headers = list("Idempotency-Key" = "req-123")',
        "      )",
        "    }",
        "  )",
        "  expect_length(observed_requests, 2L)",
        '  expect_equal(observed_requests[[1]]$method, "GET")',
        '  expect_equal(observed_requests[[1]]$url, "https://nova.example/v1/exports?limit=25")',
        '  expect_equal(observed_requests[[2]]$method, "POST")',
        '  expect_equal(observed_requests[[2]]$url, "https://nova.example/v1/exports")',
        '  expect_equal(observed_requests[[2]]$headers$`Idempotency-Key`, "req-123")',
        '  expect_equal(observed_requests[[2]]$body$content_type, "application/json")',
        '  expect_equal(observed_requests[[2]]$body$data$source_key, "uploads/scope-1/source.csv")',
        '  expect_equal(observed_requests[[2]]$body$data$filename, "source.csv")',
        "})",
        "",
        'test_that("structured errors preserve Nova error envelope fields", {',
        "  mocked_response <- httr2::response(",
        "    status_code = 503,",
        '    url = "https://nova.example/v1/exports",',
        '    headers = list(`content-type` = "application/json"),',
        '    body = charToRaw(\'{"error":{"code":"queue_unavailable","message":"export creation failed because queue publish failed","request_id":"req-exports-503","details":{"backend":"sqs"}}}\')',
        "  )",
        "  error <- tryCatch(",
        "    httr2::with_mocked_responses(",
        "      function(req) mocked_response,",
        "      {",
        f'        client <- {constructor}("https://nova.example/", bearer_token = "token-123")',
        f'        {operation_prefix}_create_export(client, body = list(source_key = "uploads/scope-1/source.csv", filename = "source.csv"))',
        "      }",
        "    ),",
        f"    {api_error_class} = function(error) error",
        "  )",
        f'  expect_s3_class(error, "{api_error_class}")',
        '  expect_true(inherits(error, "httr2_http"))',
        '  expect_equal(error$code, "queue_unavailable")',
        "  expect_equal(error$status, 503L)",
        '  expect_equal(error$request_id, "req-exports-503")',
        '  expect_equal(error$details$backend, "sqs")',
        "  expect_equal(httr2::resp_status(error$resp), 503L)",
        '  expect_equal(conditionMessage(error), "[queue_unavailable] export creation failed because queue publish failed")',
        "})",
        "",
        'test_that("structured errors fall back when code or message is missing", {',
        "  mocked_response <- httr2::response(",
        "    status_code = 503,",
        '    url = "https://nova.example/v1/exports",',
        '    headers = list(`content-type` = "application/json"),',
        '    body = charToRaw(\'{"error":{"details":{"backend":"sqs"}}}\')',
        "  )",
        "  error <- tryCatch(",
        "    httr2::with_mocked_responses(",
        "      function(req) mocked_response,",
        "      {",
        f'        client <- {constructor}("https://nova.example/", bearer_token = "token-123")',
        f'        {operation_prefix}_create_export(client, body = list(source_key = "uploads/scope-1/source.csv", filename = "source.csv"))',
        "      }",
        "    ),",
        f"    {api_error_class} = function(error) error",
        "  )",
        f'  expect_s3_class(error, "{api_error_class}")',
        '  expect_equal(error$code, "http_503")',
        '  expect_match(conditionMessage(error), "http_503", fixed = TRUE)',
        "})",
        "",
        'test_that("structured errors fall back to raw body text for non-JSON responses", {',
        "  mocked_response <- httr2::response(",
        "    status_code = 503,",
        '    url = "https://nova.example/v1/exports",',
        '    headers = list(`content-type` = "text/plain"),',
        '    body = charToRaw("service unavailable")',
        "  )",
        "  error <- tryCatch(",
        "    httr2::with_mocked_responses(",
        "      function(req) mocked_response,",
        "      {",
        f'        client <- {constructor}("https://nova.example/", bearer_token = "token-123")',
        f'        {operation_prefix}_create_export(client, body = list(source_key = "uploads/scope-1/source.csv", filename = "source.csv"))',
        "      }",
        "    ),",
        f"    {api_error_class} = function(error) error",
        "  )",
        f'  expect_s3_class(error, "{api_error_class}")',
        '  expect_true(inherits(error, "httr2_http"))',
        '  expect_equal(error$code, "http_503")',
        '  expect_match(conditionMessage(error), "service unavailable", fixed = TRUE)',
        "  expect_equal(httr2::resp_status(error$resp), 503L)",
        "})",
        "",
    ]
    return "\n".join(lines)


def _r_expected_package_files(target: GenerationTarget) -> tuple[Path, ...]:
    package_root = target.r_output_path.parent.parent
    return (
        package_root / "DESCRIPTION",
        package_root / "LICENSE",
        package_root / "NAMESPACE",
        package_root / "README.md",
        package_root / "R" / "client.R",
        package_root / "R" / "generated.R",
        package_root / "man" / _r_package_doc_filename(target),
        package_root / "tests" / "testthat.R",
        package_root / "tests" / "testthat" / "test-client.R",
    )


def _validate_r_package_tree(
    target: GenerationTarget,
    *,
    check: bool,
) -> list[str]:
    package_root = target.r_output_path.parent.parent
    expected_files = {
        path.relative_to(package_root).as_posix()
        for path in _r_expected_package_files(target)
    }

    if not check:
        package_root.mkdir(parents=True, exist_ok=True)
        return []

    if not package_root.exists():
        return [f"missing generated R package directory: {package_root}"]

    actual_files = {
        path.relative_to(package_root).as_posix()
        for path in package_root.rglob("*")
        if path.is_file()
    }
    missing = sorted(expected_files - actual_files)
    extra = sorted(actual_files - expected_files)
    issues: list[str] = []
    if missing:
        issues.append(
            "missing expected generated R package artifacts in "
            f"{package_root}: {', '.join(missing)}"
        )
    if extra:
        issues.append(
            "unexpected generated R package artifacts in "
            f"{package_root}: {', '.join(extra)}"
        )
    return issues


def _write_or_check(path: Path, content: str, *, check: bool) -> list[str]:
    issues: list[str] = []
    if check:
        current = path.read_text(encoding="utf-8") if path.exists() else None
        if current != content:
            issues.append(f"stale generated client artifact: {path}")
        return issues

    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    return issues


def generate_or_check_r_sdk(
    target: GenerationTarget,
    *,
    check: bool,
) -> list[str]:
    """Generate or verify the committed R SDK package tree."""
    _, operations = _load_operations(target.spec_path)
    issues = _validate_r_package_tree(target, check=check)
    issues.extend(
        _write_or_check(
            target.r_output_path.parent.parent / "DESCRIPTION",
            _render_r_description(target),
            check=check,
        )
    )
    issues.extend(
        _write_or_check(
            target.r_output_path.parent.parent / "LICENSE",
            _render_r_license_text(target),
            check=check,
        )
    )
    issues.extend(
        _write_or_check(
            target.r_output_path.parent.parent / "NAMESPACE",
            _render_r_namespace(target),
            check=check,
        )
    )
    issues.extend(
        _write_or_check(
            target.r_output_path.parent.parent / "README.md",
            _render_r_readme(target),
            check=check,
        )
    )
    issues.extend(
        _write_or_check(
            target.r_output_path,
            _render_r(operations, target.catalog_function_name),
            check=check,
        )
    )
    issues.extend(
        _write_or_check(
            target.r_client_output_path,
            _render_r_client(target),
            check=check,
        )
    )
    issues.extend(
        _write_or_check(
            target.r_output_path.parent.parent
            / "man"
            / _r_package_doc_filename(target),
            _render_r_package_manual(target),
            check=check,
        )
    )
    issues.extend(
        _write_or_check(
            target.r_output_path.parent.parent / "tests" / "testthat.R",
            _render_r_tests_entrypoint(target),
            check=check,
        )
    )
    issues.extend(
        _write_or_check(
            target.r_output_path.parent.parent
            / "tests"
            / "testthat"
            / "test-client.R",
            _render_r_tests(target),
            check=check,
        )
    )
    return issues
