name: RShiny Minimal Nova Deploy Validate

on:
  workflow_dispatch:
    inputs:
      nova_deploy_output_json:
        required: true
        type: string

jobs:
  validate:
    uses: 3M-Cloud/nova/.github/workflows/reusable-post-deploy-validate.yml@REPLACE_WITH_IMMUTABLE_SHA
    with:
      deploy_repo: 3M-Cloud/nova
      deploy_output_json: ${{ inputs.nova_deploy_output_json }}
