// This file is auto-generated by @hey-api/openapi-ts

import { client } from './client.gen.js';
import type { Client, Options as Options2, TDataShape } from './client/index.js';
import type { AbortUploadData, AbortUploadErrors, AbortUploadResponses, CancelExportData, CancelExportErrors, CancelExportResponses, CompleteUploadData, CompleteUploadErrors, CompleteUploadResponses, CreateExportData, CreateExportErrors, CreateExportResponses, GetCapabilitiesData, GetCapabilitiesResponses, GetExportData, GetExportErrors, GetExportResponses, GetReleaseInfoData, GetReleaseInfoResponses, GetTransferCapabilitiesData, GetTransferCapabilitiesErrors, GetTransferCapabilitiesResponses, HealthLiveData, HealthLiveResponses, HealthReadyData, HealthReadyErrors, HealthReadyResponses, InitiateUploadData, InitiateUploadErrors, InitiateUploadResponses, IntrospectUploadData, IntrospectUploadErrors, IntrospectUploadResponses, ListExportsData, ListExportsErrors, ListExportsResponses, MetricsSummaryData, MetricsSummaryErrors, MetricsSummaryResponses, PlanResourcesData, PlanResourcesErrors, PlanResourcesResponses, PresignDownloadData, PresignDownloadErrors, PresignDownloadResponses, SignUploadPartsData, SignUploadPartsErrors, SignUploadPartsResponses } from './types.gen.js';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Get metrics summary.
 *
 * Return low-cardinality counters, latency summaries, and activity rollups for dashboards.
 *
 * @param options - request options including client, security, and request overrides.
 * @returns Low-cardinality metrics and activity summary.
 */
export const metricsSummary = <ThrowOnError extends boolean = false>(options?: Options<MetricsSummaryData, ThrowOnError>) => (options?.client ?? client).get<MetricsSummaryResponses, MetricsSummaryErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/metrics/summary',
    ...options
});

/**
 * Get runtime capability declarations.
 *
 * Expose the major runtime capabilities enabled for the current Nova deployment.
 *
 * @param options - request options including client, security, and request overrides.
 * @returns Runtime capability declarations for the deployment.
 */
export const getCapabilities = <ThrowOnError extends boolean = false>(options?: Options<GetCapabilitiesData, ThrowOnError>) => (options?.client ?? client).get<GetCapabilitiesResponses, unknown, ThrowOnError>({ url: '/v1/capabilities', ...options });

/**
 * Get the effective transfer policy.
 *
 * Expose the current transfer policy envelope that browser and native upload clients should honor.
 *
 * @param options - request options including client, security, and request overrides.
 * @returns Effective transfer policy metadata and limits.
 */
export const getTransferCapabilities = <ThrowOnError extends boolean = false>(options?: Options<GetTransferCapabilitiesData, ThrowOnError>) => (options?.client ?? client).get<GetTransferCapabilitiesResponses, GetTransferCapabilitiesErrors, ThrowOnError>({ url: '/v1/capabilities/transfers', ...options });

/**
 * List export workflows.
 *
 * List caller-owned export workflow resources with the most recent exports first.
 *
 * @param options - request options including client, security, and request overrides.
 * @returns Page of caller-owned export workflow resources.
 */
export const listExports = <ThrowOnError extends boolean = false>(options?: Options<ListExportsData, ThrowOnError>) => (options?.client ?? client).get<ListExportsResponses, ListExportsErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/v1/exports',
    ...options
});

/**
 * Create an export workflow.
 *
 * Create a caller-owned export resource that copies a source object into a download-oriented export output.
 *
 * @param options - request options including client, security, and request overrides.
 * @returns Created export workflow resource.
 */
export const createExport = <ThrowOnError extends boolean = false>(options: Options<CreateExportData, ThrowOnError>) => (options.client ?? client).post<CreateExportResponses, CreateExportErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/v1/exports',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get an export workflow.
 *
 * Return the current state of a caller-owned export workflow resource.
 *
 * @param options - request options including client, security, and request overrides.
 * @returns Current export workflow resource.
 */
export const getExport = <ThrowOnError extends boolean = false>(options: Options<GetExportData, ThrowOnError>) => (options.client ?? client).get<GetExportResponses, GetExportErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/v1/exports/{export_id}',
    ...options
});

/**
 * Cancel an export workflow.
 *
 * Persist cancel intent for a caller-owned export that has not yet reached a terminal state.
 *
 * @param options - request options including client, security, and request overrides.
 * @returns Updated export workflow resource after cancel intent.
 */
export const cancelExport = <ThrowOnError extends boolean = false>(options: Options<CancelExportData, ThrowOnError>) => (options.client ?? client).post<CancelExportResponses, CancelExportErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/v1/exports/{export_id}/cancel',
    ...options
});

/**
 * Check liveness.
 *
 * Return a shallow liveness signal for the API runtime process.
 *
 * @param options - request options including client, security, and request overrides.
 * @returns Liveness status for the API runtime.
 */
export const healthLive = <ThrowOnError extends boolean = false>(options?: Options<HealthLiveData, ThrowOnError>) => (options?.client ?? client).get<HealthLiveResponses, unknown, ThrowOnError>({ url: '/v1/health/live', ...options });

/**
 * Check readiness.
 *
 * Return readiness checks for traffic-critical dependencies such as auth, transfers, exports, and idempotency.
 *
 * @param options - request options including client, security, and request overrides.
 * @returns Readiness status plus per-dependency readiness checks.
 */
export const healthReady = <ThrowOnError extends boolean = false>(options?: Options<HealthReadyData, ThrowOnError>) => (options?.client ?? client).get<HealthReadyResponses, HealthReadyErrors, ThrowOnError>({ url: '/v1/health/ready', ...options });

/**
 * Get public release metadata.
 *
 * Return public release metadata used by browser clients, diagnostics, and deploy canaries.
 *
 * @param options - request options including client, security, and request overrides.
 * @returns Release name, version, and environment metadata.
 */
export const getReleaseInfo = <ThrowOnError extends boolean = false>(options?: Options<GetReleaseInfoData, ThrowOnError>) => (options?.client ?? client).get<GetReleaseInfoResponses, unknown, ThrowOnError>({ url: '/v1/releases/info', ...options });

/**
 * Plan resource support.
 *
 * Report whether each requested resource is currently supported in the active deployment.
 *
 * @param options - request options including client, security, and request overrides.
 * @returns Supportability decisions for each requested resource.
 */
export const planResources = <ThrowOnError extends boolean = false>(options: Options<PlanResourcesData, ThrowOnError>) => (options.client ?? client).post<PlanResourcesResponses, PlanResourcesErrors, ThrowOnError>({
    url: '/v1/resources/plan',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Presign a direct download.
 *
 * Return a time-limited download URL for an object the caller is authorized to access.
 *
 * @param options - request options including client, security, and request overrides.
 * @returns Presigned download URL and associated object metadata.
 */
export const presignDownload = <ThrowOnError extends boolean = false>(options: Options<PresignDownloadData, ThrowOnError>) => (options.client ?? client).post<PresignDownloadResponses, PresignDownloadErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/v1/transfers/downloads/presign',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Abort a multipart upload.
 *
 * Cancel an in-progress multipart upload and discard any staged parts.
 *
 * @param options - request options including client, security, and request overrides.
 * @returns Acknowledgement that the multipart upload was aborted.
 */
export const abortUpload = <ThrowOnError extends boolean = false>(options: Options<AbortUploadData, ThrowOnError>) => (options.client ?? client).post<AbortUploadResponses, AbortUploadErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/v1/transfers/uploads/abort',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Complete a multipart upload.
 *
 * Finalize a multipart upload after the caller has uploaded every required part.
 *
 * @param options - request options including client, security, and request overrides.
 * @returns Completed object metadata for the finalized upload.
 */
export const completeUpload = <ThrowOnError extends boolean = false>(options: Options<CompleteUploadData, ThrowOnError>) => (options.client ?? client).post<CompleteUploadResponses, CompleteUploadErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/v1/transfers/uploads/complete',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Initiate a direct-to-S3 upload session.
 *
 * Resolve the effective transfer policy for the caller and return the presigned metadata needed to upload directly to S3.
 *
 * @param options - request options including client, security, and request overrides.
 * @returns Resolved upload session metadata, policy hints, and presigned inputs.
 */
export const initiateUpload = <ThrowOnError extends boolean = false>(options: Options<InitiateUploadData, ThrowOnError>) => (options.client ?? client).post<InitiateUploadResponses, InitiateUploadErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/v1/transfers/uploads/initiate',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Inspect multipart upload state.
 *
 * Return the persisted multipart session state so browser or native clients can resume an interrupted upload.
 *
 * @param options - request options including client, security, and request overrides.
 * @returns Current multipart upload state, including uploaded parts.
 */
export const introspectUpload = <ThrowOnError extends boolean = false>(options: Options<IntrospectUploadData, ThrowOnError>) => (options.client ?? client).post<IntrospectUploadResponses, IntrospectUploadErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/v1/transfers/uploads/introspect',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Sign multipart upload parts.
 *
 * Return presigned URLs for the requested multipart upload part numbers.
 *
 * @param options - request options including client, security, and request overrides.
 * @returns Presigned multipart part URLs and their TTL.
 */
export const signUploadParts = <ThrowOnError extends boolean = false>(options: Options<SignUploadPartsData, ThrowOnError>) => (options.client ?? client).post<SignUploadPartsResponses, SignUploadPartsErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/v1/transfers/uploads/sign-parts',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});
