// This file is auto-generated by @hey-api/openapi-ts

import { client } from './client.gen.js';
import type { Client, Options as Options2, TDataShape } from './client/index.js';
import type { AbortUploadData, AbortUploadErrors, AbortUploadResponses, CancelExportData, CancelExportErrors, CancelExportResponses, CompleteUploadData, CompleteUploadErrors, CompleteUploadResponses, CreateExportData, CreateExportErrors, CreateExportResponses, GetCapabilitiesData, GetCapabilitiesResponses, GetExportData, GetExportErrors, GetExportResponses, GetReleaseInfoData, GetReleaseInfoResponses, GetTransferCapabilitiesData, GetTransferCapabilitiesResponses, HealthLiveData, HealthLiveResponses, HealthReadyData, HealthReadyErrors, HealthReadyResponses, InitiateUploadData, InitiateUploadErrors, InitiateUploadResponses, IntrospectUploadData, IntrospectUploadErrors, IntrospectUploadResponses, ListExportsData, ListExportsErrors, ListExportsResponses, MetricsSummaryData, MetricsSummaryErrors, MetricsSummaryResponses, PlanResourcesData, PlanResourcesErrors, PlanResourcesResponses, PresignDownloadData, PresignDownloadErrors, PresignDownloadResponses, SignUploadPartsData, SignUploadPartsErrors, SignUploadPartsResponses } from './types.gen.js';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Metrics Summary
 *
 * Return low-cardinality metrics summary for dashboards.
 */
export const metricsSummary = <ThrowOnError extends boolean = false>(options?: Options<MetricsSummaryData, ThrowOnError>) => (options?.client ?? client).get<MetricsSummaryResponses, MetricsSummaryErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/metrics/summary',
    ...options
});

/**
 * Get Capabilities
 *
 * Expose runtime capability declarations.
 */
export const getCapabilities = <ThrowOnError extends boolean = false>(options?: Options<GetCapabilitiesData, ThrowOnError>) => (options?.client ?? client).get<GetCapabilitiesResponses, unknown, ThrowOnError>({ url: '/v1/capabilities', ...options });

/**
 * Get Transfer Capabilities
 *
 * Expose the current transfer policy envelope.
 */
export const getTransferCapabilities = <ThrowOnError extends boolean = false>(options?: Options<GetTransferCapabilitiesData, ThrowOnError>) => (options?.client ?? client).get<GetTransferCapabilitiesResponses, unknown, ThrowOnError>({ url: '/v1/capabilities/transfers', ...options });

/**
 * List Exports
 *
 * List caller-owned exports with most recent first.
 */
export const listExports = <ThrowOnError extends boolean = false>(options?: Options<ListExportsData, ThrowOnError>) => (options?.client ?? client).get<ListExportsResponses, ListExportsErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/v1/exports',
    ...options
});

/**
 * Create Export
 *
 * Create an explicit export workflow resource.
 */
export const createExport = <ThrowOnError extends boolean = false>(options: Options<CreateExportData, ThrowOnError>) => (options.client ?? client).post<CreateExportResponses, CreateExportErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/v1/exports',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get Export
 *
 * Return the caller-owned export resource.
 */
export const getExport = <ThrowOnError extends boolean = false>(options: Options<GetExportData, ThrowOnError>) => (options.client ?? client).get<GetExportResponses, GetExportErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/v1/exports/{export_id}',
    ...options
});

/**
 * Cancel Export
 *
 * Cancel a caller-owned non-terminal export.
 */
export const cancelExport = <ThrowOnError extends boolean = false>(options: Options<CancelExportData, ThrowOnError>) => (options.client ?? client).post<CancelExportResponses, CancelExportErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/v1/exports/{export_id}/cancel',
    ...options
});

/**
 * Health Live
 *
 * Return liveness status.
 */
export const healthLive = <ThrowOnError extends boolean = false>(options?: Options<HealthLiveData, ThrowOnError>) => (options?.client ?? client).get<HealthLiveResponses, unknown, ThrowOnError>({ url: '/v1/health/live', ...options });

/**
 * Health Ready
 *
 * Return readiness checks for traffic-critical dependencies.
 */
export const healthReady = <ThrowOnError extends boolean = false>(options?: Options<HealthReadyData, ThrowOnError>) => (options?.client ?? client).get<HealthReadyResponses, HealthReadyErrors, ThrowOnError>({ url: '/v1/health/ready', ...options });

/**
 * Get Release Info
 *
 * Return public release metadata for browser and deploy canaries.
 */
export const getReleaseInfo = <ThrowOnError extends boolean = false>(options?: Options<GetReleaseInfoData, ThrowOnError>) => (options?.client ?? client).get<GetReleaseInfoResponses, unknown, ThrowOnError>({ url: '/v1/releases/info', ...options });

/**
 * Plan Resources
 *
 * Plan supportability for requested resource keys.
 */
export const planResources = <ThrowOnError extends boolean = false>(options: Options<PlanResourcesData, ThrowOnError>) => (options.client ?? client).post<PlanResourcesResponses, PlanResourcesErrors, ThrowOnError>({
    url: '/v1/resources/plan',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Presign Download
 *
 * Issue presigned GET URL for caller-scoped key.
 */
export const presignDownload = <ThrowOnError extends boolean = false>(options: Options<PresignDownloadData, ThrowOnError>) => (options.client ?? client).post<PresignDownloadResponses, PresignDownloadErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/v1/transfers/downloads/presign',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Abort Upload
 *
 * Abort multipart upload.
 */
export const abortUpload = <ThrowOnError extends boolean = false>(options: Options<AbortUploadData, ThrowOnError>) => (options.client ?? client).post<AbortUploadResponses, AbortUploadErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/v1/transfers/uploads/abort',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Complete Upload
 *
 * Complete multipart upload.
 */
export const completeUpload = <ThrowOnError extends boolean = false>(options: Options<CompleteUploadData, ThrowOnError>) => (options.client ?? client).post<CompleteUploadResponses, CompleteUploadErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/v1/transfers/uploads/complete',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Initiate Upload
 *
 * Choose upload strategy and return presigned metadata.
 */
export const initiateUpload = <ThrowOnError extends boolean = false>(options: Options<InitiateUploadData, ThrowOnError>) => (options.client ?? client).post<InitiateUploadResponses, InitiateUploadErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/v1/transfers/uploads/initiate',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Introspect Upload
 *
 * Return uploaded multipart part state for resume flows.
 *
 * Args:
 * payload: Multipart introspection input payload.
 * metrics: Request-scoped metrics collector dependency.
 * transfer_service: Transfer domain service dependency.
 * activity_store: Activity persistence dependency.
 * principal: Authenticated caller principal.
 *
 * Returns:
 * UploadIntrospectionResponse: Multipart state for resume operations.
 */
export const introspectUpload = <ThrowOnError extends boolean = false>(options: Options<IntrospectUploadData, ThrowOnError>) => (options.client ?? client).post<IntrospectUploadResponses, IntrospectUploadErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/v1/transfers/uploads/introspect',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Sign Upload Parts
 *
 * Return presigned multipart part URLs.
 */
export const signUploadParts = <ThrowOnError extends boolean = false>(options: Options<SignUploadPartsData, ThrowOnError>) => (options.client ?? client).post<SignUploadPartsResponses, SignUploadPartsErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/v1/transfers/uploads/sign-parts',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});
