// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

/**
 * AbortUploadRequest
 *
 * Multipart abort request.
 */
export type AbortUploadRequest = {
    /**
     * Key
     */
    key: string;
    /**
     * Upload Id
     */
    upload_id: string;
};

/**
 * AbortUploadResponse
 *
 * Multipart abort response.
 */
export type AbortUploadResponse = {
    /**
     * Ok
     */
    ok?: boolean;
};

/**
 * CapabilitiesResponse
 *
 * Capabilities endpoint response.
 */
export type CapabilitiesResponse = {
    /**
     * Capabilities
     */
    capabilities: Array<CapabilityDescriptor>;
};

/**
 * CapabilityDescriptor
 *
 * Machine-readable capability declaration.
 */
export type CapabilityDescriptor = {
    /**
     * Details
     *
     * Additional capability metadata.
     */
    details?: {
        [key: string]: unknown;
    };
    /**
     * Enabled
     */
    enabled: boolean;
    /**
     * Key
     */
    key: string;
};

/**
 * CompleteUploadRequest
 *
 * Multipart completion request.
 */
export type CompleteUploadRequest = {
    /**
     * Key
     */
    key: string;
    /**
     * Parts
     */
    parts: Array<CompletedPart>;
    /**
     * Upload Id
     */
    upload_id: string;
};

/**
 * CompleteUploadResponse
 *
 * Multipart completion response.
 */
export type CompleteUploadResponse = {
    /**
     * Bucket
     */
    bucket: string;
    /**
     * Etag
     */
    etag?: string | null;
    /**
     * Key
     */
    key: string;
    /**
     * Version Id
     */
    version_id?: string | null;
};

/**
 * CompletedPart
 *
 * Part metadata needed for multipart completion.
 */
export type CompletedPart = {
    /**
     * Checksum Sha256
     */
    checksum_sha256?: string | null;
    /**
     * Etag
     */
    etag: string;
    /**
     * Part Number
     */
    part_number: number;
};

/**
 * CreateExportRequest
 *
 * Request payload for export creation.
 */
export type CreateExportRequest = {
    /**
     * Filename
     *
     * Client-facing filename to preserve in the export.
     */
    filename: string;
    /**
     * Source Key
     *
     * Storage key of the source object to export.
     */
    source_key: string;
};

/**
 * ErrorBody
 *
 * Standard API error body.
 */
export type ErrorBody = {
    /**
     * Code
     */
    code: string;
    /**
     * Details
     */
    details: {
        [key: string]: unknown;
    };
    /**
     * Message
     */
    message: string;
    /**
     * Request Id
     */
    request_id: string | null;
};

/**
 * ErrorEnvelope
 *
 * Standard API error envelope.
 */
export type ErrorEnvelope = {
    error: ErrorBody;
};

/**
 * ExportListResponse
 *
 * Response payload for export listing endpoint.
 */
export type ExportListResponse = {
    /**
     * Exports
     */
    exports: Array<ExportResource>;
};

/**
 * ExportOutput
 *
 * Completed export output metadata.
 */
export type ExportOutput = {
    /**
     * Download Filename
     *
     * Filename presented to clients when downloading.
     */
    download_filename: string;
    /**
     * Key
     *
     * Storage key for the exported object.
     */
    key: string;
};

/**
 * ExportResource
 *
 * Public export workflow resource.
 */
export type ExportResource = {
    /**
     * Cancel Requested At
     */
    cancel_requested_at?: string | null;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Error
     */
    error?: string | null;
    /**
     * Execution Arn
     */
    execution_arn?: string | null;
    /**
     * Export Id
     */
    export_id: string;
    /**
     * Filename
     */
    filename: string;
    output?: ExportOutput | null;
    /**
     * Source Key
     */
    source_key: string;
    status: ExportStatus;
    /**
     * Updated At
     */
    updated_at: string;
};

/**
 * ExportStatus
 *
 * Lifecycle status of an export workflow.
 */
export type ExportStatus = 'queued' | 'validating' | 'copying' | 'finalizing' | 'succeeded' | 'failed' | 'cancelled';

/**
 * Validation error envelope returned for invalid request payloads.
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * HealthResponse
 *
 * Health endpoint response body.
 */
export type HealthResponse = {
    /**
     * Ok
     */
    ok: boolean;
};

/**
 * InitiateUploadRequest
 *
 * Initiate-upload request model.
 *
 * Client hints (``workload_class``, ``policy_hint``, ``checksum_preference``)
 * are inputs only. The effective persisted transfer policy exposes
 * ``checksum_mode`` as ``none|optional|required`` per SPEC-0002 (S3
 * integration). ``checksum_preference`` accepts ``none|standard|strict`` as a
 * client preference; preference is not the same enum as mode mapping and the
 * final mode decision happens server-side.
 */
export type InitiateUploadRequest = {
    /**
     * Checksum Preference
     */
    checksum_preference?: string | null;
    /**
     * Checksum Value
     */
    checksum_value?: string | null;
    /**
     * Content Type
     */
    content_type?: string | null;
    /**
     * Filename
     */
    filename: string;
    /**
     * Policy Hint
     */
    policy_hint?: string | null;
    /**
     * Size Bytes
     */
    size_bytes: number;
    /**
     * Workload Class
     */
    workload_class?: string | null;
};

/**
 * InitiateUploadResponse
 *
 * Initiate-upload response model.
 */
export type InitiateUploadResponse = {
    /**
     * Accelerate Enabled
     */
    accelerate_enabled: boolean;
    /**
     * Bucket
     */
    bucket: string;
    /**
     * Checksum Algorithm
     */
    checksum_algorithm?: string | null;
    /**
     * Checksum Mode
     */
    checksum_mode: 'none' | 'optional' | 'required';
    /**
     * Expires In Seconds
     */
    expires_in_seconds: number;
    /**
     * Key
     */
    key: string;
    /**
     * Max Concurrency Hint
     */
    max_concurrency_hint: number;
    /**
     * Part Size Bytes
     */
    part_size_bytes?: number | null;
    /**
     * Policy Id
     */
    policy_id: string;
    /**
     * Policy Version
     */
    policy_version: string;
    /**
     * Resumable Until
     */
    resumable_until: string;
    /**
     * Session Id
     */
    session_id: string;
    /**
     * Sign Batch Size Hint
     */
    sign_batch_size_hint: number;
    strategy: UploadStrategy;
    /**
     * Upload Id
     */
    upload_id?: string | null;
    /**
     * Url
     */
    url?: string | null;
};

/**
 * MetricsSummaryResponse
 *
 * Metrics summary endpoint response body.
 */
export type MetricsSummaryResponse = {
    /**
     * Activity
     */
    activity: {
        [key: string]: number;
    };
    /**
     * Counters
     */
    counters: {
        [key: string]: number;
    };
    /**
     * Latencies Ms
     */
    latencies_ms: {
        [key: string]: number;
    };
};

/**
 * PresignDownloadRequest
 *
 * Presign download request.
 */
export type PresignDownloadRequest = {
    /**
     * Content Disposition
     */
    content_disposition?: string | null;
    /**
     * Content Type
     */
    content_type?: string | null;
    /**
     * Filename
     */
    filename?: string | null;
    /**
     * Key
     */
    key: string;
};

/**
 * PresignDownloadResponse
 *
 * Presign download response.
 */
export type PresignDownloadResponse = {
    /**
     * Bucket
     */
    bucket: string;
    /**
     * Expires In Seconds
     */
    expires_in_seconds: number;
    /**
     * Key
     */
    key: string;
    /**
     * Url
     */
    url: string;
};

/**
 * ReadinessResponse
 *
 * Readiness endpoint response body.
 */
export type ReadinessResponse = {
    /**
     * Checks
     */
    checks: {
        [key: string]: boolean;
    };
    /**
     * Ok
     */
    ok: boolean;
};

/**
 * ReleaseInfoResponse
 *
 * Release metadata for conformance/debug clients.
 */
export type ReleaseInfoResponse = {
    /**
     * Environment
     */
    environment: string;
    /**
     * Name
     */
    name: string;
    /**
     * Version
     */
    version: string;
};

/**
 * ResourcePlanItem
 *
 * Resource planning decision per requested resource.
 */
export type ResourcePlanItem = {
    /**
     * Reason
     */
    reason?: string | null;
    /**
     * Resource
     */
    resource: string;
    /**
     * Supported
     */
    supported: boolean;
};

/**
 * ResourcePlanRequest
 *
 * Resource planning request body.
 */
export type ResourcePlanRequest = {
    /**
     * Resources
     */
    resources: Array<string>;
};

/**
 * ResourcePlanResponse
 *
 * Resource planning response body.
 */
export type ResourcePlanResponse = {
    /**
     * Plan
     */
    plan: Array<ResourcePlanItem>;
};

/**
 * SignPartsRequest
 *
 * Multipart sign-parts request.
 */
export type SignPartsRequest = {
    /**
     * Checksums Sha256
     */
    checksums_sha256?: {
        [key: string]: string;
    } | null;
    /**
     * Key
     */
    key: string;
    /**
     * Part Numbers
     */
    part_numbers: Array<number>;
    /**
     * Upload Id
     */
    upload_id: string;
};

/**
 * SignPartsResponse
 *
 * Multipart sign-parts response.
 */
export type SignPartsResponse = {
    /**
     * Expires In Seconds
     */
    expires_in_seconds: number;
    /**
     * Urls
     */
    urls: {
        [key: string]: string;
    };
};

/**
 * TransferCapabilitiesResponse
 *
 * Transfer policy capabilities exposed to clients and operators.
 */
export type TransferCapabilitiesResponse = {
    /**
     * Accelerate Enabled
     */
    accelerate_enabled: boolean;
    /**
     * Active Multipart Upload Limit
     */
    active_multipart_upload_limit: number;
    /**
     * Checksum Algorithm
     */
    checksum_algorithm?: string | null;
    /**
     * Checksum Mode
     */
    checksum_mode: 'none' | 'optional' | 'required';
    /**
     * Daily Ingress Budget Bytes
     */
    daily_ingress_budget_bytes: number;
    /**
     * Large Export Worker Threshold Bytes
     */
    large_export_worker_threshold_bytes: number;
    /**
     * Max Concurrency Hint
     */
    max_concurrency_hint: number;
    /**
     * Max Upload Bytes
     */
    max_upload_bytes: number;
    /**
     * Maximum Part Size Bytes
     */
    maximum_part_size_bytes: number;
    /**
     * Minimum Part Size Bytes
     */
    minimum_part_size_bytes: number;
    /**
     * Multipart Threshold Bytes
     */
    multipart_threshold_bytes: number;
    /**
     * Policy Id
     */
    policy_id: string;
    /**
     * Policy Version
     */
    policy_version: string;
    /**
     * Resumable Ttl Seconds
     */
    resumable_ttl_seconds: number;
    /**
     * Sign Batch Size Hint
     */
    sign_batch_size_hint: number;
    /**
     * Sign Requests Per Upload Limit
     */
    sign_requests_per_upload_limit: number;
    /**
     * Target Upload Part Count
     */
    target_upload_part_count: number;
};

/**
 * UploadIntrospectionRequest
 *
 * Multipart upload introspection request.
 */
export type UploadIntrospectionRequest = {
    /**
     * Key
     */
    key: string;
    /**
     * Upload Id
     */
    upload_id: string;
};

/**
 * UploadIntrospectionResponse
 *
 * Multipart upload introspection response.
 */
export type UploadIntrospectionResponse = {
    /**
     * Bucket
     */
    bucket: string;
    /**
     * Key
     */
    key: string;
    /**
     * Part Size Bytes
     */
    part_size_bytes: number;
    /**
     * Parts
     */
    parts: Array<UploadedPart>;
    /**
     * Upload Id
     */
    upload_id: string;
};

/**
 * UploadStrategy
 *
 * Upload strategy options returned by initiate endpoint.
 */
export type UploadStrategy = 'single' | 'multipart';

/**
 * UploadedPart
 *
 * Part state returned for multipart upload introspection.
 */
export type UploadedPart = {
    /**
     * Etag
     */
    etag: string;
    /**
     * Part Number
     */
    part_number: number;
};

/**
 * One request-validation issue with location, message, and error type.
 */
export type ValidationError = {
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
    /**
     * Input
     */
    input?: unknown;
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

/**
 * Request data for the `MetricsSummary` operation.
 */
export type MetricsSummaryData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/metrics/summary';
};

/**
 * Error responses for the `MetricsSummary` operation.
 */
export type MetricsSummaryErrors = {
    /**
     * Unauthorized - Bearer token is missing or invalid.
     */
    401: ErrorEnvelope;
    /**
     * Forbidden - Caller lacks required scope or permission.
     */
    403: ErrorEnvelope;
};

/**
 * Error union for the `MetricsSummary` operation.
 */
export type MetricsSummaryError = MetricsSummaryErrors[keyof MetricsSummaryErrors];

/**
 * Response variants for the `MetricsSummary` operation.
 */
export type MetricsSummaryResponses = {
    /**
     * Successful Response
     */
    200: MetricsSummaryResponse;
};

export type MetricsSummaryResponse2 = MetricsSummaryResponses[keyof MetricsSummaryResponses];

/**
 * Request data for the `GetCapabilities` operation.
 */
export type GetCapabilitiesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/capabilities';
};

/**
 * Response variants for the `GetCapabilities` operation.
 */
export type GetCapabilitiesResponses = {
    /**
     * Successful Response
     */
    200: CapabilitiesResponse;
};

/**
 * Response union for the `GetCapabilities` operation.
 */
export type GetCapabilitiesResponse = GetCapabilitiesResponses[keyof GetCapabilitiesResponses];

/**
 * Request data for the `GetTransferCapabilities` operation.
 */
export type GetTransferCapabilitiesData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Workload Class
         */
        workload_class?: string | null;
        /**
         * Policy Hint
         */
        policy_hint?: string | null;
    };
    url: '/v1/capabilities/transfers';
};

/**
 * Error responses for the `GetTransferCapabilities` operation.
 */
export type GetTransferCapabilitiesErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

/**
 * Error union for the `GetTransferCapabilities` operation.
 */
export type GetTransferCapabilitiesError = GetTransferCapabilitiesErrors[keyof GetTransferCapabilitiesErrors];

/**
 * Response variants for the `GetTransferCapabilities` operation.
 */
export type GetTransferCapabilitiesResponses = {
    /**
     * Successful Response
     */
    200: TransferCapabilitiesResponse;
};

/**
 * Response union for the `GetTransferCapabilities` operation.
 */
export type GetTransferCapabilitiesResponse = GetTransferCapabilitiesResponses[keyof GetTransferCapabilitiesResponses];

/**
 * Request data for the `ListExports` operation.
 */
export type ListExportsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/v1/exports';
};

/**
 * Error responses for the `ListExports` operation.
 */
export type ListExportsErrors = {
    /**
     * Unauthorized - Bearer token is missing or invalid.
     */
    401: ErrorEnvelope;
    /**
     * Forbidden - Caller lacks required scope or permission.
     */
    403: ErrorEnvelope;
    /**
     * Unprocessable Content - Request validation failed.
     */
    422: ErrorEnvelope;
};

/**
 * Error union for the `ListExports` operation.
 */
export type ListExportsError = ListExportsErrors[keyof ListExportsErrors];

/**
 * Response variants for the `ListExports` operation.
 */
export type ListExportsResponses = {
    /**
     * Successful Response
     */
    200: ExportListResponse;
};

/**
 * Response union for the `ListExports` operation.
 */
export type ListExportsResponse = ListExportsResponses[keyof ListExportsResponses];

/**
 * Request data for the `CreateExport` operation.
 */
export type CreateExportData = {
    body: CreateExportRequest;
    headers?: {
        /**
         * Idempotency-Key
         */
        'Idempotency-Key'?: string | null;
    };
    path?: never;
    query?: never;
    url: '/v1/exports';
};

/**
 * Error responses for the `CreateExport` operation.
 */
export type CreateExportErrors = {
    /**
     * Unauthorized - Bearer token is missing or invalid.
     */
    401: ErrorEnvelope;
    /**
     * Forbidden - Caller lacks required scope or permission.
     */
    403: ErrorEnvelope;
    /**
     * Conflict - Idempotency request is already in progress.
     */
    409: ErrorEnvelope;
    /**
     * Unprocessable Content - Request validation failed.
     */
    422: ErrorEnvelope;
    /**
     * Service Unavailable - Queue publishing or idempotency storage is unavailable.
     */
    503: ErrorEnvelope;
};

/**
 * Error union for the `CreateExport` operation.
 */
export type CreateExportError = CreateExportErrors[keyof CreateExportErrors];

/**
 * Response variants for the `CreateExport` operation.
 */
export type CreateExportResponses = {
    /**
     * Successful Response
     */
    201: ExportResource;
};

/**
 * Response union for the `CreateExport` operation.
 */
export type CreateExportResponse = CreateExportResponses[keyof CreateExportResponses];

/**
 * Request data for the `GetExport` operation.
 */
export type GetExportData = {
    body?: never;
    path: {
        /**
         * Export Id
         */
        export_id: string;
    };
    query?: never;
    url: '/v1/exports/{export_id}';
};

/**
 * Error responses for the `GetExport` operation.
 */
export type GetExportErrors = {
    /**
     * Unauthorized - Bearer token is missing or invalid.
     */
    401: ErrorEnvelope;
    /**
     * Forbidden - Caller lacks required scope or permission.
     */
    403: ErrorEnvelope;
    /**
     * Not Found - Export resource was not found.
     */
    404: ErrorEnvelope;
    /**
     * Unprocessable Content - Request validation failed.
     */
    422: ErrorEnvelope;
};

/**
 * Error union for the `GetExport` operation.
 */
export type GetExportError = GetExportErrors[keyof GetExportErrors];

/**
 * Response variants for the `GetExport` operation.
 */
export type GetExportResponses = {
    /**
     * Successful Response
     */
    200: ExportResource;
};

/**
 * Response union for the `GetExport` operation.
 */
export type GetExportResponse = GetExportResponses[keyof GetExportResponses];

/**
 * Request data for the `CancelExport` operation.
 */
export type CancelExportData = {
    body?: never;
    path: {
        /**
         * Export Id
         */
        export_id: string;
    };
    query?: never;
    url: '/v1/exports/{export_id}/cancel';
};

/**
 * Error responses for the `CancelExport` operation.
 */
export type CancelExportErrors = {
    /**
     * Unauthorized - Bearer token is missing or invalid.
     */
    401: ErrorEnvelope;
    /**
     * Forbidden - Caller lacks required scope or permission.
     */
    403: ErrorEnvelope;
    /**
     * Not Found - Export resource was not found.
     */
    404: ErrorEnvelope;
    /**
     * Unprocessable Content - Request validation failed.
     */
    422: ErrorEnvelope;
};

/**
 * Error union for the `CancelExport` operation.
 */
export type CancelExportError = CancelExportErrors[keyof CancelExportErrors];

/**
 * Response variants for the `CancelExport` operation.
 */
export type CancelExportResponses = {
    /**
     * Successful Response
     */
    200: ExportResource;
};

/**
 * Response union for the `CancelExport` operation.
 */
export type CancelExportResponse = CancelExportResponses[keyof CancelExportResponses];

/**
 * Request data for the `HealthLive` operation.
 */
export type HealthLiveData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/health/live';
};

/**
 * Response variants for the `HealthLive` operation.
 */
export type HealthLiveResponses = {
    /**
     * Successful Response
     */
    200: HealthResponse;
};

/**
 * Response union for the `HealthLive` operation.
 */
export type HealthLiveResponse = HealthLiveResponses[keyof HealthLiveResponses];

/**
 * Request data for the `HealthReady` operation.
 */
export type HealthReadyData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/health/ready';
};

/**
 * Error responses for the `HealthReady` operation.
 */
export type HealthReadyErrors = {
    /**
     * Service Unavailable - Readiness failed.
     */
    503: ReadinessResponse;
};

/**
 * Error union for the `HealthReady` operation.
 */
export type HealthReadyError = HealthReadyErrors[keyof HealthReadyErrors];

/**
 * Response variants for the `HealthReady` operation.
 */
export type HealthReadyResponses = {
    /**
     * Successful Response
     */
    200: ReadinessResponse;
};

/**
 * Response union for the `HealthReady` operation.
 */
export type HealthReadyResponse = HealthReadyResponses[keyof HealthReadyResponses];

/**
 * Request data for the `GetReleaseInfo` operation.
 */
export type GetReleaseInfoData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/releases/info';
};

/**
 * Response variants for the `GetReleaseInfo` operation.
 */
export type GetReleaseInfoResponses = {
    /**
     * Successful Response
     */
    200: ReleaseInfoResponse;
};

/**
 * Response union for the `GetReleaseInfo` operation.
 */
export type GetReleaseInfoResponse = GetReleaseInfoResponses[keyof GetReleaseInfoResponses];

/**
 * Request data for the `PlanResources` operation.
 */
export type PlanResourcesData = {
    body: ResourcePlanRequest;
    path?: never;
    query?: never;
    url: '/v1/resources/plan';
};

/**
 * Error responses for the `PlanResources` operation.
 */
export type PlanResourcesErrors = {
    /**
     * Unprocessable Content - Request validation failed.
     */
    422: ErrorEnvelope;
};

/**
 * Error union for the `PlanResources` operation.
 */
export type PlanResourcesError = PlanResourcesErrors[keyof PlanResourcesErrors];

/**
 * Response variants for the `PlanResources` operation.
 */
export type PlanResourcesResponses = {
    /**
     * Successful Response
     */
    200: ResourcePlanResponse;
};

/**
 * Response union for the `PlanResources` operation.
 */
export type PlanResourcesResponse = PlanResourcesResponses[keyof PlanResourcesResponses];

/**
 * Request data for the `PresignDownload` operation.
 */
export type PresignDownloadData = {
    body: PresignDownloadRequest;
    path?: never;
    query?: never;
    url: '/v1/transfers/downloads/presign';
};

/**
 * Error responses for the `PresignDownload` operation.
 */
export type PresignDownloadErrors = {
    /**
     * Unauthorized - Bearer token is missing or invalid.
     */
    401: ErrorEnvelope;
    /**
     * Forbidden - Caller lacks required scope or permission.
     */
    403: ErrorEnvelope;
    /**
     * Unprocessable Content - Request validation failed.
     */
    422: ErrorEnvelope;
};

/**
 * Error union for the `PresignDownload` operation.
 */
export type PresignDownloadError = PresignDownloadErrors[keyof PresignDownloadErrors];

/**
 * Response variants for the `PresignDownload` operation.
 */
export type PresignDownloadResponses = {
    /**
     * Successful Response
     */
    200: PresignDownloadResponse;
};

export type PresignDownloadResponse2 = PresignDownloadResponses[keyof PresignDownloadResponses];

/**
 * Request data for the `AbortUpload` operation.
 */
export type AbortUploadData = {
    body: AbortUploadRequest;
    path?: never;
    query?: never;
    url: '/v1/transfers/uploads/abort';
};

/**
 * Error responses for the `AbortUpload` operation.
 */
export type AbortUploadErrors = {
    /**
     * Unauthorized - Bearer token is missing or invalid.
     */
    401: ErrorEnvelope;
    /**
     * Forbidden - Caller lacks required scope or permission.
     */
    403: ErrorEnvelope;
    /**
     * Unprocessable Content - Request validation failed.
     */
    422: ErrorEnvelope;
};

/**
 * Error union for the `AbortUpload` operation.
 */
export type AbortUploadError = AbortUploadErrors[keyof AbortUploadErrors];

/**
 * Response variants for the `AbortUpload` operation.
 */
export type AbortUploadResponses = {
    /**
     * Successful Response
     */
    200: AbortUploadResponse;
};

export type AbortUploadResponse2 = AbortUploadResponses[keyof AbortUploadResponses];

/**
 * Request data for the `CompleteUpload` operation.
 */
export type CompleteUploadData = {
    body: CompleteUploadRequest;
    path?: never;
    query?: never;
    url: '/v1/transfers/uploads/complete';
};

/**
 * Error responses for the `CompleteUpload` operation.
 */
export type CompleteUploadErrors = {
    /**
     * Unauthorized - Bearer token is missing or invalid.
     */
    401: ErrorEnvelope;
    /**
     * Forbidden - Caller lacks required scope or permission.
     */
    403: ErrorEnvelope;
    /**
     * Unprocessable Content - Request validation failed.
     */
    422: ErrorEnvelope;
};

/**
 * Error union for the `CompleteUpload` operation.
 */
export type CompleteUploadError = CompleteUploadErrors[keyof CompleteUploadErrors];

/**
 * Response variants for the `CompleteUpload` operation.
 */
export type CompleteUploadResponses = {
    /**
     * Successful Response
     */
    200: CompleteUploadResponse;
};

export type CompleteUploadResponse2 = CompleteUploadResponses[keyof CompleteUploadResponses];

/**
 * Request data for the `InitiateUpload` operation.
 */
export type InitiateUploadData = {
    body: InitiateUploadRequest;
    headers?: {
        /**
         * Idempotency-Key
         */
        'Idempotency-Key'?: string | null;
    };
    path?: never;
    query?: never;
    url: '/v1/transfers/uploads/initiate';
};

/**
 * Error responses for the `InitiateUpload` operation.
 */
export type InitiateUploadErrors = {
    /**
     * Unauthorized - Bearer token is missing or invalid.
     */
    401: ErrorEnvelope;
    /**
     * Forbidden - Caller lacks required scope or permission.
     */
    403: ErrorEnvelope;
    /**
     * Conflict - Idempotency request is already in progress.
     */
    409: ErrorEnvelope;
    /**
     * Unprocessable Content - Request validation failed.
     */
    422: ErrorEnvelope;
    /**
     * Service Unavailable - Idempotency storage is unavailable.
     */
    503: ErrorEnvelope;
};

/**
 * Error union for the `InitiateUpload` operation.
 */
export type InitiateUploadError = InitiateUploadErrors[keyof InitiateUploadErrors];

/**
 * Response variants for the `InitiateUpload` operation.
 */
export type InitiateUploadResponses = {
    /**
     * Successful Response
     */
    200: InitiateUploadResponse;
};

export type InitiateUploadResponse2 = InitiateUploadResponses[keyof InitiateUploadResponses];

/**
 * Request data for the `IntrospectUpload` operation.
 */
export type IntrospectUploadData = {
    body: UploadIntrospectionRequest;
    path?: never;
    query?: never;
    url: '/v1/transfers/uploads/introspect';
};

/**
 * Error responses for the `IntrospectUpload` operation.
 */
export type IntrospectUploadErrors = {
    /**
     * Unauthorized - Bearer token is missing or invalid.
     */
    401: ErrorEnvelope;
    /**
     * Forbidden - Caller lacks required scope or permission.
     */
    403: ErrorEnvelope;
    /**
     * Unprocessable Content - Request validation failed.
     */
    422: ErrorEnvelope;
};

/**
 * Error union for the `IntrospectUpload` operation.
 */
export type IntrospectUploadError = IntrospectUploadErrors[keyof IntrospectUploadErrors];

/**
 * Response variants for the `IntrospectUpload` operation.
 */
export type IntrospectUploadResponses = {
    /**
     * Successful Response
     */
    200: UploadIntrospectionResponse;
};

/**
 * Response union for the `IntrospectUpload` operation.
 */
export type IntrospectUploadResponse = IntrospectUploadResponses[keyof IntrospectUploadResponses];

/**
 * Request data for the `SignUploadParts` operation.
 */
export type SignUploadPartsData = {
    body: SignPartsRequest;
    path?: never;
    query?: never;
    url: '/v1/transfers/uploads/sign-parts';
};

/**
 * Error responses for the `SignUploadParts` operation.
 */
export type SignUploadPartsErrors = {
    /**
     * Unauthorized - Bearer token is missing or invalid.
     */
    401: ErrorEnvelope;
    /**
     * Forbidden - Caller lacks required scope or permission.
     */
    403: ErrorEnvelope;
    /**
     * Unprocessable Content - Request validation failed.
     */
    422: ErrorEnvelope;
};

/**
 * Error union for the `SignUploadParts` operation.
 */
export type SignUploadPartsError = SignUploadPartsErrors[keyof SignUploadPartsErrors];

/**
 * Response variants for the `SignUploadParts` operation.
 */
export type SignUploadPartsResponses = {
    /**
     * Successful Response
     */
    200: SignPartsResponse;
};

/**
 * Response union for the `SignUploadParts` operation.
 */
export type SignUploadPartsResponse = SignUploadPartsResponses[keyof SignUploadPartsResponses];
