// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

/**
 * AbortUploadRequest
 *
 * Multipart abort request.
 */
export type AbortUploadRequest = {
    /**
     * Storage key reserved for the multipart upload.
     */
    key: string;
    /**
     * S3 multipart upload identifier being aborted.
     */
    upload_id: string;
};

/**
 * AbortUploadResponse
 *
 * Multipart abort response.
 */
export type AbortUploadResponse = {
    /**
     * Whether the multipart abort request was accepted.
     */
    ok?: boolean;
};

/**
 * CapabilitiesResponse
 *
 * Capabilities endpoint response.
 */
export type CapabilitiesResponse = {
    /**
     * Capability declarations exposed by the running API.
     */
    capabilities: Array<CapabilityDescriptor>;
};

/**
 * CapabilityDescriptor
 *
 * Machine-readable capability declaration.
 */
export type CapabilityDescriptor = {
    /**
     * Additional capability metadata.
     */
    details?: {
        [key: string]: unknown;
    };
    /**
     * Whether the capability is enabled in the current deployment.
     */
    enabled: boolean;
    /**
     * Stable capability identifier.
     */
    key: string;
};

/**
 * CompleteUploadRequest
 *
 * Multipart completion request.
 */
export type CompleteUploadRequest = {
    /**
     * Storage key reserved for the multipart upload.
     */
    key: string;
    /**
     * Ordered multipart parts to finalize in S3.
     */
    parts: Array<CompletedPart>;
    /**
     * S3 multipart upload identifier being finalized.
     */
    upload_id: string;
};

/**
 * CompleteUploadResponse
 *
 * Multipart completion response.
 */
export type CompleteUploadResponse = {
    /**
     * Bucket that now contains the completed object.
     */
    bucket: string;
    /**
     * Object ETag returned by S3 when available.
     */
    etag?: string | null;
    /**
     * Storage key of the completed object.
     */
    key: string;
    /**
     * S3 object version identifier when bucket versioning is enabled.
     */
    version_id?: string | null;
};

/**
 * CompletedPart
 *
 * Part metadata needed for multipart completion.
 */
export type CompletedPart = {
    /**
     * Optional SHA-256 checksum for the completed multipart part.
     */
    checksum_sha256?: string | null;
    /**
     * ETag returned by S3 for the completed multipart part.
     */
    etag: string;
    /**
     * Multipart part number included in the completion request.
     */
    part_number: number;
};

/**
 * CreateExportRequest
 *
 * Request payload for export creation.
 */
export type CreateExportRequest = {
    /**
     * Client-facing filename to preserve in the export.
     */
    filename: string;
    /**
     * Storage key of the source object to export.
     */
    source_key: string;
};

/**
 * ErrorBody
 *
 * Standard API error body.
 */
export type ErrorBody = {
    /**
     * Stable machine-readable error code.
     */
    code: string;
    /**
     * Additional structured details for the error.
     */
    details: {
        [key: string]: unknown;
    };
    /**
     * Human-readable error summary.
     */
    message: string;
    /**
     * Request identifier associated with the failure when available.
     */
    request_id: string | null;
};

/**
 * ErrorEnvelope
 *
 * Standard API error envelope.
 */
export type ErrorEnvelope = {
    /**
     * Standard API error payload.
     */
    error: ErrorBody;
};

/**
 * ExportListResponse
 *
 * Response payload for export listing endpoint.
 */
export type ExportListResponse = {
    /**
     * Caller-owned export workflow resources ordered by recency.
     */
    exports: Array<ExportResource>;
};

/**
 * ExportOutput
 *
 * Completed export output metadata.
 */
export type ExportOutput = {
    /**
     * Filename presented to clients when downloading.
     */
    download_filename: string;
    /**
     * Storage key for the exported object.
     */
    key: string;
};

/**
 * ExportResource
 *
 * Public export workflow resource.
 */
export type ExportResource = {
    /**
     * Timestamp when cancel intent was persisted for the export.
     */
    cancel_requested_at?: string | null;
    /**
     * Timestamp when the export workflow resource was created.
     */
    created_at: string;
    /**
     * Terminal error message when the export fails.
     */
    error?: string | null;
    /**
     * Step Functions execution ARN for the active export workflow.
     */
    execution_arn?: string | null;
    /**
     * Identifier of the caller-owned export workflow resource.
     */
    export_id: string;
    /**
     * Filename presented to callers when downloading the export.
     */
    filename: string;
    /**
     * Completed output metadata when the export succeeds.
     */
    output?: ExportOutput | null;
    /**
     * Storage key of the object managed by the export workflow.
     */
    source_key: string;
    /**
     * Current lifecycle state of the export workflow.
     */
    status: ExportStatus;
    /**
     * Timestamp when the export workflow resource last changed.
     */
    updated_at: string;
};

/**
 * ExportStatus
 *
 * Lifecycle status of an export workflow.
 */
export type ExportStatus = 'queued' | 'validating' | 'copying' | 'finalizing' | 'succeeded' | 'failed' | 'cancelled';

/**
 * Validation error envelope returned for invalid request payloads.
 */
export type HttpValidationError = {
    /**
     * Detail
     *
     * Collection of request-validation issues returned by FastAPI.
     */
    detail?: Array<ValidationError>;
};

/**
 * HealthResponse
 *
 * Health endpoint response body.
 */
export type HealthResponse = {
    /**
     * Whether the runtime process is alive.
     */
    ok: boolean;
};

/**
 * InitiateUploadRequest
 *
 * Initiate-upload request model.
 *
 * Client hints (``workload_class``, ``policy_hint``, ``checksum_preference``)
 * are inputs only. The effective persisted transfer policy exposes
 * ``checksum_mode`` as ``none|optional|required`` per SPEC-0002 (S3
 * integration). ``checksum_preference`` accepts ``none|standard|strict`` as a
 * client preference; preference is not the same enum as mode mapping and the
 * final mode decision happens server-side.
 */
export type InitiateUploadRequest = {
    /**
     * Preferred checksum strictness requested by the client.
     */
    checksum_preference?: string | null;
    /**
     * Optional checksum value supplied with the initiate request.
     */
    checksum_value?: string | null;
    /**
     * Optional MIME type that should be persisted with the object.
     */
    content_type?: string | null;
    /**
     * Client-facing filename for the object being uploaded.
     */
    filename: string;
    /**
     * Optional transfer-policy hint evaluated by the API.
     */
    policy_hint?: string | null;
    /**
     * Total size of the object being uploaded, in bytes.
     */
    size_bytes: number;
    /**
     * Optional workload-class hint for transfer policy selection.
     */
    workload_class?: string | null;
};

/**
 * InitiateUploadResponse
 *
 * Initiate-upload response model.
 */
export type InitiateUploadResponse = {
    /**
     * Whether S3 Transfer Acceleration is enabled for the session.
     */
    accelerate_enabled: boolean;
    /**
     * Bucket that will receive the uploaded object.
     */
    bucket: string;
    /**
     * Checksum algorithm callers should use when checksums apply.
     */
    checksum_algorithm?: string | null;
    /**
     * Server-resolved checksum enforcement mode for the upload.
     */
    checksum_mode: 'none' | 'optional' | 'required';
    /**
     * Seconds until the returned presigned inputs expire.
     */
    expires_in_seconds: number;
    /**
     * Storage key reserved for the uploaded object.
     */
    key: string;
    /**
     * Suggested maximum number of concurrent client uploads.
     */
    max_concurrency_hint: number;
    /**
     * Target multipart part size in bytes when multipart is required.
     */
    part_size_bytes?: number | null;
    /**
     * Identifier of the effective transfer policy.
     */
    policy_id: string;
    /**
     * Version of the effective transfer policy.
     */
    policy_version: string;
    /**
     * Timestamp until which multipart resume operations are valid.
     */
    resumable_until: string;
    /**
     * Durable upload-session identifier used for resume flows.
     */
    session_id: string;
    /**
     * Suggested maximum number of parts per sign-parts request.
     */
    sign_batch_size_hint: number;
    /**
     * Upload strategy selected by the API for this transfer.
     */
    strategy: UploadStrategy;
    /**
     * S3 multipart upload identifier when multipart is required.
     */
    upload_id?: string | null;
    /**
     * Presigned single-part upload URL when the strategy is direct.
     */
    url?: string | null;
};

/**
 * MetricsSummaryResponse
 *
 * Metrics summary endpoint response body.
 */
export type MetricsSummaryResponse = {
    /**
     * Activity rollups derived from the activity store.
     */
    activity: {
        [key: string]: number;
    };
    /**
     * Low-cardinality request and workflow counters.
     */
    counters: {
        [key: string]: number;
    };
    /**
     * Aggregated request-latency summaries in milliseconds.
     */
    latencies_ms: {
        [key: string]: number;
    };
};

/**
 * PresignDownloadRequest
 *
 * Presign download request.
 */
export type PresignDownloadRequest = {
    /**
     * Optional Content-Disposition override for the download response.
     */
    content_disposition?: string | null;
    /**
     * Optional Content-Type override for the download response.
     */
    content_type?: string | null;
    /**
     * Optional filename hint applied to Content-Disposition.
     */
    filename?: string | null;
    /**
     * Storage key of the object to download.
     */
    key: string;
};

/**
 * PresignDownloadResponse
 *
 * Presign download response.
 */
export type PresignDownloadResponse = {
    /**
     * Bucket that owns the downloadable object.
     */
    bucket: string;
    /**
     * Seconds until the presigned download URL expires.
     */
    expires_in_seconds: number;
    /**
     * Storage key of the downloadable object.
     */
    key: string;
    /**
     * Presigned download URL for the requested object.
     */
    url: string;
};

/**
 * ReadinessResponse
 *
 * Readiness endpoint response body.
 */
export type ReadinessResponse = {
    /**
     * Per-dependency readiness results keyed by check name.
     */
    checks: {
        [key: string]: boolean;
    };
    /**
     * Whether every required traffic dependency is ready.
     */
    ok: boolean;
};

/**
 * ReleaseInfoResponse
 *
 * Release metadata for conformance/debug clients.
 */
export type ReleaseInfoResponse = {
    /**
     * Deployment environment name.
     */
    environment: string;
    /**
     * Public application name for the deployment.
     */
    name: string;
    /**
     * Published application version string.
     */
    version: string;
};

/**
 * ResourcePlanItem
 *
 * Resource planning decision per requested resource.
 */
export type ResourcePlanItem = {
    /**
     * Machine-readable reason when the resource is not supported.
     */
    reason?: string | null;
    /**
     * Requested resource key.
     */
    resource: string;
    /**
     * Whether the resource is supported in the current deployment.
     */
    supported: boolean;
};

/**
 * ResourcePlanRequest
 *
 * Resource planning request body.
 */
export type ResourcePlanRequest = {
    /**
     * Resource keys whose supportability should be evaluated.
     */
    resources: Array<string>;
};

/**
 * ResourcePlanResponse
 *
 * Resource planning response body.
 */
export type ResourcePlanResponse = {
    /**
     * Supportability decision for each requested resource key.
     */
    plan: Array<ResourcePlanItem>;
};

/**
 * SignPartsRequest
 *
 * Multipart sign-parts request.
 */
export type SignPartsRequest = {
    /**
     * Optional SHA-256 checksum map keyed by multipart part number.
     */
    checksums_sha256?: {
        [key: string]: string;
    } | null;
    /**
     * Storage key reserved for the multipart upload.
     */
    key: string;
    /**
     * Multipart part numbers to sign in this request.
     */
    part_numbers: Array<number>;
    /**
     * S3 multipart upload identifier returned by initiate upload.
     */
    upload_id: string;
};

/**
 * SignPartsResponse
 *
 * Multipart sign-parts response.
 */
export type SignPartsResponse = {
    /**
     * Seconds until the presigned part URLs expire.
     */
    expires_in_seconds: number;
    /**
     * Presigned upload URL for each requested multipart part number.
     */
    urls: {
        [key: string]: string;
    };
};

/**
 * TransferCapabilitiesResponse
 *
 * Transfer policy capabilities exposed to clients and operators.
 */
export type TransferCapabilitiesResponse = {
    /**
     * Whether S3 Transfer Acceleration is enabled.
     */
    accelerate_enabled: boolean;
    /**
     * Maximum number of active multipart uploads per scope.
     */
    active_multipart_upload_limit: number;
    /**
     * Checksum algorithm callers should use when checksums apply.
     */
    checksum_algorithm?: string | null;
    /**
     * Server-enforced checksum mode for uploads.
     */
    checksum_mode: 'none' | 'optional' | 'required';
    /**
     * Per-scope daily ingress budget in bytes.
     */
    daily_ingress_budget_bytes: number;
    /**
     * Export size threshold in bytes for the worker-backed copy lane.
     */
    large_export_worker_threshold_bytes: number;
    /**
     * Suggested maximum number of concurrent client uploads.
     */
    max_concurrency_hint: number;
    /**
     * Maximum allowed upload size in bytes.
     */
    max_upload_bytes: number;
    /**
     * Maximum multipart part size accepted by the API.
     */
    maximum_part_size_bytes: number;
    /**
     * Minimum multipart part size accepted by the API.
     */
    minimum_part_size_bytes: number;
    /**
     * Object size in bytes at which multipart upload becomes required.
     */
    multipart_threshold_bytes: number;
    /**
     * Identifier of the effective transfer policy.
     */
    policy_id: string;
    /**
     * Version of the effective transfer policy.
     */
    policy_version: string;
    /**
     * How long multipart resume state remains valid, in seconds.
     */
    resumable_ttl_seconds: number;
    /**
     * Suggested maximum number of parts per sign-parts request.
     */
    sign_batch_size_hint: number;
    /**
     * Maximum number of sign-parts requests allowed per upload.
     */
    sign_requests_per_upload_limit: number;
    /**
     * Target number of multipart parts for large uploads.
     */
    target_upload_part_count: number;
};

/**
 * UploadIntrospectionRequest
 *
 * Multipart upload introspection request.
 */
export type UploadIntrospectionRequest = {
    /**
     * Storage key reserved for the multipart upload.
     */
    key: string;
    /**
     * S3 multipart upload identifier being inspected.
     */
    upload_id: string;
};

/**
 * UploadIntrospectionResponse
 *
 * Multipart upload introspection response.
 */
export type UploadIntrospectionResponse = {
    /**
     * Bucket that owns the multipart upload.
     */
    bucket: string;
    /**
     * Storage key reserved for the multipart upload.
     */
    key: string;
    /**
     * Configured multipart part size in bytes for this session.
     */
    part_size_bytes: number;
    /**
     * Multipart parts that have already been uploaded.
     */
    parts: Array<UploadedPart>;
    /**
     * S3 multipart upload identifier.
     */
    upload_id: string;
};

/**
 * UploadStrategy
 *
 * Upload strategy options returned by initiate endpoint.
 */
export type UploadStrategy = 'single' | 'multipart';

/**
 * UploadedPart
 *
 * Part state returned for multipart upload introspection.
 */
export type UploadedPart = {
    /**
     * ETag returned by S3 for the uploaded multipart part.
     */
    etag: string;
    /**
     * Multipart part number that has already been uploaded.
     */
    part_number: number;
};

/**
 * One request-validation issue with location, message, and error type.
 */
export type ValidationError = {
    /**
     * Optional structured context attached to the validation issue.
     */
    ctx?: {
        [key: string]: unknown;
    };
    /**
     * Original input value that failed validation when FastAPI exposes it.
     */
    input?: unknown;
    /**
     * Ordered location path that identifies the invalid request field.
     */
    loc: Array<string | number>;
    /**
     * Human-readable validation message.
     */
    msg: string;
    /**
     * Machine-readable validation error type identifier.
     */
    type: string;
};

/**
 * Request data for the `MetricsSummary` operation.
 */
export type MetricsSummaryData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/metrics/summary';
};

/**
 * Error responses for the `MetricsSummary` operation.
 */
export type MetricsSummaryErrors = {
    /**
     * Unauthorized - Bearer token is missing or invalid.
     */
    401: ErrorEnvelope;
    /**
     * Forbidden - Caller lacks required scope or permission.
     */
    403: ErrorEnvelope;
};

/**
 * Error union for the `MetricsSummary` operation.
 */
export type MetricsSummaryError = MetricsSummaryErrors[keyof MetricsSummaryErrors];

/**
 * Response variants for the `MetricsSummary` operation.
 */
export type MetricsSummaryResponses = {
    /**
     * Low-cardinality metrics and activity summary.
     */
    200: MetricsSummaryResponse;
};

export type MetricsSummaryResponse2 = MetricsSummaryResponses[keyof MetricsSummaryResponses];

/**
 * Request data for the `GetCapabilities` operation.
 */
export type GetCapabilitiesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/capabilities';
};

/**
 * Response variants for the `GetCapabilities` operation.
 */
export type GetCapabilitiesResponses = {
    /**
     * Runtime capability declarations for the deployment.
     */
    200: CapabilitiesResponse;
};

/**
 * Response union for the `GetCapabilities` operation.
 */
export type GetCapabilitiesResponse = GetCapabilitiesResponses[keyof GetCapabilitiesResponses];

/**
 * Request data for the `GetTransferCapabilities` operation.
 */
export type GetTransferCapabilitiesData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Optional workload-class hint used to resolve a narrower effective transfer policy.
         */
        workload_class?: string | null;
        /**
         * Optional policy hint evaluated by the transfer policy resolver.
         */
        policy_hint?: string | null;
    };
    url: '/v1/capabilities/transfers';
};

/**
 * Error responses for the `GetTransferCapabilities` operation.
 */
export type GetTransferCapabilitiesErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

/**
 * Error union for the `GetTransferCapabilities` operation.
 */
export type GetTransferCapabilitiesError = GetTransferCapabilitiesErrors[keyof GetTransferCapabilitiesErrors];

/**
 * Response variants for the `GetTransferCapabilities` operation.
 */
export type GetTransferCapabilitiesResponses = {
    /**
     * Effective transfer policy metadata and limits.
     */
    200: TransferCapabilitiesResponse;
};

/**
 * Response union for the `GetTransferCapabilities` operation.
 */
export type GetTransferCapabilitiesResponse = GetTransferCapabilitiesResponses[keyof GetTransferCapabilitiesResponses];

/**
 * Request data for the `ListExports` operation.
 */
export type ListExportsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Maximum number of caller-owned export workflow resources to return, ordered newest first.
         */
        limit?: number;
    };
    url: '/v1/exports';
};

/**
 * Error responses for the `ListExports` operation.
 */
export type ListExportsErrors = {
    /**
     * Unauthorized - Bearer token is missing or invalid.
     */
    401: ErrorEnvelope;
    /**
     * Forbidden - Caller lacks required scope or permission.
     */
    403: ErrorEnvelope;
    /**
     * Unprocessable Content - Request validation failed.
     */
    422: ErrorEnvelope;
};

/**
 * Error union for the `ListExports` operation.
 */
export type ListExportsError = ListExportsErrors[keyof ListExportsErrors];

/**
 * Response variants for the `ListExports` operation.
 */
export type ListExportsResponses = {
    /**
     * Page of caller-owned export workflow resources.
     */
    200: ExportListResponse;
};

/**
 * Response union for the `ListExports` operation.
 */
export type ListExportsResponse = ListExportsResponses[keyof ListExportsResponses];

/**
 * Request data for the `CreateExport` operation.
 */
export type CreateExportData = {
    body: CreateExportRequest;
    headers?: {
        /**
         * Idempotency-Key
         *
         * Client-supplied idempotency key used to deduplicate supported mutation requests.
         */
        'Idempotency-Key'?: string | null;
    };
    path?: never;
    query?: never;
    url: '/v1/exports';
};

/**
 * Error responses for the `CreateExport` operation.
 */
export type CreateExportErrors = {
    /**
     * Unauthorized - Bearer token is missing or invalid.
     */
    401: ErrorEnvelope;
    /**
     * Forbidden - Caller lacks required scope or permission.
     */
    403: ErrorEnvelope;
    /**
     * Conflict - Idempotency request is already in progress.
     */
    409: ErrorEnvelope;
    /**
     * Unprocessable Content - Request validation failed.
     */
    422: ErrorEnvelope;
    /**
     * Service Unavailable - Queue publishing or idempotency storage is unavailable.
     */
    503: ErrorEnvelope;
};

/**
 * Error union for the `CreateExport` operation.
 */
export type CreateExportError = CreateExportErrors[keyof CreateExportErrors];

/**
 * Response variants for the `CreateExport` operation.
 */
export type CreateExportResponses = {
    /**
     * Created export workflow resource.
     */
    201: ExportResource;
};

/**
 * Response union for the `CreateExport` operation.
 */
export type CreateExportResponse = CreateExportResponses[keyof CreateExportResponses];

/**
 * Request data for the `GetExport` operation.
 */
export type GetExportData = {
    body?: never;
    path: {
        /**
         * Identifier of the caller-owned export workflow resource.
         */
        export_id: string;
    };
    query?: never;
    url: '/v1/exports/{export_id}';
};

/**
 * Error responses for the `GetExport` operation.
 */
export type GetExportErrors = {
    /**
     * Unauthorized - Bearer token is missing or invalid.
     */
    401: ErrorEnvelope;
    /**
     * Forbidden - Caller lacks required scope or permission.
     */
    403: ErrorEnvelope;
    /**
     * Not Found - Export resource was not found.
     */
    404: ErrorEnvelope;
    /**
     * Unprocessable Content - Request validation failed.
     */
    422: ErrorEnvelope;
};

/**
 * Error union for the `GetExport` operation.
 */
export type GetExportError = GetExportErrors[keyof GetExportErrors];

/**
 * Response variants for the `GetExport` operation.
 */
export type GetExportResponses = {
    /**
     * Current export workflow resource.
     */
    200: ExportResource;
};

/**
 * Response union for the `GetExport` operation.
 */
export type GetExportResponse = GetExportResponses[keyof GetExportResponses];

/**
 * Request data for the `CancelExport` operation.
 */
export type CancelExportData = {
    body?: never;
    path: {
        /**
         * Identifier of the caller-owned export workflow resource.
         */
        export_id: string;
    };
    query?: never;
    url: '/v1/exports/{export_id}/cancel';
};

/**
 * Error responses for the `CancelExport` operation.
 */
export type CancelExportErrors = {
    /**
     * Unauthorized - Bearer token is missing or invalid.
     */
    401: ErrorEnvelope;
    /**
     * Forbidden - Caller lacks required scope or permission.
     */
    403: ErrorEnvelope;
    /**
     * Not Found - Export resource was not found.
     */
    404: ErrorEnvelope;
    /**
     * Unprocessable Content - Request validation failed.
     */
    422: ErrorEnvelope;
};

/**
 * Error union for the `CancelExport` operation.
 */
export type CancelExportError = CancelExportErrors[keyof CancelExportErrors];

/**
 * Response variants for the `CancelExport` operation.
 */
export type CancelExportResponses = {
    /**
     * Updated export workflow resource after cancel intent.
     */
    200: ExportResource;
};

/**
 * Response union for the `CancelExport` operation.
 */
export type CancelExportResponse = CancelExportResponses[keyof CancelExportResponses];

/**
 * Request data for the `HealthLive` operation.
 */
export type HealthLiveData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/health/live';
};

/**
 * Response variants for the `HealthLive` operation.
 */
export type HealthLiveResponses = {
    /**
     * Liveness status for the API runtime.
     */
    200: HealthResponse;
};

/**
 * Response union for the `HealthLive` operation.
 */
export type HealthLiveResponse = HealthLiveResponses[keyof HealthLiveResponses];

/**
 * Request data for the `HealthReady` operation.
 */
export type HealthReadyData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/health/ready';
};

/**
 * Error responses for the `HealthReady` operation.
 */
export type HealthReadyErrors = {
    /**
     * Service Unavailable - Readiness failed.
     */
    503: ReadinessResponse;
};

/**
 * Error union for the `HealthReady` operation.
 */
export type HealthReadyError = HealthReadyErrors[keyof HealthReadyErrors];

/**
 * Response variants for the `HealthReady` operation.
 */
export type HealthReadyResponses = {
    /**
     * Readiness status plus per-dependency readiness checks.
     */
    200: ReadinessResponse;
};

/**
 * Response union for the `HealthReady` operation.
 */
export type HealthReadyResponse = HealthReadyResponses[keyof HealthReadyResponses];

/**
 * Request data for the `GetReleaseInfo` operation.
 */
export type GetReleaseInfoData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/releases/info';
};

/**
 * Response variants for the `GetReleaseInfo` operation.
 */
export type GetReleaseInfoResponses = {
    /**
     * Release name, version, and environment metadata.
     */
    200: ReleaseInfoResponse;
};

/**
 * Response union for the `GetReleaseInfo` operation.
 */
export type GetReleaseInfoResponse = GetReleaseInfoResponses[keyof GetReleaseInfoResponses];

/**
 * Request data for the `PlanResources` operation.
 */
export type PlanResourcesData = {
    body: ResourcePlanRequest;
    path?: never;
    query?: never;
    url: '/v1/resources/plan';
};

/**
 * Error responses for the `PlanResources` operation.
 */
export type PlanResourcesErrors = {
    /**
     * Unprocessable Content - Request validation failed.
     */
    422: ErrorEnvelope;
};

/**
 * Error union for the `PlanResources` operation.
 */
export type PlanResourcesError = PlanResourcesErrors[keyof PlanResourcesErrors];

/**
 * Response variants for the `PlanResources` operation.
 */
export type PlanResourcesResponses = {
    /**
     * Supportability decisions for each requested resource.
     */
    200: ResourcePlanResponse;
};

/**
 * Response union for the `PlanResources` operation.
 */
export type PlanResourcesResponse = PlanResourcesResponses[keyof PlanResourcesResponses];

/**
 * Request data for the `PresignDownload` operation.
 */
export type PresignDownloadData = {
    body: PresignDownloadRequest;
    path?: never;
    query?: never;
    url: '/v1/transfers/downloads/presign';
};

/**
 * Error responses for the `PresignDownload` operation.
 */
export type PresignDownloadErrors = {
    /**
     * Unauthorized - Bearer token is missing or invalid.
     */
    401: ErrorEnvelope;
    /**
     * Forbidden - Caller lacks required scope or permission.
     */
    403: ErrorEnvelope;
    /**
     * Unprocessable Content - Request validation failed.
     */
    422: ErrorEnvelope;
};

/**
 * Error union for the `PresignDownload` operation.
 */
export type PresignDownloadError = PresignDownloadErrors[keyof PresignDownloadErrors];

/**
 * Response variants for the `PresignDownload` operation.
 */
export type PresignDownloadResponses = {
    /**
     * Presigned download URL and associated object metadata.
     */
    200: PresignDownloadResponse;
};

export type PresignDownloadResponse2 = PresignDownloadResponses[keyof PresignDownloadResponses];

/**
 * Request data for the `AbortUpload` operation.
 */
export type AbortUploadData = {
    body: AbortUploadRequest;
    path?: never;
    query?: never;
    url: '/v1/transfers/uploads/abort';
};

/**
 * Error responses for the `AbortUpload` operation.
 */
export type AbortUploadErrors = {
    /**
     * Unauthorized - Bearer token is missing or invalid.
     */
    401: ErrorEnvelope;
    /**
     * Forbidden - Caller lacks required scope or permission.
     */
    403: ErrorEnvelope;
    /**
     * Unprocessable Content - Request validation failed.
     */
    422: ErrorEnvelope;
};

/**
 * Error union for the `AbortUpload` operation.
 */
export type AbortUploadError = AbortUploadErrors[keyof AbortUploadErrors];

/**
 * Response variants for the `AbortUpload` operation.
 */
export type AbortUploadResponses = {
    /**
     * Acknowledgement that the multipart upload was aborted.
     */
    200: AbortUploadResponse;
};

export type AbortUploadResponse2 = AbortUploadResponses[keyof AbortUploadResponses];

/**
 * Request data for the `CompleteUpload` operation.
 */
export type CompleteUploadData = {
    body: CompleteUploadRequest;
    path?: never;
    query?: never;
    url: '/v1/transfers/uploads/complete';
};

/**
 * Error responses for the `CompleteUpload` operation.
 */
export type CompleteUploadErrors = {
    /**
     * Unauthorized - Bearer token is missing or invalid.
     */
    401: ErrorEnvelope;
    /**
     * Forbidden - Caller lacks required scope or permission.
     */
    403: ErrorEnvelope;
    /**
     * Unprocessable Content - Request validation failed.
     */
    422: ErrorEnvelope;
};

/**
 * Error union for the `CompleteUpload` operation.
 */
export type CompleteUploadError = CompleteUploadErrors[keyof CompleteUploadErrors];

/**
 * Response variants for the `CompleteUpload` operation.
 */
export type CompleteUploadResponses = {
    /**
     * Completed object metadata for the finalized upload.
     */
    200: CompleteUploadResponse;
};

export type CompleteUploadResponse2 = CompleteUploadResponses[keyof CompleteUploadResponses];

/**
 * Request data for the `InitiateUpload` operation.
 */
export type InitiateUploadData = {
    body: InitiateUploadRequest;
    headers?: {
        /**
         * Idempotency-Key
         *
         * Client-supplied idempotency key used to deduplicate supported mutation requests.
         */
        'Idempotency-Key'?: string | null;
    };
    path?: never;
    query?: never;
    url: '/v1/transfers/uploads/initiate';
};

/**
 * Error responses for the `InitiateUpload` operation.
 */
export type InitiateUploadErrors = {
    /**
     * Unauthorized - Bearer token is missing or invalid.
     */
    401: ErrorEnvelope;
    /**
     * Forbidden - Caller lacks required scope or permission.
     */
    403: ErrorEnvelope;
    /**
     * Conflict - Idempotency request is already in progress.
     */
    409: ErrorEnvelope;
    /**
     * Unprocessable Content - Request validation failed.
     */
    422: ErrorEnvelope;
    /**
     * Service Unavailable - Idempotency storage is unavailable.
     */
    503: ErrorEnvelope;
};

/**
 * Error union for the `InitiateUpload` operation.
 */
export type InitiateUploadError = InitiateUploadErrors[keyof InitiateUploadErrors];

/**
 * Response variants for the `InitiateUpload` operation.
 */
export type InitiateUploadResponses = {
    /**
     * Resolved upload session metadata, policy hints, and presigned inputs.
     */
    200: InitiateUploadResponse;
};

export type InitiateUploadResponse2 = InitiateUploadResponses[keyof InitiateUploadResponses];

/**
 * Request data for the `IntrospectUpload` operation.
 */
export type IntrospectUploadData = {
    body: UploadIntrospectionRequest;
    path?: never;
    query?: never;
    url: '/v1/transfers/uploads/introspect';
};

/**
 * Error responses for the `IntrospectUpload` operation.
 */
export type IntrospectUploadErrors = {
    /**
     * Unauthorized - Bearer token is missing or invalid.
     */
    401: ErrorEnvelope;
    /**
     * Forbidden - Caller lacks required scope or permission.
     */
    403: ErrorEnvelope;
    /**
     * Unprocessable Content - Request validation failed.
     */
    422: ErrorEnvelope;
};

/**
 * Error union for the `IntrospectUpload` operation.
 */
export type IntrospectUploadError = IntrospectUploadErrors[keyof IntrospectUploadErrors];

/**
 * Response variants for the `IntrospectUpload` operation.
 */
export type IntrospectUploadResponses = {
    /**
     * Current multipart upload state, including uploaded parts.
     */
    200: UploadIntrospectionResponse;
};

/**
 * Response union for the `IntrospectUpload` operation.
 */
export type IntrospectUploadResponse = IntrospectUploadResponses[keyof IntrospectUploadResponses];

/**
 * Request data for the `SignUploadParts` operation.
 */
export type SignUploadPartsData = {
    body: SignPartsRequest;
    path?: never;
    query?: never;
    url: '/v1/transfers/uploads/sign-parts';
};

/**
 * Error responses for the `SignUploadParts` operation.
 */
export type SignUploadPartsErrors = {
    /**
     * Unauthorized - Bearer token is missing or invalid.
     */
    401: ErrorEnvelope;
    /**
     * Forbidden - Caller lacks required scope or permission.
     */
    403: ErrorEnvelope;
    /**
     * Unprocessable Content - Request validation failed.
     */
    422: ErrorEnvelope;
};

/**
 * Error union for the `SignUploadParts` operation.
 */
export type SignUploadPartsError = SignUploadPartsErrors[keyof SignUploadPartsErrors];

/**
 * Response variants for the `SignUploadParts` operation.
 */
export type SignUploadPartsResponses = {
    /**
     * Presigned multipart part URLs and their TTL.
     */
    200: SignPartsResponse;
};

/**
 * Response union for the `SignUploadParts` operation.
 */
export type SignUploadPartsResponse = SignUploadPartsResponses[keyof SignUploadPartsResponses];
