// Code generated by scripts/release/generate_clients.py. DO NOT EDIT.

import { createFetchClient } from "@nova/sdk-fetch/client";
import type { FetchClientOptions, OperationDescriptor, PathParams, QueryParams } from "@nova/sdk-fetch/contracts";
import { normalizeBaseUrl } from "@nova/sdk-fetch/url";
import { NovaSdkTransportError } from "./errors.js";
import { operations } from "./operations.js";
import type { MetricsSummaryRequestOptions, MetricsSummaryResult, GetCapabilitiesRequestOptions, GetCapabilitiesResult, HealthLiveRequestOptions, HealthLiveResult, HealthReadyRequestOptions, HealthReadyResult, ListJobsRequestOptions, ListJobsResult, CreateJobRequestOptions, CreateJobResult, GetJobStatusRequestOptions, GetJobStatusResult, CancelJobRequestOptions, CancelJobResult, ListJobEventsRequestOptions, ListJobEventsResult, RetryJobRequestOptions, RetryJobResult, GetReleaseInfoRequestOptions, GetReleaseInfoResult, PlanResourcesRequestOptions, PlanResourcesResult, PresignDownloadRequestOptions, PresignDownloadResult, AbortUploadRequestOptions, AbortUploadResult, CompleteUploadRequestOptions, CompleteUploadResult, InitiateUploadRequestOptions, InitiateUploadResult, SignUploadPartsRequestOptions, SignUploadPartsResult } from "./types.js";

/**
 * Options for configuring the generated @nova/sdk-file client.
 */
export interface NovaFileClientOptions extends FetchClientOptions {}

/**
 * Generated client surface for the @nova/sdk-file API.
 */
export interface NovaFileClient {
  readonly baseUrl: string;
  /**
   * Invoke the `metrics_summary` operation.
   */
  metrics_summary(request?: MetricsSummaryRequestOptions): Promise<MetricsSummaryResult>;
  /**
   * Invoke the `get_capabilities` operation.
   */
  get_capabilities(request?: GetCapabilitiesRequestOptions): Promise<GetCapabilitiesResult>;
  /**
   * Invoke the `health_live` operation.
   */
  health_live(request?: HealthLiveRequestOptions): Promise<HealthLiveResult>;
  /**
   * Invoke the `health_ready` operation.
   */
  health_ready(request?: HealthReadyRequestOptions): Promise<HealthReadyResult>;
  /**
   * Invoke the `list_jobs` operation.
   */
  list_jobs(request?: ListJobsRequestOptions): Promise<ListJobsResult>;
  /**
   * Invoke the `create_job` operation.
   */
  create_job(request: CreateJobRequestOptions): Promise<CreateJobResult>;
  /**
   * Invoke the `get_job_status` operation.
   */
  get_job_status(request: GetJobStatusRequestOptions): Promise<GetJobStatusResult>;
  /**
   * Invoke the `cancel_job` operation.
   */
  cancel_job(request: CancelJobRequestOptions): Promise<CancelJobResult>;
  /**
   * Invoke the `list_job_events` operation.
   */
  list_job_events(request: ListJobEventsRequestOptions): Promise<ListJobEventsResult>;
  /**
   * Invoke the `retry_job` operation.
   */
  retry_job(request: RetryJobRequestOptions): Promise<RetryJobResult>;
  /**
   * Invoke the `get_release_info` operation.
   */
  get_release_info(request?: GetReleaseInfoRequestOptions): Promise<GetReleaseInfoResult>;
  /**
   * Invoke the `plan_resources` operation.
   */
  plan_resources(request: PlanResourcesRequestOptions): Promise<PlanResourcesResult>;
  /**
   * Invoke the `presign_download` operation.
   */
  presign_download(request: PresignDownloadRequestOptions): Promise<PresignDownloadResult>;
  /**
   * Invoke the `abort_upload` operation.
   */
  abort_upload(request: AbortUploadRequestOptions): Promise<AbortUploadResult>;
  /**
   * Invoke the `complete_upload` operation.
   */
  complete_upload(request: CompleteUploadRequestOptions): Promise<CompleteUploadResult>;
  /**
   * Invoke the `initiate_upload` operation.
   */
  initiate_upload(request: InitiateUploadRequestOptions): Promise<InitiateUploadResult>;
  /**
   * Invoke the `sign_upload_parts` operation.
   */
  sign_upload_parts(request: SignUploadPartsRequestOptions): Promise<SignUploadPartsResult>;
}

type OperationRequest = {
  readonly body?: unknown;
  readonly contentType?: string;
  readonly headers?: HeadersInit;
  readonly pathParams?: PathParams;
  readonly query?: QueryParams;
  readonly signal?: AbortSignal;
};

async function executeOperation<TResult>(
  fetchClient: ReturnType<typeof createFetchClient>,
  operation: OperationDescriptor,
  request: OperationRequest = {},
  defaultContentType?: string,
): Promise<TResult> {
  try {
    return (await fetchClient.request<unknown>(operation, {
      body: request.body,
      contentType: request.contentType ?? defaultContentType,
      headers: request.headers,
      pathParams: request.pathParams,
      query: request.query,
      signal: request.signal,
    })) as TResult;
  } catch (error) {
    throw new NovaSdkTransportError(operation.operationId, error);
  }
}

/**
 * Create a generated client for the @nova/sdk-file API.
 *
 * @param options - Transport and base URL options for the client.
 * @returns A configured NovaFileClient instance.
 */
export function createNovaFileClient(
  options: NovaFileClientOptions,
): NovaFileClient {
  const fetchClient = createFetchClient(options);
  const baseUrl = normalizeBaseUrl(options.baseUrl);

  return {
    baseUrl,
    /**
     * Invoke the `metrics_summary` operation.
     */
    async metrics_summary(request?: MetricsSummaryRequestOptions): Promise<MetricsSummaryResult> {
      return executeOperation<MetricsSummaryResult>(
        fetchClient,
        operations.metrics_summary,
        request ?? {} as OperationRequest,
        undefined,
      );
    },
    /**
     * Invoke the `get_capabilities` operation.
     */
    async get_capabilities(request?: GetCapabilitiesRequestOptions): Promise<GetCapabilitiesResult> {
      return executeOperation<GetCapabilitiesResult>(
        fetchClient,
        operations.get_capabilities,
        request ?? {} as OperationRequest,
        undefined,
      );
    },
    /**
     * Invoke the `health_live` operation.
     */
    async health_live(request?: HealthLiveRequestOptions): Promise<HealthLiveResult> {
      return executeOperation<HealthLiveResult>(
        fetchClient,
        operations.health_live,
        request ?? {} as OperationRequest,
        undefined,
      );
    },
    /**
     * Invoke the `health_ready` operation.
     */
    async health_ready(request?: HealthReadyRequestOptions): Promise<HealthReadyResult> {
      return executeOperation<HealthReadyResult>(
        fetchClient,
        operations.health_ready,
        request ?? {} as OperationRequest,
        undefined,
      );
    },
    /**
     * Invoke the `list_jobs` operation.
     */
    async list_jobs(request?: ListJobsRequestOptions): Promise<ListJobsResult> {
      return executeOperation<ListJobsResult>(
        fetchClient,
        operations.list_jobs,
        request ?? {} as OperationRequest,
        undefined,
      );
    },
    /**
     * Invoke the `create_job` operation.
     */
    async create_job(request: CreateJobRequestOptions): Promise<CreateJobResult> {
      return executeOperation<CreateJobResult>(
        fetchClient,
        operations.create_job,
        request as OperationRequest,
        "application/json",
      );
    },
    /**
     * Invoke the `get_job_status` operation.
     */
    async get_job_status(request: GetJobStatusRequestOptions): Promise<GetJobStatusResult> {
      return executeOperation<GetJobStatusResult>(
        fetchClient,
        operations.get_job_status,
        request as OperationRequest,
        undefined,
      );
    },
    /**
     * Invoke the `cancel_job` operation.
     */
    async cancel_job(request: CancelJobRequestOptions): Promise<CancelJobResult> {
      return executeOperation<CancelJobResult>(
        fetchClient,
        operations.cancel_job,
        request as OperationRequest,
        undefined,
      );
    },
    /**
     * Invoke the `list_job_events` operation.
     */
    async list_job_events(request: ListJobEventsRequestOptions): Promise<ListJobEventsResult> {
      return executeOperation<ListJobEventsResult>(
        fetchClient,
        operations.list_job_events,
        request as OperationRequest,
        undefined,
      );
    },
    /**
     * Invoke the `retry_job` operation.
     */
    async retry_job(request: RetryJobRequestOptions): Promise<RetryJobResult> {
      return executeOperation<RetryJobResult>(
        fetchClient,
        operations.retry_job,
        request as OperationRequest,
        undefined,
      );
    },
    /**
     * Invoke the `get_release_info` operation.
     */
    async get_release_info(request?: GetReleaseInfoRequestOptions): Promise<GetReleaseInfoResult> {
      return executeOperation<GetReleaseInfoResult>(
        fetchClient,
        operations.get_release_info,
        request ?? {} as OperationRequest,
        undefined,
      );
    },
    /**
     * Invoke the `plan_resources` operation.
     */
    async plan_resources(request: PlanResourcesRequestOptions): Promise<PlanResourcesResult> {
      return executeOperation<PlanResourcesResult>(
        fetchClient,
        operations.plan_resources,
        request as OperationRequest,
        "application/json",
      );
    },
    /**
     * Invoke the `presign_download` operation.
     */
    async presign_download(request: PresignDownloadRequestOptions): Promise<PresignDownloadResult> {
      return executeOperation<PresignDownloadResult>(
        fetchClient,
        operations.presign_download,
        request as OperationRequest,
        "application/json",
      );
    },
    /**
     * Invoke the `abort_upload` operation.
     */
    async abort_upload(request: AbortUploadRequestOptions): Promise<AbortUploadResult> {
      return executeOperation<AbortUploadResult>(
        fetchClient,
        operations.abort_upload,
        request as OperationRequest,
        "application/json",
      );
    },
    /**
     * Invoke the `complete_upload` operation.
     */
    async complete_upload(request: CompleteUploadRequestOptions): Promise<CompleteUploadResult> {
      return executeOperation<CompleteUploadResult>(
        fetchClient,
        operations.complete_upload,
        request as OperationRequest,
        "application/json",
      );
    },
    /**
     * Invoke the `initiate_upload` operation.
     */
    async initiate_upload(request: InitiateUploadRequestOptions): Promise<InitiateUploadResult> {
      return executeOperation<InitiateUploadResult>(
        fetchClient,
        operations.initiate_upload,
        request as OperationRequest,
        "application/json",
      );
    },
    /**
     * Invoke the `sign_upload_parts` operation.
     */
    async sign_upload_parts(request: SignUploadPartsRequestOptions): Promise<SignUploadPartsResult> {
      return executeOperation<SignUploadPartsResult>(
        fetchClient,
        operations.sign_upload_parts,
        request as OperationRequest,
        "application/json",
      );
    },
  };
}
