// Code generated by scripts/release/generate_clients.py. DO NOT EDIT.

import type { OperationDescriptor } from "@nova/sdk-fetch/contracts";

/** Catalog of generated public operations keyed by operationId. */
export const operations = {
  "metrics_summary": {
    operationId: "metrics_summary",
    method: "GET",
    path: "/metrics/summary",
    summary: "Metrics Summary",
  },
  "get_capabilities": {
    operationId: "get_capabilities",
    method: "GET",
    path: "/v1/capabilities",
    summary: "Get Capabilities",
  },
  "health_live": {
    operationId: "health_live",
    method: "GET",
    path: "/v1/health/live",
    summary: "Health Live",
  },
  "health_ready": {
    operationId: "health_ready",
    method: "GET",
    path: "/v1/health/ready",
    summary: "Health Ready",
  },
  "list_jobs": {
    operationId: "list_jobs",
    method: "GET",
    path: "/v1/jobs",
    summary: "List Jobs",
  },
  "create_job": {
    operationId: "create_job",
    method: "POST",
    path: "/v1/jobs",
    summary: "Create Job",
  },
  "get_job_status": {
    operationId: "get_job_status",
    method: "GET",
    path: "/v1/jobs/{job_id}",
    summary: "Get Job Status",
  },
  "cancel_job": {
    operationId: "cancel_job",
    method: "POST",
    path: "/v1/jobs/{job_id}/cancel",
    summary: "Cancel Job",
  },
  "list_job_events": {
    operationId: "list_job_events",
    method: "GET",
    path: "/v1/jobs/{job_id}/events",
    summary: "List Job Events",
  },
  "retry_job": {
    operationId: "retry_job",
    method: "POST",
    path: "/v1/jobs/{job_id}/retry",
    summary: "Retry Job",
  },
  "get_release_info": {
    operationId: "get_release_info",
    method: "GET",
    path: "/v1/releases/info",
    summary: "Get Release Info",
  },
  "plan_resources": {
    operationId: "plan_resources",
    method: "POST",
    path: "/v1/resources/plan",
    summary: "Plan Resources",
  },
  "presign_download": {
    operationId: "presign_download",
    method: "POST",
    path: "/v1/transfers/downloads/presign",
    summary: "Presign Download",
  },
  "abort_upload": {
    operationId: "abort_upload",
    method: "POST",
    path: "/v1/transfers/uploads/abort",
    summary: "Abort Upload",
  },
  "complete_upload": {
    operationId: "complete_upload",
    method: "POST",
    path: "/v1/transfers/uploads/complete",
    summary: "Complete Upload",
  },
  "initiate_upload": {
    operationId: "initiate_upload",
    method: "POST",
    path: "/v1/transfers/uploads/initiate",
    summary: "Initiate Upload",
  },
  "introspect_upload": {
    operationId: "introspect_upload",
    method: "POST",
    path: "/v1/transfers/uploads/introspect",
    summary: "Introspect Upload",
  },
  "sign_upload_parts": {
    operationId: "sign_upload_parts",
    method: "POST",
    path: "/v1/transfers/uploads/sign-parts",
    summary: "Sign Upload Parts",
  },
} as const satisfies Record<string, OperationDescriptor>;

/** Union of all generated public operation identifiers. */
export type OperationId = keyof typeof operations;
/** Static type representing the generated public operations catalog. */
export type GeneratedOperationCatalog = typeof operations;
