// Code generated by scripts/release/generate_clients.py. DO NOT EDIT.

/** Describes one generated public operation entry in the static catalog. */
export interface OperationDescriptor {
  readonly operationId: string;
  readonly method: string;
  readonly path: string;
  readonly summary?: string;
}

/** Catalog of generated public operations keyed by operationId. */
export const operations = {
  "metrics_summary": {
    operationId: "metrics_summary",
    method: "GET",
    path: "/metrics/summary",
    summary: "Metrics Summary",
  },
  "get_capabilities": {
    operationId: "get_capabilities",
    method: "GET",
    path: "/v1/capabilities",
    summary: "Get Capabilities",
  },
  "list_exports": {
    operationId: "list_exports",
    method: "GET",
    path: "/v1/exports",
    summary: "List Exports",
  },
  "create_export": {
    operationId: "create_export",
    method: "POST",
    path: "/v1/exports",
    summary: "Create Export",
  },
  "get_export": {
    operationId: "get_export",
    method: "GET",
    path: "/v1/exports/{export_id}",
    summary: "Get Export",
  },
  "cancel_export": {
    operationId: "cancel_export",
    method: "POST",
    path: "/v1/exports/{export_id}/cancel",
    summary: "Cancel Export",
  },
  "health_live": {
    operationId: "health_live",
    method: "GET",
    path: "/v1/health/live",
    summary: "Health Live",
  },
  "health_ready": {
    operationId: "health_ready",
    method: "GET",
    path: "/v1/health/ready",
    summary: "Health Ready",
  },
  "get_release_info": {
    operationId: "get_release_info",
    method: "GET",
    path: "/v1/releases/info",
    summary: "Get Release Info",
  },
  "plan_resources": {
    operationId: "plan_resources",
    method: "POST",
    path: "/v1/resources/plan",
    summary: "Plan Resources",
  },
  "presign_download": {
    operationId: "presign_download",
    method: "POST",
    path: "/v1/transfers/downloads/presign",
    summary: "Presign Download",
  },
  "abort_upload": {
    operationId: "abort_upload",
    method: "POST",
    path: "/v1/transfers/uploads/abort",
    summary: "Abort Upload",
  },
  "complete_upload": {
    operationId: "complete_upload",
    method: "POST",
    path: "/v1/transfers/uploads/complete",
    summary: "Complete Upload",
  },
  "initiate_upload": {
    operationId: "initiate_upload",
    method: "POST",
    path: "/v1/transfers/uploads/initiate",
    summary: "Initiate Upload",
  },
  "introspect_upload": {
    operationId: "introspect_upload",
    method: "POST",
    path: "/v1/transfers/uploads/introspect",
    summary: "Introspect Upload",
  },
  "sign_upload_parts": {
    operationId: "sign_upload_parts",
    method: "POST",
    path: "/v1/transfers/uploads/sign-parts",
    summary: "Sign Upload Parts",
  },
} as const satisfies Record<string, OperationDescriptor>;

/** Union of all generated public operation identifiers. */
export type OperationId = keyof typeof operations;
/** Static type representing the generated public operations catalog. */
export type GeneratedOperationCatalog = typeof operations;
