// Code generated by scripts/release/generate_clients.py. DO NOT EDIT.

import type {
  components as GeneratedComponents,
  operations as GeneratedOperations,
} from "./generated/openapi.js";

type EmptyObject = Record<string, never>;
type SuccessStatus = 200 | 201 | 202 | 203 | 204 | 205 | 206 | 207 | 208 | 226;
type Simplify<T> = { [K in keyof T]: T[K] } & {};
type OperationOf<TId extends keyof GeneratedOperations> = GeneratedOperations[TId];
type ParametersOf<T> = T extends { parameters: infer TParameters } ? TParameters : EmptyObject;
type FieldOf<TParameters, TKey extends "query" | "header" | "path"> = TParameters extends { [K in TKey]?: infer TValue }
  ? [TValue] extends [never]
    ? EmptyObject
    : TValue
  : EmptyObject;
type ContentOf<TContent, TMediaType extends string> = TContent extends Record<PropertyKey, unknown>
  ? TMediaType extends keyof TContent
    ? TContent[TMediaType]
    : never
  : never;
type JsonContentOf<TContent> = TContent extends Record<PropertyKey, unknown>
  ? "application/json" extends keyof TContent
    ? TContent["application/json"]
    : null
  : null;
type RequestContentTypesOf<T> = T extends { requestBody: { content: infer TContent } }
  ? Extract<keyof TContent, string>
  : never;
type RequestBodyOf<T> = T extends { requestBody: { content: infer TContent } }
  ? ContentOf<TContent, RequestContentTypesOf<T>>
  : never;
type RequestBodyForContentType<T, TContentType extends string> = T extends { requestBody: { content: infer TContent } }
  ? ContentOf<TContent, TContentType>
  : never;
type ResponsesOf<T> = T extends { responses: infer TResponses } ? TResponses : EmptyObject;
type StatusCodeOf<TResponses> = Extract<keyof TResponses, number>;
type SuccessStatusCodeOf<TResponses> = Extract<StatusCodeOf<TResponses>, SuccessStatus>;
type ErrorStatusCodeOf<TResponses> = Exclude<StatusCodeOf<TResponses>, SuccessStatus>;
type ResponseBodyOf<TEntry> = TEntry extends { content: infer TContent }
  ? JsonContentOf<TContent>
  : null;
type DefaultResponseDataOf<TResponses> = "default" extends keyof TResponses
  ? ResponseBodyOf<TResponses["default"]>
  : never;
type ResponseDataOf<TResponses, TStatusCodes extends number> = TStatusCodes extends StatusCodeOf<TResponses>
  ? ResponseBodyOf<TResponses[TStatusCodes]>
  : never;
type ErrorDataOf<TResponses> =
  | ResponseDataOf<TResponses, ErrorStatusCodeOf<TResponses>>
  | DefaultResponseDataOf<TResponses>;

/** Named aliases for generated OpenAPI component schemas. */
/** OpenAPI component schema `AbortUploadRequest`. */
export type AbortUploadRequest = GeneratedComponents["schemas"]["AbortUploadRequest"];
/** OpenAPI component schema `AbortUploadResponse`. */
export type AbortUploadResponse = GeneratedComponents["schemas"]["AbortUploadResponse"];
/** OpenAPI component schema `CapabilitiesResponse`. */
export type CapabilitiesResponse = GeneratedComponents["schemas"]["CapabilitiesResponse"];
/** OpenAPI component schema `CapabilityDescriptor`. */
export type CapabilityDescriptor = GeneratedComponents["schemas"]["CapabilityDescriptor"];
/** OpenAPI component schema `CompleteUploadRequest`. */
export type CompleteUploadRequest = GeneratedComponents["schemas"]["CompleteUploadRequest"];
/** OpenAPI component schema `CompleteUploadResponse`. */
export type CompleteUploadResponse = GeneratedComponents["schemas"]["CompleteUploadResponse"];
/** OpenAPI component schema `CompletedPart`. */
export type CompletedPart = GeneratedComponents["schemas"]["CompletedPart"];
/** OpenAPI component schema `CreateExportRequest`. */
export type CreateExportRequest = GeneratedComponents["schemas"]["CreateExportRequest"];
/** OpenAPI component schema `ErrorBody`. */
export type ErrorBody = GeneratedComponents["schemas"]["ErrorBody"];
/** OpenAPI component schema `ErrorEnvelope`. */
export type ErrorEnvelope = GeneratedComponents["schemas"]["ErrorEnvelope"];
/** OpenAPI component schema `ExportListResponse`. */
export type ExportListResponse = GeneratedComponents["schemas"]["ExportListResponse"];
/** OpenAPI component schema `ExportOutput`. */
export type ExportOutput = GeneratedComponents["schemas"]["ExportOutput"];
/** OpenAPI component schema `ExportResource`. */
export type ExportResource = GeneratedComponents["schemas"]["ExportResource"];
/** OpenAPI component schema `ExportStatus`. */
export type ExportStatus = GeneratedComponents["schemas"]["ExportStatus"];
/** OpenAPI component schema `HealthResponse`. */
export type HealthResponse = GeneratedComponents["schemas"]["HealthResponse"];
/** OpenAPI component schema `InitiateUploadRequest`. */
export type InitiateUploadRequest = GeneratedComponents["schemas"]["InitiateUploadRequest"];
/** OpenAPI component schema `InitiateUploadResponse`. */
export type InitiateUploadResponse = GeneratedComponents["schemas"]["InitiateUploadResponse"];
/** OpenAPI component schema `MetricsSummaryResponse`. */
export type MetricsSummaryResponse = GeneratedComponents["schemas"]["MetricsSummaryResponse"];
/** OpenAPI component schema `PresignDownloadRequest`. */
export type PresignDownloadRequest = GeneratedComponents["schemas"]["PresignDownloadRequest"];
/** OpenAPI component schema `PresignDownloadResponse`. */
export type PresignDownloadResponse = GeneratedComponents["schemas"]["PresignDownloadResponse"];
/** OpenAPI component schema `ReadinessResponse`. */
export type ReadinessResponse = GeneratedComponents["schemas"]["ReadinessResponse"];
/** OpenAPI component schema `ReleaseInfoResponse`. */
export type ReleaseInfoResponse = GeneratedComponents["schemas"]["ReleaseInfoResponse"];
/** OpenAPI component schema `ResourcePlanItem`. */
export type ResourcePlanItem = GeneratedComponents["schemas"]["ResourcePlanItem"];
/** OpenAPI component schema `ResourcePlanRequest`. */
export type ResourcePlanRequest = GeneratedComponents["schemas"]["ResourcePlanRequest"];
/** OpenAPI component schema `ResourcePlanResponse`. */
export type ResourcePlanResponse = GeneratedComponents["schemas"]["ResourcePlanResponse"];
/** OpenAPI component schema `SignPartsRequest`. */
export type SignPartsRequest = GeneratedComponents["schemas"]["SignPartsRequest"];
/** OpenAPI component schema `SignPartsResponse`. */
export type SignPartsResponse = GeneratedComponents["schemas"]["SignPartsResponse"];
/** OpenAPI component schema `UploadIntrospectionRequest`. */
export type UploadIntrospectionRequest = GeneratedComponents["schemas"]["UploadIntrospectionRequest"];
/** OpenAPI component schema `UploadIntrospectionResponse`. */
export type UploadIntrospectionResponse = GeneratedComponents["schemas"]["UploadIntrospectionResponse"];
/** OpenAPI component schema `UploadStrategy`. */
export type UploadStrategy = GeneratedComponents["schemas"]["UploadStrategy"];
/** OpenAPI component schema `UploadedPart`. */
export type UploadedPart = GeneratedComponents["schemas"]["UploadedPart"];

/** Operation-specific request and response helpers. */

type MetricsSummarySpec = OperationOf<"metrics_summary">;
export type MetricsSummaryOperation = MetricsSummarySpec;
export type MetricsSummaryPathParams = Simplify<FieldOf<ParametersOf<MetricsSummarySpec>, "path">>;
export type MetricsSummaryQueryParams = Simplify<FieldOf<ParametersOf<MetricsSummarySpec>, "query">>;
export type MetricsSummaryHeaders = Simplify<FieldOf<ParametersOf<MetricsSummarySpec>, "header">>;
export type MetricsSummaryRequestContentType = RequestContentTypesOf<MetricsSummarySpec>;
export type MetricsSummaryRequestBody = RequestBodyOf<MetricsSummarySpec>;
export type MetricsSummaryRequestBodyForContentType<TContentType extends MetricsSummaryRequestContentType> = RequestBodyForContentType<MetricsSummarySpec, TContentType>;
export type MetricsSummaryResponses = ResponsesOf<MetricsSummarySpec>;
/** Union of success response payloads for `metrics_summary`. */
export type MetricsSummarySuccessData = ResponseDataOf<MetricsSummaryResponses, SuccessStatusCodeOf<MetricsSummaryResponses>>;
/** Union of non-success response payloads for `metrics_summary`. */
export type MetricsSummaryErrorData = ErrorDataOf<MetricsSummaryResponses>;
export type MetricsSummaryResponse200 = ResponseBodyOf<MetricsSummaryResponses[200]>;
export type MetricsSummaryResponse401 = ResponseBodyOf<MetricsSummaryResponses[401]>;
export type MetricsSummaryResponse403 = ResponseBodyOf<MetricsSummaryResponses[403]>;

type GetCapabilitiesSpec = OperationOf<"get_capabilities">;
export type GetCapabilitiesOperation = GetCapabilitiesSpec;
export type GetCapabilitiesPathParams = Simplify<FieldOf<ParametersOf<GetCapabilitiesSpec>, "path">>;
export type GetCapabilitiesQueryParams = Simplify<FieldOf<ParametersOf<GetCapabilitiesSpec>, "query">>;
export type GetCapabilitiesHeaders = Simplify<FieldOf<ParametersOf<GetCapabilitiesSpec>, "header">>;
export type GetCapabilitiesRequestContentType = RequestContentTypesOf<GetCapabilitiesSpec>;
export type GetCapabilitiesRequestBody = RequestBodyOf<GetCapabilitiesSpec>;
export type GetCapabilitiesRequestBodyForContentType<TContentType extends GetCapabilitiesRequestContentType> = RequestBodyForContentType<GetCapabilitiesSpec, TContentType>;
export type GetCapabilitiesResponses = ResponsesOf<GetCapabilitiesSpec>;
/** Union of success response payloads for `get_capabilities`. */
export type GetCapabilitiesSuccessData = ResponseDataOf<GetCapabilitiesResponses, SuccessStatusCodeOf<GetCapabilitiesResponses>>;
/** Union of non-success response payloads for `get_capabilities`. */
export type GetCapabilitiesErrorData = ErrorDataOf<GetCapabilitiesResponses>;
export type GetCapabilitiesResponse200 = ResponseBodyOf<GetCapabilitiesResponses[200]>;

type ListExportsSpec = OperationOf<"list_exports">;
export type ListExportsOperation = ListExportsSpec;
export type ListExportsPathParams = Simplify<FieldOf<ParametersOf<ListExportsSpec>, "path">>;
export type ListExportsQueryParams = Simplify<FieldOf<ParametersOf<ListExportsSpec>, "query">>;
export type ListExportsHeaders = Simplify<FieldOf<ParametersOf<ListExportsSpec>, "header">>;
export type ListExportsRequestContentType = RequestContentTypesOf<ListExportsSpec>;
export type ListExportsRequestBody = RequestBodyOf<ListExportsSpec>;
export type ListExportsRequestBodyForContentType<TContentType extends ListExportsRequestContentType> = RequestBodyForContentType<ListExportsSpec, TContentType>;
export type ListExportsResponses = ResponsesOf<ListExportsSpec>;
/** Union of success response payloads for `list_exports`. */
export type ListExportsSuccessData = ResponseDataOf<ListExportsResponses, SuccessStatusCodeOf<ListExportsResponses>>;
/** Union of non-success response payloads for `list_exports`. */
export type ListExportsErrorData = ErrorDataOf<ListExportsResponses>;
export type ListExportsResponse200 = ResponseBodyOf<ListExportsResponses[200]>;
export type ListExportsResponse401 = ResponseBodyOf<ListExportsResponses[401]>;
export type ListExportsResponse403 = ResponseBodyOf<ListExportsResponses[403]>;
export type ListExportsResponse422 = ResponseBodyOf<ListExportsResponses[422]>;

type CreateExportSpec = OperationOf<"create_export">;
export type CreateExportOperation = CreateExportSpec;
export type CreateExportPathParams = Simplify<FieldOf<ParametersOf<CreateExportSpec>, "path">>;
export type CreateExportQueryParams = Simplify<FieldOf<ParametersOf<CreateExportSpec>, "query">>;
export type CreateExportHeaders = Simplify<FieldOf<ParametersOf<CreateExportSpec>, "header">>;
export type CreateExportRequestContentType = RequestContentTypesOf<CreateExportSpec>;
export type CreateExportRequestBody = RequestBodyOf<CreateExportSpec>;
export type CreateExportRequestBodyForContentType<TContentType extends CreateExportRequestContentType> = RequestBodyForContentType<CreateExportSpec, TContentType>;
export type CreateExportResponses = ResponsesOf<CreateExportSpec>;
/** Union of success response payloads for `create_export`. */
export type CreateExportSuccessData = ResponseDataOf<CreateExportResponses, SuccessStatusCodeOf<CreateExportResponses>>;
/** Union of non-success response payloads for `create_export`. */
export type CreateExportErrorData = ErrorDataOf<CreateExportResponses>;
export type CreateExportResponse201 = ResponseBodyOf<CreateExportResponses[201]>;
export type CreateExportResponse401 = ResponseBodyOf<CreateExportResponses[401]>;
export type CreateExportResponse403 = ResponseBodyOf<CreateExportResponses[403]>;
export type CreateExportResponse409 = ResponseBodyOf<CreateExportResponses[409]>;
export type CreateExportResponse422 = ResponseBodyOf<CreateExportResponses[422]>;
export type CreateExportResponse503 = ResponseBodyOf<CreateExportResponses[503]>;

type GetExportSpec = OperationOf<"get_export">;
export type GetExportOperation = GetExportSpec;
export type GetExportPathParams = Simplify<FieldOf<ParametersOf<GetExportSpec>, "path">>;
export type GetExportQueryParams = Simplify<FieldOf<ParametersOf<GetExportSpec>, "query">>;
export type GetExportHeaders = Simplify<FieldOf<ParametersOf<GetExportSpec>, "header">>;
export type GetExportRequestContentType = RequestContentTypesOf<GetExportSpec>;
export type GetExportRequestBody = RequestBodyOf<GetExportSpec>;
export type GetExportRequestBodyForContentType<TContentType extends GetExportRequestContentType> = RequestBodyForContentType<GetExportSpec, TContentType>;
export type GetExportResponses = ResponsesOf<GetExportSpec>;
/** Union of success response payloads for `get_export`. */
export type GetExportSuccessData = ResponseDataOf<GetExportResponses, SuccessStatusCodeOf<GetExportResponses>>;
/** Union of non-success response payloads for `get_export`. */
export type GetExportErrorData = ErrorDataOf<GetExportResponses>;
export type GetExportResponse200 = ResponseBodyOf<GetExportResponses[200]>;
export type GetExportResponse401 = ResponseBodyOf<GetExportResponses[401]>;
export type GetExportResponse403 = ResponseBodyOf<GetExportResponses[403]>;
export type GetExportResponse422 = ResponseBodyOf<GetExportResponses[422]>;

type CancelExportSpec = OperationOf<"cancel_export">;
export type CancelExportOperation = CancelExportSpec;
export type CancelExportPathParams = Simplify<FieldOf<ParametersOf<CancelExportSpec>, "path">>;
export type CancelExportQueryParams = Simplify<FieldOf<ParametersOf<CancelExportSpec>, "query">>;
export type CancelExportHeaders = Simplify<FieldOf<ParametersOf<CancelExportSpec>, "header">>;
export type CancelExportRequestContentType = RequestContentTypesOf<CancelExportSpec>;
export type CancelExportRequestBody = RequestBodyOf<CancelExportSpec>;
export type CancelExportRequestBodyForContentType<TContentType extends CancelExportRequestContentType> = RequestBodyForContentType<CancelExportSpec, TContentType>;
export type CancelExportResponses = ResponsesOf<CancelExportSpec>;
/** Union of success response payloads for `cancel_export`. */
export type CancelExportSuccessData = ResponseDataOf<CancelExportResponses, SuccessStatusCodeOf<CancelExportResponses>>;
/** Union of non-success response payloads for `cancel_export`. */
export type CancelExportErrorData = ErrorDataOf<CancelExportResponses>;
export type CancelExportResponse200 = ResponseBodyOf<CancelExportResponses[200]>;
export type CancelExportResponse401 = ResponseBodyOf<CancelExportResponses[401]>;
export type CancelExportResponse403 = ResponseBodyOf<CancelExportResponses[403]>;
export type CancelExportResponse422 = ResponseBodyOf<CancelExportResponses[422]>;

type HealthLiveSpec = OperationOf<"health_live">;
export type HealthLiveOperation = HealthLiveSpec;
export type HealthLivePathParams = Simplify<FieldOf<ParametersOf<HealthLiveSpec>, "path">>;
export type HealthLiveQueryParams = Simplify<FieldOf<ParametersOf<HealthLiveSpec>, "query">>;
export type HealthLiveHeaders = Simplify<FieldOf<ParametersOf<HealthLiveSpec>, "header">>;
export type HealthLiveRequestContentType = RequestContentTypesOf<HealthLiveSpec>;
export type HealthLiveRequestBody = RequestBodyOf<HealthLiveSpec>;
export type HealthLiveRequestBodyForContentType<TContentType extends HealthLiveRequestContentType> = RequestBodyForContentType<HealthLiveSpec, TContentType>;
export type HealthLiveResponses = ResponsesOf<HealthLiveSpec>;
/** Union of success response payloads for `health_live`. */
export type HealthLiveSuccessData = ResponseDataOf<HealthLiveResponses, SuccessStatusCodeOf<HealthLiveResponses>>;
/** Union of non-success response payloads for `health_live`. */
export type HealthLiveErrorData = ErrorDataOf<HealthLiveResponses>;
export type HealthLiveResponse200 = ResponseBodyOf<HealthLiveResponses[200]>;

type HealthReadySpec = OperationOf<"health_ready">;
export type HealthReadyOperation = HealthReadySpec;
export type HealthReadyPathParams = Simplify<FieldOf<ParametersOf<HealthReadySpec>, "path">>;
export type HealthReadyQueryParams = Simplify<FieldOf<ParametersOf<HealthReadySpec>, "query">>;
export type HealthReadyHeaders = Simplify<FieldOf<ParametersOf<HealthReadySpec>, "header">>;
export type HealthReadyRequestContentType = RequestContentTypesOf<HealthReadySpec>;
export type HealthReadyRequestBody = RequestBodyOf<HealthReadySpec>;
export type HealthReadyRequestBodyForContentType<TContentType extends HealthReadyRequestContentType> = RequestBodyForContentType<HealthReadySpec, TContentType>;
export type HealthReadyResponses = ResponsesOf<HealthReadySpec>;
/** Union of success response payloads for `health_ready`. */
export type HealthReadySuccessData = ResponseDataOf<HealthReadyResponses, SuccessStatusCodeOf<HealthReadyResponses>>;
/** Union of non-success response payloads for `health_ready`. */
export type HealthReadyErrorData = ErrorDataOf<HealthReadyResponses>;
export type HealthReadyResponse200 = ResponseBodyOf<HealthReadyResponses[200]>;
export type HealthReadyResponse503 = ResponseBodyOf<HealthReadyResponses[503]>;

type GetReleaseInfoSpec = OperationOf<"get_release_info">;
export type GetReleaseInfoOperation = GetReleaseInfoSpec;
export type GetReleaseInfoPathParams = Simplify<FieldOf<ParametersOf<GetReleaseInfoSpec>, "path">>;
export type GetReleaseInfoQueryParams = Simplify<FieldOf<ParametersOf<GetReleaseInfoSpec>, "query">>;
export type GetReleaseInfoHeaders = Simplify<FieldOf<ParametersOf<GetReleaseInfoSpec>, "header">>;
export type GetReleaseInfoRequestContentType = RequestContentTypesOf<GetReleaseInfoSpec>;
export type GetReleaseInfoRequestBody = RequestBodyOf<GetReleaseInfoSpec>;
export type GetReleaseInfoRequestBodyForContentType<TContentType extends GetReleaseInfoRequestContentType> = RequestBodyForContentType<GetReleaseInfoSpec, TContentType>;
export type GetReleaseInfoResponses = ResponsesOf<GetReleaseInfoSpec>;
/** Union of success response payloads for `get_release_info`. */
export type GetReleaseInfoSuccessData = ResponseDataOf<GetReleaseInfoResponses, SuccessStatusCodeOf<GetReleaseInfoResponses>>;
/** Union of non-success response payloads for `get_release_info`. */
export type GetReleaseInfoErrorData = ErrorDataOf<GetReleaseInfoResponses>;
export type GetReleaseInfoResponse200 = ResponseBodyOf<GetReleaseInfoResponses[200]>;

type PlanResourcesSpec = OperationOf<"plan_resources">;
export type PlanResourcesOperation = PlanResourcesSpec;
export type PlanResourcesPathParams = Simplify<FieldOf<ParametersOf<PlanResourcesSpec>, "path">>;
export type PlanResourcesQueryParams = Simplify<FieldOf<ParametersOf<PlanResourcesSpec>, "query">>;
export type PlanResourcesHeaders = Simplify<FieldOf<ParametersOf<PlanResourcesSpec>, "header">>;
export type PlanResourcesRequestContentType = RequestContentTypesOf<PlanResourcesSpec>;
export type PlanResourcesRequestBody = RequestBodyOf<PlanResourcesSpec>;
export type PlanResourcesRequestBodyForContentType<TContentType extends PlanResourcesRequestContentType> = RequestBodyForContentType<PlanResourcesSpec, TContentType>;
export type PlanResourcesResponses = ResponsesOf<PlanResourcesSpec>;
/** Union of success response payloads for `plan_resources`. */
export type PlanResourcesSuccessData = ResponseDataOf<PlanResourcesResponses, SuccessStatusCodeOf<PlanResourcesResponses>>;
/** Union of non-success response payloads for `plan_resources`. */
export type PlanResourcesErrorData = ErrorDataOf<PlanResourcesResponses>;
export type PlanResourcesResponse200 = ResponseBodyOf<PlanResourcesResponses[200]>;
export type PlanResourcesResponse422 = ResponseBodyOf<PlanResourcesResponses[422]>;

type PresignDownloadSpec = OperationOf<"presign_download">;
export type PresignDownloadOperation = PresignDownloadSpec;
export type PresignDownloadPathParams = Simplify<FieldOf<ParametersOf<PresignDownloadSpec>, "path">>;
export type PresignDownloadQueryParams = Simplify<FieldOf<ParametersOf<PresignDownloadSpec>, "query">>;
export type PresignDownloadHeaders = Simplify<FieldOf<ParametersOf<PresignDownloadSpec>, "header">>;
export type PresignDownloadRequestContentType = RequestContentTypesOf<PresignDownloadSpec>;
export type PresignDownloadRequestBody = RequestBodyOf<PresignDownloadSpec>;
export type PresignDownloadRequestBodyForContentType<TContentType extends PresignDownloadRequestContentType> = RequestBodyForContentType<PresignDownloadSpec, TContentType>;
export type PresignDownloadResponses = ResponsesOf<PresignDownloadSpec>;
/** Union of success response payloads for `presign_download`. */
export type PresignDownloadSuccessData = ResponseDataOf<PresignDownloadResponses, SuccessStatusCodeOf<PresignDownloadResponses>>;
/** Union of non-success response payloads for `presign_download`. */
export type PresignDownloadErrorData = ErrorDataOf<PresignDownloadResponses>;
export type PresignDownloadResponse200 = ResponseBodyOf<PresignDownloadResponses[200]>;
export type PresignDownloadResponse401 = ResponseBodyOf<PresignDownloadResponses[401]>;
export type PresignDownloadResponse403 = ResponseBodyOf<PresignDownloadResponses[403]>;
export type PresignDownloadResponse422 = ResponseBodyOf<PresignDownloadResponses[422]>;

type AbortUploadSpec = OperationOf<"abort_upload">;
export type AbortUploadOperation = AbortUploadSpec;
export type AbortUploadPathParams = Simplify<FieldOf<ParametersOf<AbortUploadSpec>, "path">>;
export type AbortUploadQueryParams = Simplify<FieldOf<ParametersOf<AbortUploadSpec>, "query">>;
export type AbortUploadHeaders = Simplify<FieldOf<ParametersOf<AbortUploadSpec>, "header">>;
export type AbortUploadRequestContentType = RequestContentTypesOf<AbortUploadSpec>;
export type AbortUploadRequestBody = RequestBodyOf<AbortUploadSpec>;
export type AbortUploadRequestBodyForContentType<TContentType extends AbortUploadRequestContentType> = RequestBodyForContentType<AbortUploadSpec, TContentType>;
export type AbortUploadResponses = ResponsesOf<AbortUploadSpec>;
/** Union of success response payloads for `abort_upload`. */
export type AbortUploadSuccessData = ResponseDataOf<AbortUploadResponses, SuccessStatusCodeOf<AbortUploadResponses>>;
/** Union of non-success response payloads for `abort_upload`. */
export type AbortUploadErrorData = ErrorDataOf<AbortUploadResponses>;
export type AbortUploadResponse200 = ResponseBodyOf<AbortUploadResponses[200]>;
export type AbortUploadResponse401 = ResponseBodyOf<AbortUploadResponses[401]>;
export type AbortUploadResponse403 = ResponseBodyOf<AbortUploadResponses[403]>;
export type AbortUploadResponse422 = ResponseBodyOf<AbortUploadResponses[422]>;

type CompleteUploadSpec = OperationOf<"complete_upload">;
export type CompleteUploadOperation = CompleteUploadSpec;
export type CompleteUploadPathParams = Simplify<FieldOf<ParametersOf<CompleteUploadSpec>, "path">>;
export type CompleteUploadQueryParams = Simplify<FieldOf<ParametersOf<CompleteUploadSpec>, "query">>;
export type CompleteUploadHeaders = Simplify<FieldOf<ParametersOf<CompleteUploadSpec>, "header">>;
export type CompleteUploadRequestContentType = RequestContentTypesOf<CompleteUploadSpec>;
export type CompleteUploadRequestBody = RequestBodyOf<CompleteUploadSpec>;
export type CompleteUploadRequestBodyForContentType<TContentType extends CompleteUploadRequestContentType> = RequestBodyForContentType<CompleteUploadSpec, TContentType>;
export type CompleteUploadResponses = ResponsesOf<CompleteUploadSpec>;
/** Union of success response payloads for `complete_upload`. */
export type CompleteUploadSuccessData = ResponseDataOf<CompleteUploadResponses, SuccessStatusCodeOf<CompleteUploadResponses>>;
/** Union of non-success response payloads for `complete_upload`. */
export type CompleteUploadErrorData = ErrorDataOf<CompleteUploadResponses>;
export type CompleteUploadResponse200 = ResponseBodyOf<CompleteUploadResponses[200]>;
export type CompleteUploadResponse401 = ResponseBodyOf<CompleteUploadResponses[401]>;
export type CompleteUploadResponse403 = ResponseBodyOf<CompleteUploadResponses[403]>;
export type CompleteUploadResponse422 = ResponseBodyOf<CompleteUploadResponses[422]>;

type InitiateUploadSpec = OperationOf<"initiate_upload">;
export type InitiateUploadOperation = InitiateUploadSpec;
export type InitiateUploadPathParams = Simplify<FieldOf<ParametersOf<InitiateUploadSpec>, "path">>;
export type InitiateUploadQueryParams = Simplify<FieldOf<ParametersOf<InitiateUploadSpec>, "query">>;
export type InitiateUploadHeaders = Simplify<FieldOf<ParametersOf<InitiateUploadSpec>, "header">>;
export type InitiateUploadRequestContentType = RequestContentTypesOf<InitiateUploadSpec>;
export type InitiateUploadRequestBody = RequestBodyOf<InitiateUploadSpec>;
export type InitiateUploadRequestBodyForContentType<TContentType extends InitiateUploadRequestContentType> = RequestBodyForContentType<InitiateUploadSpec, TContentType>;
export type InitiateUploadResponses = ResponsesOf<InitiateUploadSpec>;
/** Union of success response payloads for `initiate_upload`. */
export type InitiateUploadSuccessData = ResponseDataOf<InitiateUploadResponses, SuccessStatusCodeOf<InitiateUploadResponses>>;
/** Union of non-success response payloads for `initiate_upload`. */
export type InitiateUploadErrorData = ErrorDataOf<InitiateUploadResponses>;
export type InitiateUploadResponse200 = ResponseBodyOf<InitiateUploadResponses[200]>;
export type InitiateUploadResponse401 = ResponseBodyOf<InitiateUploadResponses[401]>;
export type InitiateUploadResponse403 = ResponseBodyOf<InitiateUploadResponses[403]>;
export type InitiateUploadResponse409 = ResponseBodyOf<InitiateUploadResponses[409]>;
export type InitiateUploadResponse422 = ResponseBodyOf<InitiateUploadResponses[422]>;
export type InitiateUploadResponse503 = ResponseBodyOf<InitiateUploadResponses[503]>;

type IntrospectUploadSpec = OperationOf<"introspect_upload">;
export type IntrospectUploadOperation = IntrospectUploadSpec;
export type IntrospectUploadPathParams = Simplify<FieldOf<ParametersOf<IntrospectUploadSpec>, "path">>;
export type IntrospectUploadQueryParams = Simplify<FieldOf<ParametersOf<IntrospectUploadSpec>, "query">>;
export type IntrospectUploadHeaders = Simplify<FieldOf<ParametersOf<IntrospectUploadSpec>, "header">>;
export type IntrospectUploadRequestContentType = RequestContentTypesOf<IntrospectUploadSpec>;
export type IntrospectUploadRequestBody = RequestBodyOf<IntrospectUploadSpec>;
export type IntrospectUploadRequestBodyForContentType<TContentType extends IntrospectUploadRequestContentType> = RequestBodyForContentType<IntrospectUploadSpec, TContentType>;
export type IntrospectUploadResponses = ResponsesOf<IntrospectUploadSpec>;
/** Union of success response payloads for `introspect_upload`. */
export type IntrospectUploadSuccessData = ResponseDataOf<IntrospectUploadResponses, SuccessStatusCodeOf<IntrospectUploadResponses>>;
/** Union of non-success response payloads for `introspect_upload`. */
export type IntrospectUploadErrorData = ErrorDataOf<IntrospectUploadResponses>;
export type IntrospectUploadResponse200 = ResponseBodyOf<IntrospectUploadResponses[200]>;
export type IntrospectUploadResponse401 = ResponseBodyOf<IntrospectUploadResponses[401]>;
export type IntrospectUploadResponse403 = ResponseBodyOf<IntrospectUploadResponses[403]>;
export type IntrospectUploadResponse422 = ResponseBodyOf<IntrospectUploadResponses[422]>;

type SignUploadPartsSpec = OperationOf<"sign_upload_parts">;
export type SignUploadPartsOperation = SignUploadPartsSpec;
export type SignUploadPartsPathParams = Simplify<FieldOf<ParametersOf<SignUploadPartsSpec>, "path">>;
export type SignUploadPartsQueryParams = Simplify<FieldOf<ParametersOf<SignUploadPartsSpec>, "query">>;
export type SignUploadPartsHeaders = Simplify<FieldOf<ParametersOf<SignUploadPartsSpec>, "header">>;
export type SignUploadPartsRequestContentType = RequestContentTypesOf<SignUploadPartsSpec>;
export type SignUploadPartsRequestBody = RequestBodyOf<SignUploadPartsSpec>;
export type SignUploadPartsRequestBodyForContentType<TContentType extends SignUploadPartsRequestContentType> = RequestBodyForContentType<SignUploadPartsSpec, TContentType>;
export type SignUploadPartsResponses = ResponsesOf<SignUploadPartsSpec>;
/** Union of success response payloads for `sign_upload_parts`. */
export type SignUploadPartsSuccessData = ResponseDataOf<SignUploadPartsResponses, SuccessStatusCodeOf<SignUploadPartsResponses>>;
/** Union of non-success response payloads for `sign_upload_parts`. */
export type SignUploadPartsErrorData = ErrorDataOf<SignUploadPartsResponses>;
export type SignUploadPartsResponse200 = ResponseBodyOf<SignUploadPartsResponses[200]>;
export type SignUploadPartsResponse401 = ResponseBodyOf<SignUploadPartsResponses[401]>;
export type SignUploadPartsResponse403 = ResponseBodyOf<SignUploadPartsResponses[403]>;
export type SignUploadPartsResponse422 = ResponseBodyOf<SignUploadPartsResponses[422]>;
