// Code generated by scripts/release/generate_clients.py. DO NOT EDIT.

import type {
  components as GeneratedComponents,
  operations as GeneratedOperations,
} from "./generated/openapi.js";

type EmptyObject = Record<string, never>;
type SuccessStatus = 200 | 201 | 202 | 203 | 204 | 205 | 206 | 207 | 208 | 226;
type Simplify<T> = { [K in keyof T]: T[K] } & {};
type OperationOf<TId extends keyof GeneratedOperations> = GeneratedOperations[TId];
type ParametersOf<T> = T extends { parameters: infer TParameters } ? TParameters : EmptyObject;
type FieldOf<TParameters, TKey extends "query" | "header" | "path"> = TParameters extends { [K in TKey]?: infer TValue }
  ? [TValue] extends [never]
    ? EmptyObject
    : TValue
  : EmptyObject;
type ContentOf<TContent, TMediaType extends string> = TContent extends Record<PropertyKey, unknown>
  ? TMediaType extends keyof TContent
    ? TContent[TMediaType]
    : never
  : never;
type JsonContentOf<TContent> = TContent extends Record<PropertyKey, unknown>
  ? "application/json" extends keyof TContent
    ? TContent["application/json"]
    : null
  : null;
type RequestContentTypesOf<T> = T extends { requestBody: { content: infer TContent } }
  ? Extract<keyof TContent, string>
  : never;
type RequestBodyOf<T> = T extends { requestBody: { content: infer TContent } }
  ? ContentOf<TContent, RequestContentTypesOf<T>>
  : never;
type RequestBodyForContentType<T, TContentType extends string> = T extends { requestBody: { content: infer TContent } }
  ? ContentOf<TContent, TContentType>
  : never;
type ResponsesOf<T> = T extends { responses: infer TResponses } ? TResponses : EmptyObject;
type StatusCodeOf<TResponses> = Extract<keyof TResponses, number>;
type ResponseBodyOf<TEntry> = TEntry extends { content: infer TContent }
  ? JsonContentOf<TContent>
  : null;
type ResultForResponses<TResponses> = {
  [TStatus in StatusCodeOf<TResponses>]: {
    readonly status: TStatus;
    readonly ok: TStatus extends SuccessStatus ? true : false;
    readonly headers: Headers;
    readonly data: ResponseBodyOf<TResponses[TStatus]>;
  };
}[StatusCodeOf<TResponses>];

/** Named aliases for generated OpenAPI component schemas. */
export type AbortUploadRequest = GeneratedComponents["schemas"]["AbortUploadRequest"];
export type AbortUploadResponse = GeneratedComponents["schemas"]["AbortUploadResponse"];
export type CapabilitiesResponse = GeneratedComponents["schemas"]["CapabilitiesResponse"];
export type CapabilityDescriptor = GeneratedComponents["schemas"]["CapabilityDescriptor"];
export type CompleteUploadRequest = GeneratedComponents["schemas"]["CompleteUploadRequest"];
export type CompleteUploadResponse = GeneratedComponents["schemas"]["CompleteUploadResponse"];
export type CompletedPart = GeneratedComponents["schemas"]["CompletedPart"];
export type EnqueueJobRequest = GeneratedComponents["schemas"]["EnqueueJobRequest"];
export type EnqueueJobResponse = GeneratedComponents["schemas"]["EnqueueJobResponse"];
export type ErrorEnvelope = GeneratedComponents["schemas"]["ErrorEnvelope"];
export type HealthResponse = GeneratedComponents["schemas"]["HealthResponse"];
export type InitiateUploadRequest = GeneratedComponents["schemas"]["InitiateUploadRequest"];
export type InitiateUploadResponse = GeneratedComponents["schemas"]["InitiateUploadResponse"];
export type JobCancelResponse = GeneratedComponents["schemas"]["JobCancelResponse"];
export type JobEvent = GeneratedComponents["schemas"]["JobEvent"];
export type JobEventType = GeneratedComponents["schemas"]["JobEventType"];
export type JobEventsResponse = GeneratedComponents["schemas"]["JobEventsResponse"];
export type JobListResponse = GeneratedComponents["schemas"]["JobListResponse"];
export type JobRecord = GeneratedComponents["schemas"]["JobRecord"];
export type JobStatus = GeneratedComponents["schemas"]["JobStatus"];
export type JobStatusResponse = GeneratedComponents["schemas"]["JobStatusResponse"];
export type MetricsSummaryResponse = GeneratedComponents["schemas"]["MetricsSummaryResponse"];
export type PresignDownloadRequest = GeneratedComponents["schemas"]["PresignDownloadRequest"];
export type PresignDownloadResponse = GeneratedComponents["schemas"]["PresignDownloadResponse"];
export type ReadinessResponse = GeneratedComponents["schemas"]["ReadinessResponse"];
export type ReleaseInfoResponse = GeneratedComponents["schemas"]["ReleaseInfoResponse"];
export type ResourcePlanItem = GeneratedComponents["schemas"]["ResourcePlanItem"];
export type ResourcePlanRequest = GeneratedComponents["schemas"]["ResourcePlanRequest"];
export type ResourcePlanResponse = GeneratedComponents["schemas"]["ResourcePlanResponse"];
export type SignPartsRequest = GeneratedComponents["schemas"]["SignPartsRequest"];
export type SignPartsResponse = GeneratedComponents["schemas"]["SignPartsResponse"];
export type UploadStrategy = GeneratedComponents["schemas"]["UploadStrategy"];

/** Operation-specific request and response helpers. */

type MetricsSummarySpec = OperationOf<"metrics_summary">;
export type MetricsSummaryOperation = MetricsSummarySpec;
export type MetricsSummaryPathParams = Simplify<FieldOf<ParametersOf<MetricsSummarySpec>, "path">>;
export type MetricsSummaryQueryParams = Simplify<FieldOf<ParametersOf<MetricsSummarySpec>, "query">>;
export type MetricsSummaryHeaders = Simplify<FieldOf<ParametersOf<MetricsSummarySpec>, "header">>;
export type MetricsSummaryRequestContentType = RequestContentTypesOf<MetricsSummarySpec>;
export type MetricsSummaryRequestBody = RequestBodyOf<MetricsSummarySpec>;
export type MetricsSummaryRequestBodyForContentType<TContentType extends MetricsSummaryRequestContentType> = RequestBodyForContentType<MetricsSummarySpec, TContentType>;
export type MetricsSummaryResponses = ResponsesOf<MetricsSummarySpec>;
export type MetricsSummaryResult = ResultForResponses<MetricsSummaryResponses>;
export type MetricsSummaryResponseData = MetricsSummaryResult["data"];
export type MetricsSummarySuccessResult = Extract<MetricsSummaryResult, { ok: true }>;
export type MetricsSummaryErrorResult = Extract<MetricsSummaryResult, { ok: false }>;
export type MetricsSummarySuccessData = MetricsSummarySuccessResult["data"];
export type MetricsSummaryErrorData = MetricsSummaryErrorResult["data"];
export type MetricsSummaryResponse200 = ResponseBodyOf<MetricsSummaryResponses[200]>;
export type MetricsSummaryResponse401 = ResponseBodyOf<MetricsSummaryResponses[401]>;
export type MetricsSummaryResponse403 = ResponseBodyOf<MetricsSummaryResponses[403]>;
export interface MetricsSummaryRequestOptions {
  readonly signal?: AbortSignal;
}

type GetCapabilitiesSpec = OperationOf<"get_capabilities">;
export type GetCapabilitiesOperation = GetCapabilitiesSpec;
export type GetCapabilitiesPathParams = Simplify<FieldOf<ParametersOf<GetCapabilitiesSpec>, "path">>;
export type GetCapabilitiesQueryParams = Simplify<FieldOf<ParametersOf<GetCapabilitiesSpec>, "query">>;
export type GetCapabilitiesHeaders = Simplify<FieldOf<ParametersOf<GetCapabilitiesSpec>, "header">>;
export type GetCapabilitiesRequestContentType = RequestContentTypesOf<GetCapabilitiesSpec>;
export type GetCapabilitiesRequestBody = RequestBodyOf<GetCapabilitiesSpec>;
export type GetCapabilitiesRequestBodyForContentType<TContentType extends GetCapabilitiesRequestContentType> = RequestBodyForContentType<GetCapabilitiesSpec, TContentType>;
export type GetCapabilitiesResponses = ResponsesOf<GetCapabilitiesSpec>;
export type GetCapabilitiesResult = ResultForResponses<GetCapabilitiesResponses>;
export type GetCapabilitiesResponseData = GetCapabilitiesResult["data"];
export type GetCapabilitiesSuccessResult = Extract<GetCapabilitiesResult, { ok: true }>;
export type GetCapabilitiesErrorResult = Extract<GetCapabilitiesResult, { ok: false }>;
export type GetCapabilitiesSuccessData = GetCapabilitiesSuccessResult["data"];
export type GetCapabilitiesErrorData = GetCapabilitiesErrorResult["data"];
export type GetCapabilitiesResponse200 = ResponseBodyOf<GetCapabilitiesResponses[200]>;
export interface GetCapabilitiesRequestOptions {
  readonly signal?: AbortSignal;
}

type HealthLiveSpec = OperationOf<"health_live">;
export type HealthLiveOperation = HealthLiveSpec;
export type HealthLivePathParams = Simplify<FieldOf<ParametersOf<HealthLiveSpec>, "path">>;
export type HealthLiveQueryParams = Simplify<FieldOf<ParametersOf<HealthLiveSpec>, "query">>;
export type HealthLiveHeaders = Simplify<FieldOf<ParametersOf<HealthLiveSpec>, "header">>;
export type HealthLiveRequestContentType = RequestContentTypesOf<HealthLiveSpec>;
export type HealthLiveRequestBody = RequestBodyOf<HealthLiveSpec>;
export type HealthLiveRequestBodyForContentType<TContentType extends HealthLiveRequestContentType> = RequestBodyForContentType<HealthLiveSpec, TContentType>;
export type HealthLiveResponses = ResponsesOf<HealthLiveSpec>;
export type HealthLiveResult = ResultForResponses<HealthLiveResponses>;
export type HealthLiveResponseData = HealthLiveResult["data"];
export type HealthLiveSuccessResult = Extract<HealthLiveResult, { ok: true }>;
export type HealthLiveErrorResult = Extract<HealthLiveResult, { ok: false }>;
export type HealthLiveSuccessData = HealthLiveSuccessResult["data"];
export type HealthLiveErrorData = HealthLiveErrorResult["data"];
export type HealthLiveResponse200 = ResponseBodyOf<HealthLiveResponses[200]>;
export interface HealthLiveRequestOptions {
  readonly signal?: AbortSignal;
}

type HealthReadySpec = OperationOf<"health_ready">;
export type HealthReadyOperation = HealthReadySpec;
export type HealthReadyPathParams = Simplify<FieldOf<ParametersOf<HealthReadySpec>, "path">>;
export type HealthReadyQueryParams = Simplify<FieldOf<ParametersOf<HealthReadySpec>, "query">>;
export type HealthReadyHeaders = Simplify<FieldOf<ParametersOf<HealthReadySpec>, "header">>;
export type HealthReadyRequestContentType = RequestContentTypesOf<HealthReadySpec>;
export type HealthReadyRequestBody = RequestBodyOf<HealthReadySpec>;
export type HealthReadyRequestBodyForContentType<TContentType extends HealthReadyRequestContentType> = RequestBodyForContentType<HealthReadySpec, TContentType>;
export type HealthReadyResponses = ResponsesOf<HealthReadySpec>;
export type HealthReadyResult = ResultForResponses<HealthReadyResponses>;
export type HealthReadyResponseData = HealthReadyResult["data"];
export type HealthReadySuccessResult = Extract<HealthReadyResult, { ok: true }>;
export type HealthReadyErrorResult = Extract<HealthReadyResult, { ok: false }>;
export type HealthReadySuccessData = HealthReadySuccessResult["data"];
export type HealthReadyErrorData = HealthReadyErrorResult["data"];
export type HealthReadyResponse200 = ResponseBodyOf<HealthReadyResponses[200]>;
export type HealthReadyResponse503 = ResponseBodyOf<HealthReadyResponses[503]>;
export interface HealthReadyRequestOptions {
  readonly signal?: AbortSignal;
}

type ListJobsSpec = OperationOf<"list_jobs">;
export type ListJobsOperation = ListJobsSpec;
export type ListJobsPathParams = Simplify<FieldOf<ParametersOf<ListJobsSpec>, "path">>;
export type ListJobsQueryParams = Simplify<FieldOf<ParametersOf<ListJobsSpec>, "query">>;
export type ListJobsHeaders = Simplify<FieldOf<ParametersOf<ListJobsSpec>, "header">>;
export type ListJobsRequestContentType = RequestContentTypesOf<ListJobsSpec>;
export type ListJobsRequestBody = RequestBodyOf<ListJobsSpec>;
export type ListJobsRequestBodyForContentType<TContentType extends ListJobsRequestContentType> = RequestBodyForContentType<ListJobsSpec, TContentType>;
export type ListJobsResponses = ResponsesOf<ListJobsSpec>;
export type ListJobsResult = ResultForResponses<ListJobsResponses>;
export type ListJobsResponseData = ListJobsResult["data"];
export type ListJobsSuccessResult = Extract<ListJobsResult, { ok: true }>;
export type ListJobsErrorResult = Extract<ListJobsResult, { ok: false }>;
export type ListJobsSuccessData = ListJobsSuccessResult["data"];
export type ListJobsErrorData = ListJobsErrorResult["data"];
export type ListJobsResponse200 = ResponseBodyOf<ListJobsResponses[200]>;
export type ListJobsResponse401 = ResponseBodyOf<ListJobsResponses[401]>;
export type ListJobsResponse403 = ResponseBodyOf<ListJobsResponses[403]>;
export type ListJobsResponse422 = ResponseBodyOf<ListJobsResponses[422]>;
export interface ListJobsRequestOptions {
  readonly query?: ListJobsQueryParams;
  readonly signal?: AbortSignal;
}

type CreateJobSpec = OperationOf<"create_job">;
export type CreateJobOperation = CreateJobSpec;
export type CreateJobPathParams = Simplify<FieldOf<ParametersOf<CreateJobSpec>, "path">>;
export type CreateJobQueryParams = Simplify<FieldOf<ParametersOf<CreateJobSpec>, "query">>;
export type CreateJobHeaders = Simplify<FieldOf<ParametersOf<CreateJobSpec>, "header">>;
export type CreateJobRequestContentType = RequestContentTypesOf<CreateJobSpec>;
export type CreateJobRequestBody = RequestBodyOf<CreateJobSpec>;
export type CreateJobRequestBodyForContentType<TContentType extends CreateJobRequestContentType> = RequestBodyForContentType<CreateJobSpec, TContentType>;
export type CreateJobResponses = ResponsesOf<CreateJobSpec>;
export type CreateJobResult = ResultForResponses<CreateJobResponses>;
export type CreateJobResponseData = CreateJobResult["data"];
export type CreateJobSuccessResult = Extract<CreateJobResult, { ok: true }>;
export type CreateJobErrorResult = Extract<CreateJobResult, { ok: false }>;
export type CreateJobSuccessData = CreateJobSuccessResult["data"];
export type CreateJobErrorData = CreateJobErrorResult["data"];
export type CreateJobResponse200 = ResponseBodyOf<CreateJobResponses[200]>;
export type CreateJobResponse401 = ResponseBodyOf<CreateJobResponses[401]>;
export type CreateJobResponse403 = ResponseBodyOf<CreateJobResponses[403]>;
export type CreateJobResponse422 = ResponseBodyOf<CreateJobResponses[422]>;
export type CreateJobResponse503 = ResponseBodyOf<CreateJobResponses[503]>;
export interface CreateJobRequestOptions {
  readonly headers?: CreateJobHeaders;
  readonly signal?: AbortSignal;
  readonly body: CreateJobRequestBody;
}

type GetJobStatusSpec = OperationOf<"get_job_status">;
export type GetJobStatusOperation = GetJobStatusSpec;
export type GetJobStatusPathParams = Simplify<FieldOf<ParametersOf<GetJobStatusSpec>, "path">>;
export type GetJobStatusQueryParams = Simplify<FieldOf<ParametersOf<GetJobStatusSpec>, "query">>;
export type GetJobStatusHeaders = Simplify<FieldOf<ParametersOf<GetJobStatusSpec>, "header">>;
export type GetJobStatusRequestContentType = RequestContentTypesOf<GetJobStatusSpec>;
export type GetJobStatusRequestBody = RequestBodyOf<GetJobStatusSpec>;
export type GetJobStatusRequestBodyForContentType<TContentType extends GetJobStatusRequestContentType> = RequestBodyForContentType<GetJobStatusSpec, TContentType>;
export type GetJobStatusResponses = ResponsesOf<GetJobStatusSpec>;
export type GetJobStatusResult = ResultForResponses<GetJobStatusResponses>;
export type GetJobStatusResponseData = GetJobStatusResult["data"];
export type GetJobStatusSuccessResult = Extract<GetJobStatusResult, { ok: true }>;
export type GetJobStatusErrorResult = Extract<GetJobStatusResult, { ok: false }>;
export type GetJobStatusSuccessData = GetJobStatusSuccessResult["data"];
export type GetJobStatusErrorData = GetJobStatusErrorResult["data"];
export type GetJobStatusResponse200 = ResponseBodyOf<GetJobStatusResponses[200]>;
export type GetJobStatusResponse401 = ResponseBodyOf<GetJobStatusResponses[401]>;
export type GetJobStatusResponse403 = ResponseBodyOf<GetJobStatusResponses[403]>;
export type GetJobStatusResponse422 = ResponseBodyOf<GetJobStatusResponses[422]>;
export interface GetJobStatusRequestOptions {
  readonly pathParams: GetJobStatusPathParams;
  readonly signal?: AbortSignal;
}

type CancelJobSpec = OperationOf<"cancel_job">;
export type CancelJobOperation = CancelJobSpec;
export type CancelJobPathParams = Simplify<FieldOf<ParametersOf<CancelJobSpec>, "path">>;
export type CancelJobQueryParams = Simplify<FieldOf<ParametersOf<CancelJobSpec>, "query">>;
export type CancelJobHeaders = Simplify<FieldOf<ParametersOf<CancelJobSpec>, "header">>;
export type CancelJobRequestContentType = RequestContentTypesOf<CancelJobSpec>;
export type CancelJobRequestBody = RequestBodyOf<CancelJobSpec>;
export type CancelJobRequestBodyForContentType<TContentType extends CancelJobRequestContentType> = RequestBodyForContentType<CancelJobSpec, TContentType>;
export type CancelJobResponses = ResponsesOf<CancelJobSpec>;
export type CancelJobResult = ResultForResponses<CancelJobResponses>;
export type CancelJobResponseData = CancelJobResult["data"];
export type CancelJobSuccessResult = Extract<CancelJobResult, { ok: true }>;
export type CancelJobErrorResult = Extract<CancelJobResult, { ok: false }>;
export type CancelJobSuccessData = CancelJobSuccessResult["data"];
export type CancelJobErrorData = CancelJobErrorResult["data"];
export type CancelJobResponse200 = ResponseBodyOf<CancelJobResponses[200]>;
export type CancelJobResponse401 = ResponseBodyOf<CancelJobResponses[401]>;
export type CancelJobResponse403 = ResponseBodyOf<CancelJobResponses[403]>;
export type CancelJobResponse422 = ResponseBodyOf<CancelJobResponses[422]>;
export interface CancelJobRequestOptions {
  readonly pathParams: CancelJobPathParams;
  readonly signal?: AbortSignal;
}

type ListJobEventsSpec = OperationOf<"list_job_events">;
export type ListJobEventsOperation = ListJobEventsSpec;
export type ListJobEventsPathParams = Simplify<FieldOf<ParametersOf<ListJobEventsSpec>, "path">>;
export type ListJobEventsQueryParams = Simplify<FieldOf<ParametersOf<ListJobEventsSpec>, "query">>;
export type ListJobEventsHeaders = Simplify<FieldOf<ParametersOf<ListJobEventsSpec>, "header">>;
export type ListJobEventsRequestContentType = RequestContentTypesOf<ListJobEventsSpec>;
export type ListJobEventsRequestBody = RequestBodyOf<ListJobEventsSpec>;
export type ListJobEventsRequestBodyForContentType<TContentType extends ListJobEventsRequestContentType> = RequestBodyForContentType<ListJobEventsSpec, TContentType>;
export type ListJobEventsResponses = ResponsesOf<ListJobEventsSpec>;
export type ListJobEventsResult = ResultForResponses<ListJobEventsResponses>;
export type ListJobEventsResponseData = ListJobEventsResult["data"];
export type ListJobEventsSuccessResult = Extract<ListJobEventsResult, { ok: true }>;
export type ListJobEventsErrorResult = Extract<ListJobEventsResult, { ok: false }>;
export type ListJobEventsSuccessData = ListJobEventsSuccessResult["data"];
export type ListJobEventsErrorData = ListJobEventsErrorResult["data"];
export type ListJobEventsResponse200 = ResponseBodyOf<ListJobEventsResponses[200]>;
export type ListJobEventsResponse401 = ResponseBodyOf<ListJobEventsResponses[401]>;
export type ListJobEventsResponse403 = ResponseBodyOf<ListJobEventsResponses[403]>;
export type ListJobEventsResponse422 = ResponseBodyOf<ListJobEventsResponses[422]>;
export interface ListJobEventsRequestOptions {
  readonly pathParams: ListJobEventsPathParams;
  readonly signal?: AbortSignal;
}

type RetryJobSpec = OperationOf<"retry_job">;
export type RetryJobOperation = RetryJobSpec;
export type RetryJobPathParams = Simplify<FieldOf<ParametersOf<RetryJobSpec>, "path">>;
export type RetryJobQueryParams = Simplify<FieldOf<ParametersOf<RetryJobSpec>, "query">>;
export type RetryJobHeaders = Simplify<FieldOf<ParametersOf<RetryJobSpec>, "header">>;
export type RetryJobRequestContentType = RequestContentTypesOf<RetryJobSpec>;
export type RetryJobRequestBody = RequestBodyOf<RetryJobSpec>;
export type RetryJobRequestBodyForContentType<TContentType extends RetryJobRequestContentType> = RequestBodyForContentType<RetryJobSpec, TContentType>;
export type RetryJobResponses = ResponsesOf<RetryJobSpec>;
export type RetryJobResult = ResultForResponses<RetryJobResponses>;
export type RetryJobResponseData = RetryJobResult["data"];
export type RetryJobSuccessResult = Extract<RetryJobResult, { ok: true }>;
export type RetryJobErrorResult = Extract<RetryJobResult, { ok: false }>;
export type RetryJobSuccessData = RetryJobSuccessResult["data"];
export type RetryJobErrorData = RetryJobErrorResult["data"];
export type RetryJobResponse200 = ResponseBodyOf<RetryJobResponses[200]>;
export type RetryJobResponse401 = ResponseBodyOf<RetryJobResponses[401]>;
export type RetryJobResponse403 = ResponseBodyOf<RetryJobResponses[403]>;
export type RetryJobResponse422 = ResponseBodyOf<RetryJobResponses[422]>;
export interface RetryJobRequestOptions {
  readonly pathParams: RetryJobPathParams;
  readonly signal?: AbortSignal;
}

type GetReleaseInfoSpec = OperationOf<"get_release_info">;
export type GetReleaseInfoOperation = GetReleaseInfoSpec;
export type GetReleaseInfoPathParams = Simplify<FieldOf<ParametersOf<GetReleaseInfoSpec>, "path">>;
export type GetReleaseInfoQueryParams = Simplify<FieldOf<ParametersOf<GetReleaseInfoSpec>, "query">>;
export type GetReleaseInfoHeaders = Simplify<FieldOf<ParametersOf<GetReleaseInfoSpec>, "header">>;
export type GetReleaseInfoRequestContentType = RequestContentTypesOf<GetReleaseInfoSpec>;
export type GetReleaseInfoRequestBody = RequestBodyOf<GetReleaseInfoSpec>;
export type GetReleaseInfoRequestBodyForContentType<TContentType extends GetReleaseInfoRequestContentType> = RequestBodyForContentType<GetReleaseInfoSpec, TContentType>;
export type GetReleaseInfoResponses = ResponsesOf<GetReleaseInfoSpec>;
export type GetReleaseInfoResult = ResultForResponses<GetReleaseInfoResponses>;
export type GetReleaseInfoResponseData = GetReleaseInfoResult["data"];
export type GetReleaseInfoSuccessResult = Extract<GetReleaseInfoResult, { ok: true }>;
export type GetReleaseInfoErrorResult = Extract<GetReleaseInfoResult, { ok: false }>;
export type GetReleaseInfoSuccessData = GetReleaseInfoSuccessResult["data"];
export type GetReleaseInfoErrorData = GetReleaseInfoErrorResult["data"];
export type GetReleaseInfoResponse200 = ResponseBodyOf<GetReleaseInfoResponses[200]>;
export interface GetReleaseInfoRequestOptions {
  readonly signal?: AbortSignal;
}

type PlanResourcesSpec = OperationOf<"plan_resources">;
export type PlanResourcesOperation = PlanResourcesSpec;
export type PlanResourcesPathParams = Simplify<FieldOf<ParametersOf<PlanResourcesSpec>, "path">>;
export type PlanResourcesQueryParams = Simplify<FieldOf<ParametersOf<PlanResourcesSpec>, "query">>;
export type PlanResourcesHeaders = Simplify<FieldOf<ParametersOf<PlanResourcesSpec>, "header">>;
export type PlanResourcesRequestContentType = RequestContentTypesOf<PlanResourcesSpec>;
export type PlanResourcesRequestBody = RequestBodyOf<PlanResourcesSpec>;
export type PlanResourcesRequestBodyForContentType<TContentType extends PlanResourcesRequestContentType> = RequestBodyForContentType<PlanResourcesSpec, TContentType>;
export type PlanResourcesResponses = ResponsesOf<PlanResourcesSpec>;
export type PlanResourcesResult = ResultForResponses<PlanResourcesResponses>;
export type PlanResourcesResponseData = PlanResourcesResult["data"];
export type PlanResourcesSuccessResult = Extract<PlanResourcesResult, { ok: true }>;
export type PlanResourcesErrorResult = Extract<PlanResourcesResult, { ok: false }>;
export type PlanResourcesSuccessData = PlanResourcesSuccessResult["data"];
export type PlanResourcesErrorData = PlanResourcesErrorResult["data"];
export type PlanResourcesResponse200 = ResponseBodyOf<PlanResourcesResponses[200]>;
export type PlanResourcesResponse422 = ResponseBodyOf<PlanResourcesResponses[422]>;
export interface PlanResourcesRequestOptions {
  readonly signal?: AbortSignal;
  readonly body: PlanResourcesRequestBody;
}

type PresignDownloadSpec = OperationOf<"presign_download">;
export type PresignDownloadOperation = PresignDownloadSpec;
export type PresignDownloadPathParams = Simplify<FieldOf<ParametersOf<PresignDownloadSpec>, "path">>;
export type PresignDownloadQueryParams = Simplify<FieldOf<ParametersOf<PresignDownloadSpec>, "query">>;
export type PresignDownloadHeaders = Simplify<FieldOf<ParametersOf<PresignDownloadSpec>, "header">>;
export type PresignDownloadRequestContentType = RequestContentTypesOf<PresignDownloadSpec>;
export type PresignDownloadRequestBody = RequestBodyOf<PresignDownloadSpec>;
export type PresignDownloadRequestBodyForContentType<TContentType extends PresignDownloadRequestContentType> = RequestBodyForContentType<PresignDownloadSpec, TContentType>;
export type PresignDownloadResponses = ResponsesOf<PresignDownloadSpec>;
export type PresignDownloadResult = ResultForResponses<PresignDownloadResponses>;
export type PresignDownloadResponseData = PresignDownloadResult["data"];
export type PresignDownloadSuccessResult = Extract<PresignDownloadResult, { ok: true }>;
export type PresignDownloadErrorResult = Extract<PresignDownloadResult, { ok: false }>;
export type PresignDownloadSuccessData = PresignDownloadSuccessResult["data"];
export type PresignDownloadErrorData = PresignDownloadErrorResult["data"];
export type PresignDownloadResponse200 = ResponseBodyOf<PresignDownloadResponses[200]>;
export type PresignDownloadResponse401 = ResponseBodyOf<PresignDownloadResponses[401]>;
export type PresignDownloadResponse403 = ResponseBodyOf<PresignDownloadResponses[403]>;
export type PresignDownloadResponse422 = ResponseBodyOf<PresignDownloadResponses[422]>;
export interface PresignDownloadRequestOptions {
  readonly signal?: AbortSignal;
  readonly body: PresignDownloadRequestBody;
}

type AbortUploadSpec = OperationOf<"abort_upload">;
export type AbortUploadOperation = AbortUploadSpec;
export type AbortUploadPathParams = Simplify<FieldOf<ParametersOf<AbortUploadSpec>, "path">>;
export type AbortUploadQueryParams = Simplify<FieldOf<ParametersOf<AbortUploadSpec>, "query">>;
export type AbortUploadHeaders = Simplify<FieldOf<ParametersOf<AbortUploadSpec>, "header">>;
export type AbortUploadRequestContentType = RequestContentTypesOf<AbortUploadSpec>;
export type AbortUploadRequestBody = RequestBodyOf<AbortUploadSpec>;
export type AbortUploadRequestBodyForContentType<TContentType extends AbortUploadRequestContentType> = RequestBodyForContentType<AbortUploadSpec, TContentType>;
export type AbortUploadResponses = ResponsesOf<AbortUploadSpec>;
export type AbortUploadResult = ResultForResponses<AbortUploadResponses>;
export type AbortUploadResponseData = AbortUploadResult["data"];
export type AbortUploadSuccessResult = Extract<AbortUploadResult, { ok: true }>;
export type AbortUploadErrorResult = Extract<AbortUploadResult, { ok: false }>;
export type AbortUploadSuccessData = AbortUploadSuccessResult["data"];
export type AbortUploadErrorData = AbortUploadErrorResult["data"];
export type AbortUploadResponse200 = ResponseBodyOf<AbortUploadResponses[200]>;
export type AbortUploadResponse401 = ResponseBodyOf<AbortUploadResponses[401]>;
export type AbortUploadResponse403 = ResponseBodyOf<AbortUploadResponses[403]>;
export type AbortUploadResponse422 = ResponseBodyOf<AbortUploadResponses[422]>;
export interface AbortUploadRequestOptions {
  readonly signal?: AbortSignal;
  readonly body: AbortUploadRequestBody;
}

type CompleteUploadSpec = OperationOf<"complete_upload">;
export type CompleteUploadOperation = CompleteUploadSpec;
export type CompleteUploadPathParams = Simplify<FieldOf<ParametersOf<CompleteUploadSpec>, "path">>;
export type CompleteUploadQueryParams = Simplify<FieldOf<ParametersOf<CompleteUploadSpec>, "query">>;
export type CompleteUploadHeaders = Simplify<FieldOf<ParametersOf<CompleteUploadSpec>, "header">>;
export type CompleteUploadRequestContentType = RequestContentTypesOf<CompleteUploadSpec>;
export type CompleteUploadRequestBody = RequestBodyOf<CompleteUploadSpec>;
export type CompleteUploadRequestBodyForContentType<TContentType extends CompleteUploadRequestContentType> = RequestBodyForContentType<CompleteUploadSpec, TContentType>;
export type CompleteUploadResponses = ResponsesOf<CompleteUploadSpec>;
export type CompleteUploadResult = ResultForResponses<CompleteUploadResponses>;
export type CompleteUploadResponseData = CompleteUploadResult["data"];
export type CompleteUploadSuccessResult = Extract<CompleteUploadResult, { ok: true }>;
export type CompleteUploadErrorResult = Extract<CompleteUploadResult, { ok: false }>;
export type CompleteUploadSuccessData = CompleteUploadSuccessResult["data"];
export type CompleteUploadErrorData = CompleteUploadErrorResult["data"];
export type CompleteUploadResponse200 = ResponseBodyOf<CompleteUploadResponses[200]>;
export type CompleteUploadResponse401 = ResponseBodyOf<CompleteUploadResponses[401]>;
export type CompleteUploadResponse403 = ResponseBodyOf<CompleteUploadResponses[403]>;
export type CompleteUploadResponse422 = ResponseBodyOf<CompleteUploadResponses[422]>;
export interface CompleteUploadRequestOptions {
  readonly signal?: AbortSignal;
  readonly body: CompleteUploadRequestBody;
}

type InitiateUploadSpec = OperationOf<"initiate_upload">;
export type InitiateUploadOperation = InitiateUploadSpec;
export type InitiateUploadPathParams = Simplify<FieldOf<ParametersOf<InitiateUploadSpec>, "path">>;
export type InitiateUploadQueryParams = Simplify<FieldOf<ParametersOf<InitiateUploadSpec>, "query">>;
export type InitiateUploadHeaders = Simplify<FieldOf<ParametersOf<InitiateUploadSpec>, "header">>;
export type InitiateUploadRequestContentType = RequestContentTypesOf<InitiateUploadSpec>;
export type InitiateUploadRequestBody = RequestBodyOf<InitiateUploadSpec>;
export type InitiateUploadRequestBodyForContentType<TContentType extends InitiateUploadRequestContentType> = RequestBodyForContentType<InitiateUploadSpec, TContentType>;
export type InitiateUploadResponses = ResponsesOf<InitiateUploadSpec>;
export type InitiateUploadResult = ResultForResponses<InitiateUploadResponses>;
export type InitiateUploadResponseData = InitiateUploadResult["data"];
export type InitiateUploadSuccessResult = Extract<InitiateUploadResult, { ok: true }>;
export type InitiateUploadErrorResult = Extract<InitiateUploadResult, { ok: false }>;
export type InitiateUploadSuccessData = InitiateUploadSuccessResult["data"];
export type InitiateUploadErrorData = InitiateUploadErrorResult["data"];
export type InitiateUploadResponse200 = ResponseBodyOf<InitiateUploadResponses[200]>;
export type InitiateUploadResponse401 = ResponseBodyOf<InitiateUploadResponses[401]>;
export type InitiateUploadResponse403 = ResponseBodyOf<InitiateUploadResponses[403]>;
export type InitiateUploadResponse409 = ResponseBodyOf<InitiateUploadResponses[409]>;
export type InitiateUploadResponse422 = ResponseBodyOf<InitiateUploadResponses[422]>;
export type InitiateUploadResponse503 = ResponseBodyOf<InitiateUploadResponses[503]>;
export interface InitiateUploadRequestOptions {
  readonly headers?: InitiateUploadHeaders;
  readonly signal?: AbortSignal;
  readonly body: InitiateUploadRequestBody;
}

type SignUploadPartsSpec = OperationOf<"sign_upload_parts">;
export type SignUploadPartsOperation = SignUploadPartsSpec;
export type SignUploadPartsPathParams = Simplify<FieldOf<ParametersOf<SignUploadPartsSpec>, "path">>;
export type SignUploadPartsQueryParams = Simplify<FieldOf<ParametersOf<SignUploadPartsSpec>, "query">>;
export type SignUploadPartsHeaders = Simplify<FieldOf<ParametersOf<SignUploadPartsSpec>, "header">>;
export type SignUploadPartsRequestContentType = RequestContentTypesOf<SignUploadPartsSpec>;
export type SignUploadPartsRequestBody = RequestBodyOf<SignUploadPartsSpec>;
export type SignUploadPartsRequestBodyForContentType<TContentType extends SignUploadPartsRequestContentType> = RequestBodyForContentType<SignUploadPartsSpec, TContentType>;
export type SignUploadPartsResponses = ResponsesOf<SignUploadPartsSpec>;
export type SignUploadPartsResult = ResultForResponses<SignUploadPartsResponses>;
export type SignUploadPartsResponseData = SignUploadPartsResult["data"];
export type SignUploadPartsSuccessResult = Extract<SignUploadPartsResult, { ok: true }>;
export type SignUploadPartsErrorResult = Extract<SignUploadPartsResult, { ok: false }>;
export type SignUploadPartsSuccessData = SignUploadPartsSuccessResult["data"];
export type SignUploadPartsErrorData = SignUploadPartsErrorResult["data"];
export type SignUploadPartsResponse200 = ResponseBodyOf<SignUploadPartsResponses[200]>;
export type SignUploadPartsResponse401 = ResponseBodyOf<SignUploadPartsResponses[401]>;
export type SignUploadPartsResponse403 = ResponseBodyOf<SignUploadPartsResponses[403]>;
export type SignUploadPartsResponse422 = ResponseBodyOf<SignUploadPartsResponses[422]>;
export interface SignUploadPartsRequestOptions {
  readonly signal?: AbortSignal;
  readonly body: SignUploadPartsRequestBody;
}
