// Code generated by scripts/release/generate_clients.py. DO NOT EDIT.

import type {
  components as GeneratedComponents,
  operations as GeneratedOperations,
} from "./generated/openapi.js";

type EmptyObject = Record<string, never>;
type SuccessStatus = 200 | 201 | 202 | 203 | 204 | 205 | 206 | 207 | 208 | 226;
type Simplify<T> = { [K in keyof T]: T[K] } & {};
type OperationOf<TId extends keyof GeneratedOperations> = GeneratedOperations[TId];
type ParametersOf<T> = T extends { parameters: infer TParameters } ? TParameters : EmptyObject;
type FieldOf<TParameters, TKey extends "query" | "header" | "path"> = TParameters extends { [K in TKey]?: infer TValue }
  ? [TValue] extends [never]
    ? EmptyObject
    : TValue
  : EmptyObject;
type ContentOf<TContent, TMediaType extends string> = TContent extends Record<PropertyKey, unknown>
  ? TMediaType extends keyof TContent
    ? TContent[TMediaType]
    : never
  : never;
type JsonContentOf<TContent> = TContent extends Record<PropertyKey, unknown>
  ? "application/json" extends keyof TContent
    ? TContent["application/json"]
    : null
  : null;
type RequestContentTypesOf<T> = T extends { requestBody: { content: infer TContent } }
  ? Extract<keyof TContent, string>
  : never;
type RequestBodyOf<T> = T extends { requestBody: { content: infer TContent } }
  ? ContentOf<TContent, RequestContentTypesOf<T>>
  : never;
type RequestBodyForContentType<T, TContentType extends string> = T extends { requestBody: { content: infer TContent } }
  ? ContentOf<TContent, TContentType>
  : never;
type ResponsesOf<T> = T extends { responses: infer TResponses } ? TResponses : EmptyObject;
type StatusCodeOf<TResponses> = Extract<keyof TResponses, number>;
type SuccessStatusCodeOf<TResponses> = Extract<StatusCodeOf<TResponses>, SuccessStatus>;
type ErrorStatusCodeOf<TResponses> = Exclude<StatusCodeOf<TResponses>, SuccessStatus>;
type ResponseBodyOf<TEntry> = TEntry extends { content: infer TContent }
  ? JsonContentOf<TContent>
  : null;
type ResponseDataOf<TResponses, TStatusCodes extends number> = TStatusCodes extends StatusCodeOf<TResponses>
  ? ResponseBodyOf<TResponses[TStatusCodes]>
  : never;

/** Named aliases for generated OpenAPI component schemas. */
/** OpenAPI component schema `AbortUploadRequest`. */
export type AbortUploadRequest = GeneratedComponents["schemas"]["AbortUploadRequest"];
/** OpenAPI component schema `AbortUploadResponse`. */
export type AbortUploadResponse = GeneratedComponents["schemas"]["AbortUploadResponse"];
/** OpenAPI component schema `CapabilitiesResponse`. */
export type CapabilitiesResponse = GeneratedComponents["schemas"]["CapabilitiesResponse"];
/** OpenAPI component schema `CapabilityDescriptor`. */
export type CapabilityDescriptor = GeneratedComponents["schemas"]["CapabilityDescriptor"];
/** OpenAPI component schema `CompleteUploadRequest`. */
export type CompleteUploadRequest = GeneratedComponents["schemas"]["CompleteUploadRequest"];
/** OpenAPI component schema `CompleteUploadResponse`. */
export type CompleteUploadResponse = GeneratedComponents["schemas"]["CompleteUploadResponse"];
/** OpenAPI component schema `CompletedPart`. */
export type CompletedPart = GeneratedComponents["schemas"]["CompletedPart"];
/** OpenAPI component schema `EnqueueJobRequest`. */
export type EnqueueJobRequest = GeneratedComponents["schemas"]["EnqueueJobRequest"];
/** OpenAPI component schema `EnqueueJobResponse`. */
export type EnqueueJobResponse = GeneratedComponents["schemas"]["EnqueueJobResponse"];
/** OpenAPI component schema `ErrorBody`. */
export type ErrorBody = GeneratedComponents["schemas"]["ErrorBody"];
/** OpenAPI component schema `ErrorEnvelope`. */
export type ErrorEnvelope = GeneratedComponents["schemas"]["ErrorEnvelope"];
/** OpenAPI component schema `HealthResponse`. */
export type HealthResponse = GeneratedComponents["schemas"]["HealthResponse"];
/** OpenAPI component schema `InitiateUploadRequest`. */
export type InitiateUploadRequest = GeneratedComponents["schemas"]["InitiateUploadRequest"];
/** OpenAPI component schema `InitiateUploadResponse`. */
export type InitiateUploadResponse = GeneratedComponents["schemas"]["InitiateUploadResponse"];
/** OpenAPI component schema `JobCancelResponse`. */
export type JobCancelResponse = GeneratedComponents["schemas"]["JobCancelResponse"];
/** OpenAPI component schema `JobEvent`. */
export type JobEvent = GeneratedComponents["schemas"]["JobEvent"];
/** OpenAPI component schema `JobEventType`. */
export type JobEventType = GeneratedComponents["schemas"]["JobEventType"];
/** OpenAPI component schema `JobEventsResponse`. */
export type JobEventsResponse = GeneratedComponents["schemas"]["JobEventsResponse"];
/** OpenAPI component schema `JobListResponse`. */
export type JobListResponse = GeneratedComponents["schemas"]["JobListResponse"];
/** OpenAPI component schema `JobRecord`. */
export type JobRecord = GeneratedComponents["schemas"]["JobRecord"];
/** OpenAPI component schema `JobStatus`. */
export type JobStatus = GeneratedComponents["schemas"]["JobStatus"];
/** OpenAPI component schema `JobStatusResponse`. */
export type JobStatusResponse = GeneratedComponents["schemas"]["JobStatusResponse"];
/** OpenAPI component schema `MetricsSummaryResponse`. */
export type MetricsSummaryResponse = GeneratedComponents["schemas"]["MetricsSummaryResponse"];
/** OpenAPI component schema `PresignDownloadRequest`. */
export type PresignDownloadRequest = GeneratedComponents["schemas"]["PresignDownloadRequest"];
/** OpenAPI component schema `PresignDownloadResponse`. */
export type PresignDownloadResponse = GeneratedComponents["schemas"]["PresignDownloadResponse"];
/** OpenAPI component schema `ReadinessResponse`. */
export type ReadinessResponse = GeneratedComponents["schemas"]["ReadinessResponse"];
/** OpenAPI component schema `ReleaseInfoResponse`. */
export type ReleaseInfoResponse = GeneratedComponents["schemas"]["ReleaseInfoResponse"];
/** OpenAPI component schema `ResourcePlanItem`. */
export type ResourcePlanItem = GeneratedComponents["schemas"]["ResourcePlanItem"];
/** OpenAPI component schema `ResourcePlanRequest`. */
export type ResourcePlanRequest = GeneratedComponents["schemas"]["ResourcePlanRequest"];
/** OpenAPI component schema `ResourcePlanResponse`. */
export type ResourcePlanResponse = GeneratedComponents["schemas"]["ResourcePlanResponse"];
/** OpenAPI component schema `SignPartsRequest`. */
export type SignPartsRequest = GeneratedComponents["schemas"]["SignPartsRequest"];
/** OpenAPI component schema `SignPartsResponse`. */
export type SignPartsResponse = GeneratedComponents["schemas"]["SignPartsResponse"];
/** OpenAPI component schema `UploadIntrospectionRequest`. */
export type UploadIntrospectionRequest = GeneratedComponents["schemas"]["UploadIntrospectionRequest"];
/** OpenAPI component schema `UploadIntrospectionResponse`. */
export type UploadIntrospectionResponse = GeneratedComponents["schemas"]["UploadIntrospectionResponse"];
/** OpenAPI component schema `UploadStrategy`. */
export type UploadStrategy = GeneratedComponents["schemas"]["UploadStrategy"];
/** OpenAPI component schema `UploadedPart`. */
export type UploadedPart = GeneratedComponents["schemas"]["UploadedPart"];

/** Operation-specific request and response helpers. */

type MetricsSummarySpec = OperationOf<"metrics_summary">;
export type MetricsSummaryOperation = MetricsSummarySpec;
export type MetricsSummaryPathParams = Simplify<FieldOf<ParametersOf<MetricsSummarySpec>, "path">>;
export type MetricsSummaryQueryParams = Simplify<FieldOf<ParametersOf<MetricsSummarySpec>, "query">>;
export type MetricsSummaryHeaders = Simplify<FieldOf<ParametersOf<MetricsSummarySpec>, "header">>;
export type MetricsSummaryRequestContentType = RequestContentTypesOf<MetricsSummarySpec>;
export type MetricsSummaryRequestBody = RequestBodyOf<MetricsSummarySpec>;
export type MetricsSummaryRequestBodyForContentType<TContentType extends MetricsSummaryRequestContentType> = RequestBodyForContentType<MetricsSummarySpec, TContentType>;
export type MetricsSummaryResponses = ResponsesOf<MetricsSummarySpec>;
export type MetricsSummarySuccessData = ResponseDataOf<MetricsSummaryResponses, SuccessStatusCodeOf<MetricsSummaryResponses>>;
export type MetricsSummaryErrorData = ResponseDataOf<MetricsSummaryResponses, ErrorStatusCodeOf<MetricsSummaryResponses>>;
export type MetricsSummaryResponse200 = ResponseBodyOf<MetricsSummaryResponses[200]>;
export type MetricsSummaryResponse401 = ResponseBodyOf<MetricsSummaryResponses[401]>;
export type MetricsSummaryResponse403 = ResponseBodyOf<MetricsSummaryResponses[403]>;

type GetCapabilitiesSpec = OperationOf<"get_capabilities">;
export type GetCapabilitiesOperation = GetCapabilitiesSpec;
export type GetCapabilitiesPathParams = Simplify<FieldOf<ParametersOf<GetCapabilitiesSpec>, "path">>;
export type GetCapabilitiesQueryParams = Simplify<FieldOf<ParametersOf<GetCapabilitiesSpec>, "query">>;
export type GetCapabilitiesHeaders = Simplify<FieldOf<ParametersOf<GetCapabilitiesSpec>, "header">>;
export type GetCapabilitiesRequestContentType = RequestContentTypesOf<GetCapabilitiesSpec>;
export type GetCapabilitiesRequestBody = RequestBodyOf<GetCapabilitiesSpec>;
export type GetCapabilitiesRequestBodyForContentType<TContentType extends GetCapabilitiesRequestContentType> = RequestBodyForContentType<GetCapabilitiesSpec, TContentType>;
export type GetCapabilitiesResponses = ResponsesOf<GetCapabilitiesSpec>;
export type GetCapabilitiesSuccessData = ResponseDataOf<GetCapabilitiesResponses, SuccessStatusCodeOf<GetCapabilitiesResponses>>;
export type GetCapabilitiesErrorData = ResponseDataOf<GetCapabilitiesResponses, ErrorStatusCodeOf<GetCapabilitiesResponses>>;
export type GetCapabilitiesResponse200 = ResponseBodyOf<GetCapabilitiesResponses[200]>;

type HealthLiveSpec = OperationOf<"health_live">;
export type HealthLiveOperation = HealthLiveSpec;
export type HealthLivePathParams = Simplify<FieldOf<ParametersOf<HealthLiveSpec>, "path">>;
export type HealthLiveQueryParams = Simplify<FieldOf<ParametersOf<HealthLiveSpec>, "query">>;
export type HealthLiveHeaders = Simplify<FieldOf<ParametersOf<HealthLiveSpec>, "header">>;
export type HealthLiveRequestContentType = RequestContentTypesOf<HealthLiveSpec>;
export type HealthLiveRequestBody = RequestBodyOf<HealthLiveSpec>;
export type HealthLiveRequestBodyForContentType<TContentType extends HealthLiveRequestContentType> = RequestBodyForContentType<HealthLiveSpec, TContentType>;
export type HealthLiveResponses = ResponsesOf<HealthLiveSpec>;
export type HealthLiveSuccessData = ResponseDataOf<HealthLiveResponses, SuccessStatusCodeOf<HealthLiveResponses>>;
export type HealthLiveErrorData = ResponseDataOf<HealthLiveResponses, ErrorStatusCodeOf<HealthLiveResponses>>;
export type HealthLiveResponse200 = ResponseBodyOf<HealthLiveResponses[200]>;

type HealthReadySpec = OperationOf<"health_ready">;
export type HealthReadyOperation = HealthReadySpec;
export type HealthReadyPathParams = Simplify<FieldOf<ParametersOf<HealthReadySpec>, "path">>;
export type HealthReadyQueryParams = Simplify<FieldOf<ParametersOf<HealthReadySpec>, "query">>;
export type HealthReadyHeaders = Simplify<FieldOf<ParametersOf<HealthReadySpec>, "header">>;
export type HealthReadyRequestContentType = RequestContentTypesOf<HealthReadySpec>;
export type HealthReadyRequestBody = RequestBodyOf<HealthReadySpec>;
export type HealthReadyRequestBodyForContentType<TContentType extends HealthReadyRequestContentType> = RequestBodyForContentType<HealthReadySpec, TContentType>;
export type HealthReadyResponses = ResponsesOf<HealthReadySpec>;
export type HealthReadySuccessData = ResponseDataOf<HealthReadyResponses, SuccessStatusCodeOf<HealthReadyResponses>>;
export type HealthReadyErrorData = ResponseDataOf<HealthReadyResponses, ErrorStatusCodeOf<HealthReadyResponses>>;
export type HealthReadyResponse200 = ResponseBodyOf<HealthReadyResponses[200]>;
export type HealthReadyResponse503 = ResponseBodyOf<HealthReadyResponses[503]>;

type ListJobsSpec = OperationOf<"list_jobs">;
export type ListJobsOperation = ListJobsSpec;
export type ListJobsPathParams = Simplify<FieldOf<ParametersOf<ListJobsSpec>, "path">>;
export type ListJobsQueryParams = Simplify<FieldOf<ParametersOf<ListJobsSpec>, "query">>;
export type ListJobsHeaders = Simplify<FieldOf<ParametersOf<ListJobsSpec>, "header">>;
export type ListJobsRequestContentType = RequestContentTypesOf<ListJobsSpec>;
export type ListJobsRequestBody = RequestBodyOf<ListJobsSpec>;
export type ListJobsRequestBodyForContentType<TContentType extends ListJobsRequestContentType> = RequestBodyForContentType<ListJobsSpec, TContentType>;
export type ListJobsResponses = ResponsesOf<ListJobsSpec>;
export type ListJobsSuccessData = ResponseDataOf<ListJobsResponses, SuccessStatusCodeOf<ListJobsResponses>>;
export type ListJobsErrorData = ResponseDataOf<ListJobsResponses, ErrorStatusCodeOf<ListJobsResponses>>;
export type ListJobsResponse200 = ResponseBodyOf<ListJobsResponses[200]>;
export type ListJobsResponse401 = ResponseBodyOf<ListJobsResponses[401]>;
export type ListJobsResponse403 = ResponseBodyOf<ListJobsResponses[403]>;
export type ListJobsResponse422 = ResponseBodyOf<ListJobsResponses[422]>;

type CreateJobSpec = OperationOf<"create_job">;
export type CreateJobOperation = CreateJobSpec;
export type CreateJobPathParams = Simplify<FieldOf<ParametersOf<CreateJobSpec>, "path">>;
export type CreateJobQueryParams = Simplify<FieldOf<ParametersOf<CreateJobSpec>, "query">>;
export type CreateJobHeaders = Simplify<FieldOf<ParametersOf<CreateJobSpec>, "header">>;
export type CreateJobRequestContentType = RequestContentTypesOf<CreateJobSpec>;
export type CreateJobRequestBody = RequestBodyOf<CreateJobSpec>;
export type CreateJobRequestBodyForContentType<TContentType extends CreateJobRequestContentType> = RequestBodyForContentType<CreateJobSpec, TContentType>;
export type CreateJobResponses = ResponsesOf<CreateJobSpec>;
export type CreateJobSuccessData = ResponseDataOf<CreateJobResponses, SuccessStatusCodeOf<CreateJobResponses>>;
export type CreateJobErrorData = ResponseDataOf<CreateJobResponses, ErrorStatusCodeOf<CreateJobResponses>>;
export type CreateJobResponse200 = ResponseBodyOf<CreateJobResponses[200]>;
export type CreateJobResponse401 = ResponseBodyOf<CreateJobResponses[401]>;
export type CreateJobResponse403 = ResponseBodyOf<CreateJobResponses[403]>;
export type CreateJobResponse409 = ResponseBodyOf<CreateJobResponses[409]>;
export type CreateJobResponse422 = ResponseBodyOf<CreateJobResponses[422]>;
export type CreateJobResponse503 = ResponseBodyOf<CreateJobResponses[503]>;

type GetJobStatusSpec = OperationOf<"get_job_status">;
export type GetJobStatusOperation = GetJobStatusSpec;
export type GetJobStatusPathParams = Simplify<FieldOf<ParametersOf<GetJobStatusSpec>, "path">>;
export type GetJobStatusQueryParams = Simplify<FieldOf<ParametersOf<GetJobStatusSpec>, "query">>;
export type GetJobStatusHeaders = Simplify<FieldOf<ParametersOf<GetJobStatusSpec>, "header">>;
export type GetJobStatusRequestContentType = RequestContentTypesOf<GetJobStatusSpec>;
export type GetJobStatusRequestBody = RequestBodyOf<GetJobStatusSpec>;
export type GetJobStatusRequestBodyForContentType<TContentType extends GetJobStatusRequestContentType> = RequestBodyForContentType<GetJobStatusSpec, TContentType>;
export type GetJobStatusResponses = ResponsesOf<GetJobStatusSpec>;
export type GetJobStatusSuccessData = ResponseDataOf<GetJobStatusResponses, SuccessStatusCodeOf<GetJobStatusResponses>>;
export type GetJobStatusErrorData = ResponseDataOf<GetJobStatusResponses, ErrorStatusCodeOf<GetJobStatusResponses>>;
export type GetJobStatusResponse200 = ResponseBodyOf<GetJobStatusResponses[200]>;
export type GetJobStatusResponse401 = ResponseBodyOf<GetJobStatusResponses[401]>;
export type GetJobStatusResponse403 = ResponseBodyOf<GetJobStatusResponses[403]>;
export type GetJobStatusResponse422 = ResponseBodyOf<GetJobStatusResponses[422]>;

type CancelJobSpec = OperationOf<"cancel_job">;
export type CancelJobOperation = CancelJobSpec;
export type CancelJobPathParams = Simplify<FieldOf<ParametersOf<CancelJobSpec>, "path">>;
export type CancelJobQueryParams = Simplify<FieldOf<ParametersOf<CancelJobSpec>, "query">>;
export type CancelJobHeaders = Simplify<FieldOf<ParametersOf<CancelJobSpec>, "header">>;
export type CancelJobRequestContentType = RequestContentTypesOf<CancelJobSpec>;
export type CancelJobRequestBody = RequestBodyOf<CancelJobSpec>;
export type CancelJobRequestBodyForContentType<TContentType extends CancelJobRequestContentType> = RequestBodyForContentType<CancelJobSpec, TContentType>;
export type CancelJobResponses = ResponsesOf<CancelJobSpec>;
export type CancelJobSuccessData = ResponseDataOf<CancelJobResponses, SuccessStatusCodeOf<CancelJobResponses>>;
export type CancelJobErrorData = ResponseDataOf<CancelJobResponses, ErrorStatusCodeOf<CancelJobResponses>>;
export type CancelJobResponse200 = ResponseBodyOf<CancelJobResponses[200]>;
export type CancelJobResponse401 = ResponseBodyOf<CancelJobResponses[401]>;
export type CancelJobResponse403 = ResponseBodyOf<CancelJobResponses[403]>;
export type CancelJobResponse422 = ResponseBodyOf<CancelJobResponses[422]>;

type ListJobEventsSpec = OperationOf<"list_job_events">;
export type ListJobEventsOperation = ListJobEventsSpec;
export type ListJobEventsPathParams = Simplify<FieldOf<ParametersOf<ListJobEventsSpec>, "path">>;
export type ListJobEventsQueryParams = Simplify<FieldOf<ParametersOf<ListJobEventsSpec>, "query">>;
export type ListJobEventsHeaders = Simplify<FieldOf<ParametersOf<ListJobEventsSpec>, "header">>;
export type ListJobEventsRequestContentType = RequestContentTypesOf<ListJobEventsSpec>;
export type ListJobEventsRequestBody = RequestBodyOf<ListJobEventsSpec>;
export type ListJobEventsRequestBodyForContentType<TContentType extends ListJobEventsRequestContentType> = RequestBodyForContentType<ListJobEventsSpec, TContentType>;
export type ListJobEventsResponses = ResponsesOf<ListJobEventsSpec>;
export type ListJobEventsSuccessData = ResponseDataOf<ListJobEventsResponses, SuccessStatusCodeOf<ListJobEventsResponses>>;
export type ListJobEventsErrorData = ResponseDataOf<ListJobEventsResponses, ErrorStatusCodeOf<ListJobEventsResponses>>;
export type ListJobEventsResponse200 = ResponseBodyOf<ListJobEventsResponses[200]>;
export type ListJobEventsResponse401 = ResponseBodyOf<ListJobEventsResponses[401]>;
export type ListJobEventsResponse403 = ResponseBodyOf<ListJobEventsResponses[403]>;
export type ListJobEventsResponse422 = ResponseBodyOf<ListJobEventsResponses[422]>;

type RetryJobSpec = OperationOf<"retry_job">;
export type RetryJobOperation = RetryJobSpec;
export type RetryJobPathParams = Simplify<FieldOf<ParametersOf<RetryJobSpec>, "path">>;
export type RetryJobQueryParams = Simplify<FieldOf<ParametersOf<RetryJobSpec>, "query">>;
export type RetryJobHeaders = Simplify<FieldOf<ParametersOf<RetryJobSpec>, "header">>;
export type RetryJobRequestContentType = RequestContentTypesOf<RetryJobSpec>;
export type RetryJobRequestBody = RequestBodyOf<RetryJobSpec>;
export type RetryJobRequestBodyForContentType<TContentType extends RetryJobRequestContentType> = RequestBodyForContentType<RetryJobSpec, TContentType>;
export type RetryJobResponses = ResponsesOf<RetryJobSpec>;
export type RetryJobSuccessData = ResponseDataOf<RetryJobResponses, SuccessStatusCodeOf<RetryJobResponses>>;
export type RetryJobErrorData = ResponseDataOf<RetryJobResponses, ErrorStatusCodeOf<RetryJobResponses>>;
export type RetryJobResponse200 = ResponseBodyOf<RetryJobResponses[200]>;
export type RetryJobResponse401 = ResponseBodyOf<RetryJobResponses[401]>;
export type RetryJobResponse403 = ResponseBodyOf<RetryJobResponses[403]>;
export type RetryJobResponse422 = ResponseBodyOf<RetryJobResponses[422]>;

type GetReleaseInfoSpec = OperationOf<"get_release_info">;
export type GetReleaseInfoOperation = GetReleaseInfoSpec;
export type GetReleaseInfoPathParams = Simplify<FieldOf<ParametersOf<GetReleaseInfoSpec>, "path">>;
export type GetReleaseInfoQueryParams = Simplify<FieldOf<ParametersOf<GetReleaseInfoSpec>, "query">>;
export type GetReleaseInfoHeaders = Simplify<FieldOf<ParametersOf<GetReleaseInfoSpec>, "header">>;
export type GetReleaseInfoRequestContentType = RequestContentTypesOf<GetReleaseInfoSpec>;
export type GetReleaseInfoRequestBody = RequestBodyOf<GetReleaseInfoSpec>;
export type GetReleaseInfoRequestBodyForContentType<TContentType extends GetReleaseInfoRequestContentType> = RequestBodyForContentType<GetReleaseInfoSpec, TContentType>;
export type GetReleaseInfoResponses = ResponsesOf<GetReleaseInfoSpec>;
export type GetReleaseInfoSuccessData = ResponseDataOf<GetReleaseInfoResponses, SuccessStatusCodeOf<GetReleaseInfoResponses>>;
export type GetReleaseInfoErrorData = ResponseDataOf<GetReleaseInfoResponses, ErrorStatusCodeOf<GetReleaseInfoResponses>>;
export type GetReleaseInfoResponse200 = ResponseBodyOf<GetReleaseInfoResponses[200]>;

type PlanResourcesSpec = OperationOf<"plan_resources">;
export type PlanResourcesOperation = PlanResourcesSpec;
export type PlanResourcesPathParams = Simplify<FieldOf<ParametersOf<PlanResourcesSpec>, "path">>;
export type PlanResourcesQueryParams = Simplify<FieldOf<ParametersOf<PlanResourcesSpec>, "query">>;
export type PlanResourcesHeaders = Simplify<FieldOf<ParametersOf<PlanResourcesSpec>, "header">>;
export type PlanResourcesRequestContentType = RequestContentTypesOf<PlanResourcesSpec>;
export type PlanResourcesRequestBody = RequestBodyOf<PlanResourcesSpec>;
export type PlanResourcesRequestBodyForContentType<TContentType extends PlanResourcesRequestContentType> = RequestBodyForContentType<PlanResourcesSpec, TContentType>;
export type PlanResourcesResponses = ResponsesOf<PlanResourcesSpec>;
export type PlanResourcesSuccessData = ResponseDataOf<PlanResourcesResponses, SuccessStatusCodeOf<PlanResourcesResponses>>;
export type PlanResourcesErrorData = ResponseDataOf<PlanResourcesResponses, ErrorStatusCodeOf<PlanResourcesResponses>>;
export type PlanResourcesResponse200 = ResponseBodyOf<PlanResourcesResponses[200]>;
export type PlanResourcesResponse422 = ResponseBodyOf<PlanResourcesResponses[422]>;

type PresignDownloadSpec = OperationOf<"presign_download">;
export type PresignDownloadOperation = PresignDownloadSpec;
export type PresignDownloadPathParams = Simplify<FieldOf<ParametersOf<PresignDownloadSpec>, "path">>;
export type PresignDownloadQueryParams = Simplify<FieldOf<ParametersOf<PresignDownloadSpec>, "query">>;
export type PresignDownloadHeaders = Simplify<FieldOf<ParametersOf<PresignDownloadSpec>, "header">>;
export type PresignDownloadRequestContentType = RequestContentTypesOf<PresignDownloadSpec>;
export type PresignDownloadRequestBody = RequestBodyOf<PresignDownloadSpec>;
export type PresignDownloadRequestBodyForContentType<TContentType extends PresignDownloadRequestContentType> = RequestBodyForContentType<PresignDownloadSpec, TContentType>;
export type PresignDownloadResponses = ResponsesOf<PresignDownloadSpec>;
export type PresignDownloadSuccessData = ResponseDataOf<PresignDownloadResponses, SuccessStatusCodeOf<PresignDownloadResponses>>;
export type PresignDownloadErrorData = ResponseDataOf<PresignDownloadResponses, ErrorStatusCodeOf<PresignDownloadResponses>>;
export type PresignDownloadResponse200 = ResponseBodyOf<PresignDownloadResponses[200]>;
export type PresignDownloadResponse401 = ResponseBodyOf<PresignDownloadResponses[401]>;
export type PresignDownloadResponse403 = ResponseBodyOf<PresignDownloadResponses[403]>;
export type PresignDownloadResponse422 = ResponseBodyOf<PresignDownloadResponses[422]>;

type AbortUploadSpec = OperationOf<"abort_upload">;
export type AbortUploadOperation = AbortUploadSpec;
export type AbortUploadPathParams = Simplify<FieldOf<ParametersOf<AbortUploadSpec>, "path">>;
export type AbortUploadQueryParams = Simplify<FieldOf<ParametersOf<AbortUploadSpec>, "query">>;
export type AbortUploadHeaders = Simplify<FieldOf<ParametersOf<AbortUploadSpec>, "header">>;
export type AbortUploadRequestContentType = RequestContentTypesOf<AbortUploadSpec>;
export type AbortUploadRequestBody = RequestBodyOf<AbortUploadSpec>;
export type AbortUploadRequestBodyForContentType<TContentType extends AbortUploadRequestContentType> = RequestBodyForContentType<AbortUploadSpec, TContentType>;
export type AbortUploadResponses = ResponsesOf<AbortUploadSpec>;
export type AbortUploadSuccessData = ResponseDataOf<AbortUploadResponses, SuccessStatusCodeOf<AbortUploadResponses>>;
export type AbortUploadErrorData = ResponseDataOf<AbortUploadResponses, ErrorStatusCodeOf<AbortUploadResponses>>;
export type AbortUploadResponse200 = ResponseBodyOf<AbortUploadResponses[200]>;
export type AbortUploadResponse401 = ResponseBodyOf<AbortUploadResponses[401]>;
export type AbortUploadResponse403 = ResponseBodyOf<AbortUploadResponses[403]>;
export type AbortUploadResponse422 = ResponseBodyOf<AbortUploadResponses[422]>;

type CompleteUploadSpec = OperationOf<"complete_upload">;
export type CompleteUploadOperation = CompleteUploadSpec;
export type CompleteUploadPathParams = Simplify<FieldOf<ParametersOf<CompleteUploadSpec>, "path">>;
export type CompleteUploadQueryParams = Simplify<FieldOf<ParametersOf<CompleteUploadSpec>, "query">>;
export type CompleteUploadHeaders = Simplify<FieldOf<ParametersOf<CompleteUploadSpec>, "header">>;
export type CompleteUploadRequestContentType = RequestContentTypesOf<CompleteUploadSpec>;
export type CompleteUploadRequestBody = RequestBodyOf<CompleteUploadSpec>;
export type CompleteUploadRequestBodyForContentType<TContentType extends CompleteUploadRequestContentType> = RequestBodyForContentType<CompleteUploadSpec, TContentType>;
export type CompleteUploadResponses = ResponsesOf<CompleteUploadSpec>;
export type CompleteUploadSuccessData = ResponseDataOf<CompleteUploadResponses, SuccessStatusCodeOf<CompleteUploadResponses>>;
export type CompleteUploadErrorData = ResponseDataOf<CompleteUploadResponses, ErrorStatusCodeOf<CompleteUploadResponses>>;
export type CompleteUploadResponse200 = ResponseBodyOf<CompleteUploadResponses[200]>;
export type CompleteUploadResponse401 = ResponseBodyOf<CompleteUploadResponses[401]>;
export type CompleteUploadResponse403 = ResponseBodyOf<CompleteUploadResponses[403]>;
export type CompleteUploadResponse422 = ResponseBodyOf<CompleteUploadResponses[422]>;

type InitiateUploadSpec = OperationOf<"initiate_upload">;
export type InitiateUploadOperation = InitiateUploadSpec;
export type InitiateUploadPathParams = Simplify<FieldOf<ParametersOf<InitiateUploadSpec>, "path">>;
export type InitiateUploadQueryParams = Simplify<FieldOf<ParametersOf<InitiateUploadSpec>, "query">>;
export type InitiateUploadHeaders = Simplify<FieldOf<ParametersOf<InitiateUploadSpec>, "header">>;
export type InitiateUploadRequestContentType = RequestContentTypesOf<InitiateUploadSpec>;
export type InitiateUploadRequestBody = RequestBodyOf<InitiateUploadSpec>;
export type InitiateUploadRequestBodyForContentType<TContentType extends InitiateUploadRequestContentType> = RequestBodyForContentType<InitiateUploadSpec, TContentType>;
export type InitiateUploadResponses = ResponsesOf<InitiateUploadSpec>;
export type InitiateUploadSuccessData = ResponseDataOf<InitiateUploadResponses, SuccessStatusCodeOf<InitiateUploadResponses>>;
export type InitiateUploadErrorData = ResponseDataOf<InitiateUploadResponses, ErrorStatusCodeOf<InitiateUploadResponses>>;
export type InitiateUploadResponse200 = ResponseBodyOf<InitiateUploadResponses[200]>;
export type InitiateUploadResponse401 = ResponseBodyOf<InitiateUploadResponses[401]>;
export type InitiateUploadResponse403 = ResponseBodyOf<InitiateUploadResponses[403]>;
export type InitiateUploadResponse409 = ResponseBodyOf<InitiateUploadResponses[409]>;
export type InitiateUploadResponse422 = ResponseBodyOf<InitiateUploadResponses[422]>;
export type InitiateUploadResponse503 = ResponseBodyOf<InitiateUploadResponses[503]>;

type IntrospectUploadSpec = OperationOf<"introspect_upload">;
export type IntrospectUploadOperation = IntrospectUploadSpec;
export type IntrospectUploadPathParams = Simplify<FieldOf<ParametersOf<IntrospectUploadSpec>, "path">>;
export type IntrospectUploadQueryParams = Simplify<FieldOf<ParametersOf<IntrospectUploadSpec>, "query">>;
export type IntrospectUploadHeaders = Simplify<FieldOf<ParametersOf<IntrospectUploadSpec>, "header">>;
export type IntrospectUploadRequestContentType = RequestContentTypesOf<IntrospectUploadSpec>;
export type IntrospectUploadRequestBody = RequestBodyOf<IntrospectUploadSpec>;
export type IntrospectUploadRequestBodyForContentType<TContentType extends IntrospectUploadRequestContentType> = RequestBodyForContentType<IntrospectUploadSpec, TContentType>;
export type IntrospectUploadResponses = ResponsesOf<IntrospectUploadSpec>;
export type IntrospectUploadSuccessData = ResponseDataOf<IntrospectUploadResponses, SuccessStatusCodeOf<IntrospectUploadResponses>>;
export type IntrospectUploadErrorData = ResponseDataOf<IntrospectUploadResponses, ErrorStatusCodeOf<IntrospectUploadResponses>>;
export type IntrospectUploadResponse200 = ResponseBodyOf<IntrospectUploadResponses[200]>;
export type IntrospectUploadResponse401 = ResponseBodyOf<IntrospectUploadResponses[401]>;
export type IntrospectUploadResponse403 = ResponseBodyOf<IntrospectUploadResponses[403]>;
export type IntrospectUploadResponse422 = ResponseBodyOf<IntrospectUploadResponses[422]>;

type SignUploadPartsSpec = OperationOf<"sign_upload_parts">;
export type SignUploadPartsOperation = SignUploadPartsSpec;
export type SignUploadPartsPathParams = Simplify<FieldOf<ParametersOf<SignUploadPartsSpec>, "path">>;
export type SignUploadPartsQueryParams = Simplify<FieldOf<ParametersOf<SignUploadPartsSpec>, "query">>;
export type SignUploadPartsHeaders = Simplify<FieldOf<ParametersOf<SignUploadPartsSpec>, "header">>;
export type SignUploadPartsRequestContentType = RequestContentTypesOf<SignUploadPartsSpec>;
export type SignUploadPartsRequestBody = RequestBodyOf<SignUploadPartsSpec>;
export type SignUploadPartsRequestBodyForContentType<TContentType extends SignUploadPartsRequestContentType> = RequestBodyForContentType<SignUploadPartsSpec, TContentType>;
export type SignUploadPartsResponses = ResponsesOf<SignUploadPartsSpec>;
export type SignUploadPartsSuccessData = ResponseDataOf<SignUploadPartsResponses, SuccessStatusCodeOf<SignUploadPartsResponses>>;
export type SignUploadPartsErrorData = ResponseDataOf<SignUploadPartsResponses, ErrorStatusCodeOf<SignUploadPartsResponses>>;
export type SignUploadPartsResponse200 = ResponseBodyOf<SignUploadPartsResponses[200]>;
export type SignUploadPartsResponse401 = ResponseBodyOf<SignUploadPartsResponses[401]>;
export type SignUploadPartsResponse403 = ResponseBodyOf<SignUploadPartsResponses[403]>;
export type SignUploadPartsResponse422 = ResponseBodyOf<SignUploadPartsResponses[422]>;
