Parameters:
  Project:
    Type: String
    Description: Name of the project
    MinLength: 2
    Default: crdl
  Application:
    Type: String
    Description: Name of the application
    MinLength: 2
  Service:
    Type: String
  EcrRepoName:
    Type: String
  EcrKmsAlias:
    Type: String
  UsedByEcs:
    Type: String
    Default: "false"
    AllowedValues: ["true", "false"]

Conditions:
  UseEcs: !Equals [!Ref UsedByEcs, "true"]

Resources:
  ECRRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Ref EcrRepoName
      LifecyclePolicy:
        LifecyclePolicyText: |
          {
            "rules": [
            {
              "rulePriority": 1,
              "description": "Only keep 2 images",
              "selection": {
                "tagStatus": "any",
                "countType": "imageCountMoreThan",
                "countNumber": 2
              },
              "action": { "type": "expire" }
            }]
          }
      EncryptionConfiguration:
        EncryptionType: KMS
        KmsKey: !Sub alias/${EcrKmsAlias}
      ImageScanningConfiguration:
        ScanOnPush: true
      Tags:
        - Key: Project
          Value: !Ref Project
        - Key: Application
          Value: !Ref Application
        - Key: Service
          Value: !Ref Service
      RepositoryPolicyText:
        Version: "2012-10-17"
        Statement:
          - Sid: AllowPush
            Effect: Allow
            Principal:
              AWS:
              - !Sub "arn:aws:iam::${AWS::AccountId}:root"
            Action:
              - "ecr:GetAuthorizationToken"
              - "ecr:BatchCheckLayerAvailability"
              - "ecr:PutImage"
              - "ecr:InitiateLayerUpload"
              - "ecr:UploadLayerPart"
              - "ecr:CompleteLayerUpload"
              - "ecr:DescribeRepositories"

          # Allow lambda and ecs services to pull images from this ECR repo
          - Sid: AWSResourceRetrieval
            Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
                - ecs.amazonaws.com
            Action:
              - "ecr:BatchGetImage"
              - "ecr:GetDownloadUrlForLayer"

  # Role that Amazon ECS needs to pull container images and run the task
  EcsTaskExecutionRole:
    Condition: UseEcs
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${Project}-${Application}-${Service}-ecs-task-execution-${AWS::Region}"
      Tags:
        - Key: Project
          Value: !Ref Project
        - Key: Application
          Value: !Ref Application
        - Key: Service
          Value: !Ref Service
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Action:
              - sts:AssumeRole
            Principal:
              Service:
                - ecs-tasks.amazonaws.com
      Policies:
        - PolicyName: !Sub "${Project}-${Application}-${Service}-ecs-task-execution-${AWS::Region}"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                  - ecr:GetAuthorizationToken
                Resource: "*"
                Condition:
                  StringEquals:
                    aws:RequestedRegion: !Ref "AWS::Region"
              - Effect: Allow
                Action:
                  - ecr:BatchCheckLayerAvailability
                  - ecr:GetDownloadUrlForLayer
                  - ecr:BatchGetImage
                Resource: "*"
                Condition:
                  StringEquals:
                    aws:RequestedRegion: !Ref "AWS::Region"

Outputs:
  ECRRepositoryName:
    Value: !Sub ${EcrRepoName}
    Export:
      Name: !Sub "${AWS::AccountId}:${AWS::Region}:${Project}:${Application}:${Service}:ecr:name"
  ECRRepositoryUri:
    Value: !GetAtt ECRRepository.RepositoryUri
    Export:
      Name: !Sub "${AWS::AccountId}:${AWS::Region}:${Project}:${Application}:${Service}:ecr:uri"
  ECRRepositoryArn:
    Value: !GetAtt ECRRepository.Arn
    Export:
      Name: !Sub "${AWS::AccountId}:${AWS::Region}:${Project}:${Application}:${Service}:ecr:arn"
