# Code generated by scripts/release/generate_clients.py. DO NOT EDIT.

new_nova_auth_client <- function(base_url, timeout_seconds = 30) {
  if (!is.character(base_url) || length(base_url) != 1L || !nzchar(base_url)) {
    stop("base_url must be a non-empty string", call. = FALSE)
  }
  structure(
    list(
      base_url = sub("/+$", "", base_url),
      timeout_seconds = timeout_seconds,
      operations = nova_auth_operation_catalog()
    ),
    class = "nova_auth_client"
  )
}

nova_auth_request_descriptor <- function(client, operation_id, path_params = list(), query = list()) {
  operation <- client$operations[[operation_id]]
  if (is.null(operation)) {
    stop(sprintf("unknown operation_id: %s", operation_id), call. = FALSE)
  }

  resolved_path <- operation$path
  if (length(path_params) > 0L) {
    for (param_name in names(path_params)) {
      resolved_path <- gsub(
        sprintf("{%s}", param_name),
        utils::URLencode(as.character(path_params[[param_name]]), reserved = TRUE),
        resolved_path,
        fixed = TRUE
      )
    }
  }

  list(
    operation_id = operation$operation_id,
    method = operation$method,
    url = paste0(client$base_url, resolved_path),
    query = query,
    timeout_seconds = client$timeout_seconds
  )
}
