# Code generated by scripts/release/generate_clients.py. DO NOT EDIT.

nova_auth_operation_catalog <- function() {
  list(
    "health_live" = list(
      operation_id = "health_live",
      method = "GET",
      path = "/v1/health/live",
      summary = "Health Live"
    ),
    "health_ready" = list(
      operation_id = "health_ready",
      method = "GET",
      path = "/v1/health/ready",
      summary = "Health Ready"
    ),
    "introspect_token" = list(
      operation_id = "introspect_token",
      method = "POST",
      path = "/v1/token/introspect",
      summary = "Introspect Token"
    ),
    "verify_token" = list(
      operation_id = "verify_token",
      method = "POST",
      path = "/v1/token/verify",
      summary = "Verify Token"
    )
  )
}
