# Code generated by scripts/release/generate_clients.py. DO NOT EDIT.

nova_auth_operation_catalog <- function() {
  list(
    "health_live" = list(
      operation_id = "health_live",
      method = "GET",
      path = "/v1/health/live",
      summary = "Health Live",
      has_request_body = FALSE,
      has_required_request_body = FALSE,
      has_path_params = FALSE,
      has_query_params = FALSE,
      has_required_query_params = FALSE,
      has_header_params = FALSE,
      has_required_header_params = FALSE,
      request_content_types = character(0),
      default_request_content_type = NULL,
      response_status_codes = c(200L)
    ),
    "health_ready" = list(
      operation_id = "health_ready",
      method = "GET",
      path = "/v1/health/ready",
      summary = "Health Ready",
      has_request_body = FALSE,
      has_required_request_body = FALSE,
      has_path_params = FALSE,
      has_query_params = FALSE,
      has_required_query_params = FALSE,
      has_header_params = FALSE,
      has_required_header_params = FALSE,
      request_content_types = character(0),
      default_request_content_type = NULL,
      response_status_codes = c(200L, 503L)
    ),
    "introspect_token" = list(
      operation_id = "introspect_token",
      method = "POST",
      path = "/v1/token/introspect",
      summary = "Introspect Token",
      has_request_body = TRUE,
      has_required_request_body = TRUE,
      has_path_params = FALSE,
      has_query_params = FALSE,
      has_required_query_params = FALSE,
      has_header_params = FALSE,
      has_required_header_params = FALSE,
      request_content_types = c("application/json", "application/x-www-form-urlencoded"),
      default_request_content_type = NULL,
      response_status_codes = c(200L, 401L, 403L, 422L, 503L)
    ),
    "verify_token" = list(
      operation_id = "verify_token",
      method = "POST",
      path = "/v1/token/verify",
      summary = "Verify Token",
      has_request_body = TRUE,
      has_required_request_body = TRUE,
      has_path_params = FALSE,
      has_query_params = FALSE,
      has_required_query_params = FALSE,
      has_header_params = FALSE,
      has_required_header_params = FALSE,
      request_content_types = c("application/json"),
      default_request_content_type = "application/json",
      response_status_codes = c(200L, 401L, 403L, 422L, 503L)
    )
  )
}

nova_auth_null_coalesce <- function(value, fallback) {
  if (is.null(value)) {
    fallback
  } else {
    value
  }
}

nova_auth_normalize_named_list <- function(value, label) {
  if (is.null(value)) {
    return(list())
  }
  if (is.atomic(value) && !is.list(value)) {
    value <- as.list(value)
  }
  if (!is.list(value)) {
    stop(sprintf("%s must be a named list", label), call. = FALSE)
  }
  item_names <- names(value)
  if (is.null(item_names)) {
    stop(sprintf("%s must be a named list", label), call. = FALSE)
  }
  cleaned <- list()
  for (index in seq_along(value)) {
    item_name <- item_names[[index]]
    if (is.na(item_name) || !nzchar(item_name)) {
      stop(sprintf("%s names must be non-empty", label), call. = FALSE)
    }
    item_value <- value[[index]]
    if (is.null(item_value)) {
      next
    }
    cleaned[[item_name]] <- item_value
  }
  cleaned
}

nova_auth_prune_null_headers <- function(value) {
  if (length(value) == 0L) {
    return(value)
  }
  value[!vapply(value, is.null, logical(1))]
}

nova_auth_normalize_base_url <- function(base_url) {
  if (!is.character(base_url) || length(base_url) != 1L || !nzchar(base_url)) {
    stop("base_url must be a non-empty string", call. = FALSE)
  }
  sub("/+$", "", base_url)
}

nova_auth_resolve_path <- function(path, path_params) {
  resolved_path <- path
  if (length(path_params) > 0L) {
    for (param_name in names(path_params)) {
      resolved_path <- gsub(
        sprintf("{%s}", param_name),
        utils::URLencode(as.character(path_params[[param_name]]), reserved = TRUE),
        resolved_path,
        fixed = TRUE
      )
    }
  }
  missing_path_params <- regmatches(
    resolved_path, gregexpr("\\{[^}]+\\}", resolved_path, perl = TRUE)
  )[[1]]
  if (length(missing_path_params) > 0L) {
    stop(sprintf("missing path parameter(s): %s", paste(missing_path_params, collapse = ", ")), call. = FALSE)
  }
  resolved_path
}

nova_auth_select_content_type <- function(operation, content_type) {
  available_content_types <- operation$request_content_types
  if (is.null(content_type) || !nzchar(as.character(content_type)[[1]])) {
    if (length(available_content_types) == 0L) {
      return(NULL)
    }
    if (length(available_content_types) > 1L) {
      stop(sprintf("operation %s requires an explicit content_type", operation$operation_id), call. = FALSE)
    }
    return(available_content_types[[1L]])
  }
  selected_content_type <- as.character(content_type)[[1]]
  if (!(selected_content_type %in% available_content_types)) {
    stop(sprintf("unsupported content_type %s for operation %s", selected_content_type, operation$operation_id), call. = FALSE)
  }
  selected_content_type
}

nova_auth_parse_json_body <- function(body) {
  if (is.null(body) || !nzchar(trimws(body))) {
    return(NULL)
  }
  tryCatch(
    jsonlite::fromJSON(body, simplifyVector = FALSE),
    error = function(...) NULL
  )
}

nova_auth_encode_json_body <- function(body) {
  jsonlite::toJSON(body, auto_unbox = TRUE, null = "null")
}

nova_auth_encode_form_body <- function(body) {
  if (is.null(body) || length(body) == 0L) {
    return("")
  }
  body <- nova_auth_normalize_named_list(body, "body")
  encode_item <- function(name, value) {
    if (is.null(value)) {
      return(character(0))
    }
    if (is.list(value) && !inherits(value, "data.frame")) {
      value <- jsonlite::toJSON(value, auto_unbox = TRUE, null = "null")
      return(paste0(utils::URLencode(name, reserved = TRUE), "=", utils::URLencode(value, reserved = TRUE)))
    }
    values <- as.character(value)
    if (length(values) == 0L) {
      return(character(0))
    }
    encoded_name <- utils::URLencode(name, reserved = TRUE)
    vapply(
      values,
      function(item) {
        paste0(encoded_name, "=", utils::URLencode(item, reserved = TRUE))
      },
      character(1)
    )
  }
  parts <- character(0)
  for (name in names(body)) {
    parts <- c(parts, encode_item(name, body[[name]]))
  }
  paste(parts, collapse = "&")
}

nova_auth_encode_request_body <- function(body, content_type) {
  if (is.null(body)) {
    return(NULL)
  }
  if (identical(content_type, "application/json")) {
    return(nova_auth_encode_json_body(body))
  }
  if (identical(content_type, "application/x-www-form-urlencoded")) {
    return(nova_auth_encode_form_body(body))
  }
  stop(sprintf("unsupported content_type %s", content_type), call. = FALSE)
}

nova_auth_decode_error_envelope <- function(body, status = NULL) {
  parsed_body <- nova_auth_parse_json_body(body)
  if (!is.list(parsed_body) || is.null(parsed_body$error) || !is.list(parsed_body$error)) {
    if (is.null(status)) {
      return(NULL)
    }
    fallback_message <- if (is.null(body) || !nzchar(trimws(body))) {
      sprintf("HTTP %s response", status)
    } else {
      body
    }
    return(
      list(
        error = list(
          code = paste0("http_", status),
          message = fallback_message,
          details = list(),
          request_id = NULL
        )
      )
    )
  }
  error_body <- parsed_body$error
  request_id <- error_body$request_id
  if (length(request_id) == 0L) {
    request_id <- NULL
  }
  list(
    error = list(
      code = as.character(error_body$code),
      message = as.character(error_body$message),
      details = nova_auth_null_coalesce(error_body$details, list()),
      request_id = request_id
    )
  )
}
