# Code generated by scripts/release/r_sdk.py. DO NOT EDIT.

nova_metrics_summary <- function(
  client,
  headers = NULL
) {
  nova_api_call(
    client = client,
    operation_id = "metrics_summary",
    method = "GET",
    path = "/metrics/summary",
    headers = headers,
    requires_body = FALSE,
    accepts_body = FALSE
  )
}

nova_get_capabilities <- function(
  client,
  headers = NULL
) {
  nova_api_call(
    client = client,
    operation_id = "get_capabilities",
    method = "GET",
    path = "/v1/capabilities",
    headers = headers,
    requires_body = FALSE,
    accepts_body = FALSE
  )
}

nova_get_transfer_capabilities <- function(
  client,
  policy_hint = NULL,
  workload_class = NULL,
  headers = NULL
) {
  nova_api_call(
    client = client,
    operation_id = "get_transfer_capabilities",
    method = "GET",
    path = "/v1/capabilities/transfers",
    query = list(policy_hint = policy_hint, workload_class = workload_class),
    headers = headers,
    requires_body = FALSE,
    accepts_body = FALSE
  )
}

nova_list_exports <- function(
  client,
  limit = NULL,
  headers = NULL
) {
  nova_api_call(
    client = client,
    operation_id = "list_exports",
    method = "GET",
    path = "/v1/exports",
    query = list(limit = limit),
    headers = headers,
    requires_body = FALSE,
    accepts_body = FALSE
  )
}

nova_create_export <- function(
  client,
  body,
  headers = NULL
) {
  nova_api_call(
    client = client,
    operation_id = "create_export",
    method = "POST",
    path = "/v1/exports",
    body = body,
    headers = headers,
    requires_body = TRUE,
    accepts_body = TRUE
  )
}

nova_get_export <- function(
  client,
  export_id,
  headers = NULL
) {
  nova_api_call(
    client = client,
    operation_id = "get_export",
    method = "GET",
    path = "/v1/exports/{export_id}",
    path_params = list(export_id = export_id),
    headers = headers,
    requires_body = FALSE,
    accepts_body = FALSE
  )
}

nova_cancel_export <- function(
  client,
  export_id,
  headers = NULL
) {
  nova_api_call(
    client = client,
    operation_id = "cancel_export",
    method = "POST",
    path = "/v1/exports/{export_id}/cancel",
    path_params = list(export_id = export_id),
    headers = headers,
    requires_body = FALSE,
    accepts_body = FALSE
  )
}

nova_health_live <- function(
  client,
  headers = NULL
) {
  nova_api_call(
    client = client,
    operation_id = "health_live",
    method = "GET",
    path = "/v1/health/live",
    headers = headers,
    requires_body = FALSE,
    accepts_body = FALSE
  )
}

nova_health_ready <- function(
  client,
  headers = NULL
) {
  nova_api_call(
    client = client,
    operation_id = "health_ready",
    method = "GET",
    path = "/v1/health/ready",
    headers = headers,
    requires_body = FALSE,
    accepts_body = FALSE
  )
}

nova_get_release_info <- function(
  client,
  headers = NULL
) {
  nova_api_call(
    client = client,
    operation_id = "get_release_info",
    method = "GET",
    path = "/v1/releases/info",
    headers = headers,
    requires_body = FALSE,
    accepts_body = FALSE
  )
}

nova_plan_resources <- function(
  client,
  body,
  headers = NULL
) {
  nova_api_call(
    client = client,
    operation_id = "plan_resources",
    method = "POST",
    path = "/v1/resources/plan",
    body = body,
    headers = headers,
    requires_body = TRUE,
    accepts_body = TRUE
  )
}

nova_presign_download <- function(
  client,
  body,
  headers = NULL
) {
  nova_api_call(
    client = client,
    operation_id = "presign_download",
    method = "POST",
    path = "/v1/transfers/downloads/presign",
    body = body,
    headers = headers,
    requires_body = TRUE,
    accepts_body = TRUE
  )
}

nova_abort_upload <- function(
  client,
  body,
  headers = NULL
) {
  nova_api_call(
    client = client,
    operation_id = "abort_upload",
    method = "POST",
    path = "/v1/transfers/uploads/abort",
    body = body,
    headers = headers,
    requires_body = TRUE,
    accepts_body = TRUE
  )
}

nova_complete_upload <- function(
  client,
  body,
  headers = NULL
) {
  nova_api_call(
    client = client,
    operation_id = "complete_upload",
    method = "POST",
    path = "/v1/transfers/uploads/complete",
    body = body,
    headers = headers,
    requires_body = TRUE,
    accepts_body = TRUE
  )
}

nova_initiate_upload <- function(
  client,
  body,
  headers = NULL
) {
  nova_api_call(
    client = client,
    operation_id = "initiate_upload",
    method = "POST",
    path = "/v1/transfers/uploads/initiate",
    body = body,
    headers = headers,
    requires_body = TRUE,
    accepts_body = TRUE
  )
}

nova_introspect_upload <- function(
  client,
  body,
  headers = NULL
) {
  nova_api_call(
    client = client,
    operation_id = "introspect_upload",
    method = "POST",
    path = "/v1/transfers/uploads/introspect",
    body = body,
    headers = headers,
    requires_body = TRUE,
    accepts_body = TRUE
  )
}

nova_sign_upload_parts <- function(
  client,
  body,
  headers = NULL
) {
  nova_api_call(
    client = client,
    operation_id = "sign_upload_parts",
    method = "POST",
    path = "/v1/transfers/uploads/sign-parts",
    body = body,
    headers = headers,
    requires_body = TRUE,
    accepts_body = TRUE
  )
}
