"""Tests for the TypeScript public module policy gate."""

from __future__ import annotations

import importlib
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

check_typescript_module_policy = importlib.import_module(
    "scripts.conformance.check_typescript_module_policy"
)


def _write(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")


def test_generator_owned_internal_index_is_allowed(
    tmp_path: Path,
    monkeypatch,
) -> None:
    """Allow the one Hey API-generated internal client index scaffold."""
    internal_index = (
        tmp_path
        / "packages"
        / "nova_sdk_ts"
        / "src"
        / "client"
        / "client"
        / "index.ts"
    )
    _write(
        internal_index,
        "\n".join(
            [
                "// This file is auto-generated by @hey-api/openapi-ts",
                "",
                "export type { Auth } from '../core/auth.gen.js';",
                "export { createClient } from './client.gen.js';",
                "export { createConfig, mergeHeaders } from './utils.gen.js';",
                "",
            ]
        ),
    )

    monkeypatch.setattr(check_typescript_module_policy, "REPO_ROOT", tmp_path)
    monkeypatch.setattr(
        check_typescript_module_policy, "TS_ROOT", tmp_path / "packages"
    )

    assert check_typescript_module_policy._validate_public_module_policy() == []


def test_public_index_entrypoints_are_rejected(
    tmp_path: Path,
    monkeypatch,
) -> None:
    """Reject public index.ts entrypoints anywhere under package src roots."""
    public_index = tmp_path / "packages" / "example" / "src" / "index.ts"
    _write(
        public_index,
        "\n".join(
            [
                "export { thing } from './thing.js';",
                "",
            ]
        ),
    )

    monkeypatch.setattr(check_typescript_module_policy, "REPO_ROOT", tmp_path)
    monkeypatch.setattr(
        check_typescript_module_policy, "TS_ROOT", tmp_path / "packages"
    )

    violations = check_typescript_module_policy._validate_public_module_policy()

    assert violations == [
        (
            "packages/example/src/index.ts: "
            "public index.ts entrypoints are disallowed"
        )
    ]


def test_public_barrels_outside_allowed_internal_index_are_rejected(
    tmp_path: Path,
    monkeypatch,
) -> None:
    """Reject barrel re-exports outside the allowlisted internal file."""
    public_barrel = tmp_path / "packages" / "example" / "src" / "module.ts"
    _write(
        public_barrel,
        "\n".join(
            [
                "export { thing } from './thing.js';",
                "",
            ]
        ),
    )

    monkeypatch.setattr(check_typescript_module_policy, "REPO_ROOT", tmp_path)
    monkeypatch.setattr(
        check_typescript_module_policy, "TS_ROOT", tmp_path / "packages"
    )

    violations = check_typescript_module_policy._validate_public_module_policy()

    assert violations == [
        (
            "packages/example/src/module.ts:1: "
            "public re-export barrel syntax is disallowed"
        )
    ]


def test_internal_index_requires_allowlisted_exports_and_header(
    tmp_path: Path,
    monkeypatch,
) -> None:
    """Reject non-generator or non-allowlisted content in the internal index."""
    internal_index = (
        tmp_path
        / "packages"
        / "nova_sdk_ts"
        / "src"
        / "client"
        / "client"
        / "index.ts"
    )
    _write(
        internal_index,
        "\n".join(
            [
                "// custom file",
                "",
                "export { createClient } from './client.gen.js';",
                "export { leaked } from '../private.js';",
                "",
            ]
        ),
    )

    monkeypatch.setattr(check_typescript_module_policy, "REPO_ROOT", tmp_path)
    monkeypatch.setattr(
        check_typescript_module_policy, "TS_ROOT", tmp_path / "packages"
    )

    violations = check_typescript_module_policy._validate_public_module_policy()

    assert (
        "packages/nova_sdk_ts/src/client/client/index.ts: "
        "generator-owned internal index must keep the "
        "Hey API autogenerated header" in violations
    )
    assert (
        "packages/nova_sdk_ts/src/client/client/index.ts:4: "
        "internal generator barrel target is not allowlisted: "
        "../private.js" in violations
    )
