// Code generated by scripts/release/generate_clients.py. DO NOT EDIT.

export interface OperationDescriptor {
  readonly operationId: string;
  readonly method: "GET" | "POST" | "PUT" | "PATCH" | "DELETE" | "OPTIONS" | "HEAD";
  readonly path: string;
  readonly summary?: string;
}

export const operations = {
  "health_live": {
    operationId: "health_live",
    method: "GET",
    path: "/v1/health/live",
    summary: "Health Live",
  },
  "health_ready": {
    operationId: "health_ready",
    method: "GET",
    path: "/v1/health/ready",
    summary: "Health Ready",
  },
  "introspect_token": {
    operationId: "introspect_token",
    method: "POST",
    path: "/v1/token/introspect",
    summary: "Introspect Token",
  },
  "verify_token": {
    operationId: "verify_token",
    method: "POST",
    path: "/v1/token/verify",
    summary: "Verify Token",
  },
} as const satisfies Record<string, OperationDescriptor>;

export type OperationId = keyof typeof operations;
export type GeneratedOperationCatalog = typeof operations;
