// Code generated by scripts/release/generate_clients.py. DO NOT EDIT.

import type { OperationDescriptor } from "@nova/sdk-fetch/contracts";

/** Catalog of generated operations keyed by operationId. */
export const operations = {
  "health_live": {
    operationId: "health_live",
    method: "GET",
    path: "/v1/health/live",
    summary: "Health Live",
  },
  "health_ready": {
    operationId: "health_ready",
    method: "GET",
    path: "/v1/health/ready",
    summary: "Health Ready",
  },
  "introspect_token": {
    operationId: "introspect_token",
    method: "POST",
    path: "/v1/token/introspect",
    summary: "Introspect Token",
  },
  "verify_token": {
    operationId: "verify_token",
    method: "POST",
    path: "/v1/token/verify",
    summary: "Verify Token",
  },
} as const satisfies Record<string, OperationDescriptor>;

/** Union of all generated operation identifiers. */
export type OperationId = keyof typeof operations;
/** Static type representing the generated operations catalog. */
export type GeneratedOperationCatalog = typeof operations;
