// Code generated by scripts/release/generate_clients.py. DO NOT EDIT.

import { createFetchClient } from "@nova/sdk-fetch/client";
import type { FetchClientOptions, OperationDescriptor, PathParams, QueryParams } from "@nova/sdk-fetch/contracts";
import { normalizeBaseUrl } from "@nova/sdk-fetch/url";
import { NovaSdkTransportError } from "./errors.js";
import { operations } from "./operations.js";
import type { HealthLiveRequestOptions, HealthLiveResult, HealthReadyRequestOptions, HealthReadyResult, IntrospectTokenRequestOptions, IntrospectTokenResult, VerifyTokenRequestOptions, VerifyTokenResult } from "./types.js";

export interface NovaAuthClientOptions extends FetchClientOptions {}

export interface NovaAuthClient {
  readonly baseUrl: string;
  health_live(request?: HealthLiveRequestOptions): Promise<HealthLiveResult>;
  health_ready(request?: HealthReadyRequestOptions): Promise<HealthReadyResult>;
  introspect_token(request: IntrospectTokenRequestOptions): Promise<IntrospectTokenResult>;
  verify_token(request: VerifyTokenRequestOptions): Promise<VerifyTokenResult>;
}

type OperationRequest = {
  readonly body?: unknown;
  readonly contentType?: string;
  readonly headers?: HeadersInit;
  readonly pathParams?: PathParams;
  readonly query?: QueryParams;
  readonly signal?: AbortSignal;
};

async function executeOperation<TResult>(
  fetchClient: ReturnType<typeof createFetchClient>,
  operation: OperationDescriptor,
  request: OperationRequest = {},
  defaultContentType?: string,
): Promise<TResult> {
  try {
    return (await fetchClient.request<unknown>(operation, {
      body: request.body,
      contentType: request.contentType ?? defaultContentType,
      headers: request.headers,
      pathParams: request.pathParams,
      query: request.query,
      signal: request.signal,
    })) as TResult;
  } catch (error) {
    throw new NovaSdkTransportError(operation.operationId, error);
  }
}

export function createNovaAuthClient(
  options: NovaAuthClientOptions,
): NovaAuthClient {
  const fetchClient = createFetchClient(options);
  const baseUrl = normalizeBaseUrl(options.baseUrl);

  return {
    baseUrl,
    async health_live(request: HealthLiveRequestOptions = {}): Promise<HealthLiveResult> {
      return executeOperation<HealthLiveResult>(
        fetchClient,
        operations.health_live,
        request as OperationRequest,
        undefined,
      );
    },
    async health_ready(request: HealthReadyRequestOptions = {}): Promise<HealthReadyResult> {
      return executeOperation<HealthReadyResult>(
        fetchClient,
        operations.health_ready,
        request as OperationRequest,
        undefined,
      );
    },
    async introspect_token(request: IntrospectTokenRequestOptions): Promise<IntrospectTokenResult> {
      return executeOperation<IntrospectTokenResult>(
        fetchClient,
        operations.introspect_token,
        request as OperationRequest,
        undefined,
      );
    },
    async verify_token(request: VerifyTokenRequestOptions): Promise<VerifyTokenResult> {
      return executeOperation<VerifyTokenResult>(
        fetchClient,
        operations.verify_token,
        request as OperationRequest,
        "application/json",
      );
    },
  };
}
