// Code generated by scripts/release/generate_clients.py. DO NOT EDIT.

interface HttpLikeResponse<TData = unknown> {
  readonly status: number;
  readonly ok: boolean;
  readonly headers: Headers;
  readonly data: TData;
}

/** Transport-level failure raised before an HTTP response is available. */
export class NovaSdkTransportError extends Error {
  readonly operationId: string;
  override readonly cause: unknown;

  constructor(operationId: string, cause: unknown) {
    super(`Transport error for ${operationId}`);
    this.name = "NovaSdkTransportError";
    this.operationId = operationId;
    this.cause = cause;
  }
}

/** HTTP failure wrapper for callers that prefer throwing over branch handling. */
export class NovaSdkHttpError<TResponse extends HttpLikeResponse = HttpLikeResponse> extends Error {
  readonly operationId: string;
  readonly response: TResponse;

  constructor(operationId: string, response: TResponse) {
    super(`HTTP ${response.status} for ${operationId}`);
    this.name = "NovaSdkHttpError";
    this.operationId = operationId;
    this.response = response;
  }

  get status(): number {
    return this.response.status;
  }

  get data(): TResponse["data"] {
    return this.response.data;
  }

  get headers(): Headers {
    return this.response.headers;
  }
}

/** Throw a typed HTTP error when a response status is not successful. */
export function assertOkResponse<TResponse extends HttpLikeResponse>(
  operationId: string,
  response: TResponse,
): asserts response is TResponse & { readonly ok: true } {
  if (!response.ok) {
    throw new NovaSdkHttpError(operationId, response);
  }
}
