// Code generated by scripts/release/generate_clients.py. DO NOT EDIT.

import type {
  components as GeneratedComponents,
  operations as GeneratedOperations,
} from "./generated/openapi.js";

type EmptyObject = Record<string, never>;
type SuccessStatus = 200 | 201 | 202 | 203 | 204 | 205 | 206 | 207 | 208 | 226;
type Simplify<T> = { [K in keyof T]: T[K] } & {};
type OperationOf<TId extends keyof GeneratedOperations> = GeneratedOperations[TId];
type ParametersOf<T> = T extends { parameters: infer TParameters } ? TParameters : EmptyObject;
type FieldOf<TParameters, TKey extends "query" | "header" | "path"> = TParameters extends { [K in TKey]?: infer TValue }
  ? [TValue] extends [never]
    ? EmptyObject
    : TValue
  : EmptyObject;
type ContentOf<TContent, TMediaType extends string> = TContent extends Record<PropertyKey, unknown>
  ? TMediaType extends keyof TContent
    ? TContent[TMediaType]
    : never
  : never;
type JsonContentOf<TContent> = TContent extends Record<PropertyKey, unknown>
  ? "application/json" extends keyof TContent
    ? TContent["application/json"]
    : null
  : null;
type RequestContentTypesOf<T> = T extends { requestBody: { content: infer TContent } }
  ? Extract<keyof TContent, string>
  : never;
type RequestBodyOf<T> = T extends { requestBody: { content: infer TContent } }
  ? ContentOf<TContent, RequestContentTypesOf<T>>
  : never;
type RequestBodyForContentType<T, TContentType extends string> = T extends { requestBody: { content: infer TContent } }
  ? ContentOf<TContent, TContentType>
  : never;
type ResponsesOf<T> = T extends { responses: infer TResponses } ? TResponses : EmptyObject;
type StatusCodeOf<TResponses> = Extract<keyof TResponses, number>;
type ResponseBodyOf<TEntry> = TEntry extends { content: infer TContent }
  ? JsonContentOf<TContent>
  : null;
type ResultForResponses<TResponses> = {
  [TStatus in StatusCodeOf<TResponses>]: {
    readonly status: TStatus;
    readonly ok: TStatus extends SuccessStatus ? true : false;
    readonly headers: Headers;
    readonly data: ResponseBodyOf<TResponses[TStatus]>;
  };
}[StatusCodeOf<TResponses>];

/** Named aliases for generated OpenAPI component schemas. */
export type ErrorEnvelope = GeneratedComponents["schemas"]["ErrorEnvelope"];
export type HealthResponse = GeneratedComponents["schemas"]["HealthResponse"];
export type Principal = GeneratedComponents["schemas"]["Principal"];
export type TokenIntrospectFormRequest = GeneratedComponents["schemas"]["TokenIntrospectFormRequest"];
export type TokenIntrospectRequest = GeneratedComponents["schemas"]["TokenIntrospectRequest"];
export type TokenIntrospectResponse = GeneratedComponents["schemas"]["TokenIntrospectResponse"];
export type TokenVerifyRequest = GeneratedComponents["schemas"]["TokenVerifyRequest"];
export type TokenVerifyResponse = GeneratedComponents["schemas"]["TokenVerifyResponse"];

/** Operation-specific request and response helpers. */

type HealthLiveSpec = OperationOf<"health_live">;
export type HealthLiveOperation = HealthLiveSpec;
export type HealthLivePathParams = Simplify<FieldOf<ParametersOf<HealthLiveSpec>, "path">>;
export type HealthLiveQueryParams = Simplify<FieldOf<ParametersOf<HealthLiveSpec>, "query">>;
export type HealthLiveHeaders = Simplify<FieldOf<ParametersOf<HealthLiveSpec>, "header">>;
export type HealthLiveRequestContentType = RequestContentTypesOf<HealthLiveSpec>;
export type HealthLiveRequestBody = RequestBodyOf<HealthLiveSpec>;
export type HealthLiveRequestBodyForContentType<TContentType extends HealthLiveRequestContentType> = RequestBodyForContentType<HealthLiveSpec, TContentType>;
export type HealthLiveResponses = ResponsesOf<HealthLiveSpec>;
export type HealthLiveResult = ResultForResponses<HealthLiveResponses>;
export type HealthLiveResponseData = HealthLiveResult["data"];
export type HealthLiveSuccessResult = Extract<HealthLiveResult, { ok: true }>;
export type HealthLiveErrorResult = Extract<HealthLiveResult, { ok: false }>;
export type HealthLiveSuccessData = HealthLiveSuccessResult["data"];
export type HealthLiveErrorData = HealthLiveErrorResult["data"];
export type HealthLiveResponse200 = ResponseBodyOf<HealthLiveResponses[200]>;
export interface HealthLiveRequestOptions {
  readonly signal?: AbortSignal;
}

type HealthReadySpec = OperationOf<"health_ready">;
export type HealthReadyOperation = HealthReadySpec;
export type HealthReadyPathParams = Simplify<FieldOf<ParametersOf<HealthReadySpec>, "path">>;
export type HealthReadyQueryParams = Simplify<FieldOf<ParametersOf<HealthReadySpec>, "query">>;
export type HealthReadyHeaders = Simplify<FieldOf<ParametersOf<HealthReadySpec>, "header">>;
export type HealthReadyRequestContentType = RequestContentTypesOf<HealthReadySpec>;
export type HealthReadyRequestBody = RequestBodyOf<HealthReadySpec>;
export type HealthReadyRequestBodyForContentType<TContentType extends HealthReadyRequestContentType> = RequestBodyForContentType<HealthReadySpec, TContentType>;
export type HealthReadyResponses = ResponsesOf<HealthReadySpec>;
export type HealthReadyResult = ResultForResponses<HealthReadyResponses>;
export type HealthReadyResponseData = HealthReadyResult["data"];
export type HealthReadySuccessResult = Extract<HealthReadyResult, { ok: true }>;
export type HealthReadyErrorResult = Extract<HealthReadyResult, { ok: false }>;
export type HealthReadySuccessData = HealthReadySuccessResult["data"];
export type HealthReadyErrorData = HealthReadyErrorResult["data"];
export type HealthReadyResponse200 = ResponseBodyOf<HealthReadyResponses[200]>;
export type HealthReadyResponse503 = ResponseBodyOf<HealthReadyResponses[503]>;
export interface HealthReadyRequestOptions {
  readonly signal?: AbortSignal;
}

type IntrospectTokenSpec = OperationOf<"introspect_token">;
export type IntrospectTokenOperation = IntrospectTokenSpec;
export type IntrospectTokenPathParams = Simplify<FieldOf<ParametersOf<IntrospectTokenSpec>, "path">>;
export type IntrospectTokenQueryParams = Simplify<FieldOf<ParametersOf<IntrospectTokenSpec>, "query">>;
export type IntrospectTokenHeaders = Simplify<FieldOf<ParametersOf<IntrospectTokenSpec>, "header">>;
export type IntrospectTokenRequestContentType = RequestContentTypesOf<IntrospectTokenSpec>;
export type IntrospectTokenRequestBody = RequestBodyOf<IntrospectTokenSpec>;
export type IntrospectTokenRequestBodyForContentType<TContentType extends IntrospectTokenRequestContentType> = RequestBodyForContentType<IntrospectTokenSpec, TContentType>;
export type IntrospectTokenResponses = ResponsesOf<IntrospectTokenSpec>;
export type IntrospectTokenResult = ResultForResponses<IntrospectTokenResponses>;
export type IntrospectTokenResponseData = IntrospectTokenResult["data"];
export type IntrospectTokenSuccessResult = Extract<IntrospectTokenResult, { ok: true }>;
export type IntrospectTokenErrorResult = Extract<IntrospectTokenResult, { ok: false }>;
export type IntrospectTokenSuccessData = IntrospectTokenSuccessResult["data"];
export type IntrospectTokenErrorData = IntrospectTokenErrorResult["data"];
export type IntrospectTokenResponse200 = ResponseBodyOf<IntrospectTokenResponses[200]>;
export type IntrospectTokenResponse401 = ResponseBodyOf<IntrospectTokenResponses[401]>;
export type IntrospectTokenResponse403 = ResponseBodyOf<IntrospectTokenResponses[403]>;
export type IntrospectTokenResponse422 = ResponseBodyOf<IntrospectTokenResponses[422]>;
export type IntrospectTokenResponse503 = ResponseBodyOf<IntrospectTokenResponses[503]>;
export type IntrospectTokenRequestOptions =
  | {
      readonly signal?: AbortSignal;
      readonly contentType: "application/json";
      readonly body: IntrospectTokenRequestBodyForContentType<"application/json">;
    }
  | {
      readonly signal?: AbortSignal;
      readonly contentType: "application/x-www-form-urlencoded";
      readonly body: IntrospectTokenRequestBodyForContentType<"application/x-www-form-urlencoded"> | URLSearchParams;
    };

type VerifyTokenSpec = OperationOf<"verify_token">;
export type VerifyTokenOperation = VerifyTokenSpec;
export type VerifyTokenPathParams = Simplify<FieldOf<ParametersOf<VerifyTokenSpec>, "path">>;
export type VerifyTokenQueryParams = Simplify<FieldOf<ParametersOf<VerifyTokenSpec>, "query">>;
export type VerifyTokenHeaders = Simplify<FieldOf<ParametersOf<VerifyTokenSpec>, "header">>;
export type VerifyTokenRequestContentType = RequestContentTypesOf<VerifyTokenSpec>;
export type VerifyTokenRequestBody = RequestBodyOf<VerifyTokenSpec>;
export type VerifyTokenRequestBodyForContentType<TContentType extends VerifyTokenRequestContentType> = RequestBodyForContentType<VerifyTokenSpec, TContentType>;
export type VerifyTokenResponses = ResponsesOf<VerifyTokenSpec>;
export type VerifyTokenResult = ResultForResponses<VerifyTokenResponses>;
export type VerifyTokenResponseData = VerifyTokenResult["data"];
export type VerifyTokenSuccessResult = Extract<VerifyTokenResult, { ok: true }>;
export type VerifyTokenErrorResult = Extract<VerifyTokenResult, { ok: false }>;
export type VerifyTokenSuccessData = VerifyTokenSuccessResult["data"];
export type VerifyTokenErrorData = VerifyTokenErrorResult["data"];
export type VerifyTokenResponse200 = ResponseBodyOf<VerifyTokenResponses[200]>;
export type VerifyTokenResponse401 = ResponseBodyOf<VerifyTokenResponses[401]>;
export type VerifyTokenResponse403 = ResponseBodyOf<VerifyTokenResponses[403]>;
export type VerifyTokenResponse422 = ResponseBodyOf<VerifyTokenResponses[422]>;
export type VerifyTokenResponse503 = ResponseBodyOf<VerifyTokenResponses[503]>;
export interface VerifyTokenRequestOptions {
  readonly signal?: AbortSignal;
  readonly body: VerifyTokenRequestBody;
}
