# Code generated by scripts/release/generate_clients.py. DO NOT EDIT.

nova_file_null_coalesce <- function(value, fallback) {
  if (is.null(value)) {
    fallback
  } else {
    value
  }
}

nova_file_normalize_named_list <- function(value, label) {
  if (is.null(value)) {
    return(list())
  }
  if (is.atomic(value) && !is.list(value)) {
    value <- as.list(value)
  }
  if (!is.list(value)) {
    stop(sprintf("%s must be a named list", label), call. = FALSE)
  }
  item_names <- names(value)
  if (is.null(item_names)) {
    stop(sprintf("%s must be a named list", label), call. = FALSE)
  }
  cleaned <- list()
  for (index in seq_along(value)) {
    item_name <- item_names[[index]]
    if (is.na(item_name) || !nzchar(item_name)) {
      stop(sprintf("%s names must be non-empty", label), call. = FALSE)
    }
    item_value <- value[[index]]
    if (is.null(item_value)) {
      next
    }
    cleaned[[item_name]] <- item_value
  }
  cleaned
}

nova_file_prune_null_headers <- function(value) {
  if (length(value) == 0L) {
    return(value)
  }
  value[!vapply(value, is.null, logical(1))]
}

nova_file_normalize_base_url <- function(base_url) {
  if (!is.character(base_url) || length(base_url) != 1L || !nzchar(base_url)) {
    stop("base_url must be a non-empty string", call. = FALSE)
  }
  sub("/+$", "", base_url)
}

nova_file_resolve_path <- function(path, path_params) {
  path_params <- nova_file_normalize_named_list(path_params, "path_params")
  resolved_path <- path
  if (length(path_params) > 0L) {
    for (param_name in names(path_params)) {
      resolved_path <- gsub(
        sprintf("{%s}", param_name),
        utils::URLencode(as.character(path_params[[param_name]]), reserved = TRUE),
        resolved_path,
        fixed = TRUE
      )
    }
  }
  missing_path_params <- regmatches(
    resolved_path, gregexpr("\\{[^}]+\\}", resolved_path, perl = TRUE)
  )[[1]]
  if (length(missing_path_params) > 0L) {
    stop(sprintf("missing path parameter(s): %s", paste(missing_path_params, collapse = ", ")), call. = FALSE)
  }
  resolved_path
}

nova_file_select_content_type <- function(operation_id, request_content_types, content_type) {
  if (length(request_content_types) == 0L) {
    return(NULL)
  }
  if (is.null(content_type) || !nzchar(as.character(content_type)[[1]])) {
    if (length(request_content_types) > 1L) {
      stop(sprintf("operation %s requires an explicit content_type", operation_id), call. = FALSE)
    }
    return(request_content_types[[1L]])
  }
  selected_content_type <- as.character(content_type)[[1]]
  if (!(selected_content_type %in% request_content_types)) {
    stop(sprintf("unsupported content_type %s for operation %s", selected_content_type, operation_id), call. = FALSE)
  }
  selected_content_type
}

nova_file_parse_json_body <- function(body) {
  if (is.null(body) || !nzchar(trimws(body))) {
    return(NULL)
  }
  tryCatch(
    jsonlite::fromJSON(body, simplifyVector = FALSE),
    error = function(...) NULL
  )
}

nova_file_parse_success_body <- function(body) {
  parsed_body <- nova_file_parse_json_body(body)
  if (is.null(parsed_body)) {
    if (is.null(body) || !nzchar(trimws(body))) {
      return(NULL)
    }
    return(body)
  }
  parsed_body
}

nova_file_encode_json_body <- function(body) {
  jsonlite::toJSON(body, auto_unbox = TRUE, null = "null")
}

nova_file_encode_form_body <- function(body) {
  if (is.null(body) || length(body) == 0L) {
    return("")
  }
  body <- nova_file_normalize_named_list(body, "body")
  encode_item <- function(name, value) {
    if (is.null(value)) {
      return(character(0))
    }
    if (is.list(value) && !inherits(value, "data.frame")) {
      value <- jsonlite::toJSON(value, auto_unbox = TRUE, null = "null")
      return(paste0(utils::URLencode(name, reserved = TRUE), "=", utils::URLencode(value, reserved = TRUE)))
    }
    values <- as.character(value)
    if (length(values) == 0L) {
      return(character(0))
    }
    encoded_name <- utils::URLencode(name, reserved = TRUE)
    vapply(
      values,
      function(item) {
        paste0(encoded_name, "=", utils::URLencode(item, reserved = TRUE))
      },
      character(1)
    )
  }
  parts <- character(0)
  for (name in names(body)) {
    parts <- c(parts, encode_item(name, body[[name]]))
  }
  paste(parts, collapse = "&")
}

nova_file_encode_request_body <- function(body, content_type) {
  if (is.null(body)) {
    return(NULL)
  }
  if (identical(content_type, "application/json")) {
    return(nova_file_encode_json_body(body))
  }
  if (identical(content_type, "application/x-www-form-urlencoded")) {
    return(nova_file_encode_form_body(body))
  }
  stop(sprintf("unsupported content_type %s", content_type), call. = FALSE)
}

nova_file_default_user_agent <- function() {
  sprintf("nova.sdk.r.file/%s", utils::packageVersion("nova.sdk.r.file"))
}

nova_file_bearer_token <- function(token = NULL, env_var = "NOVA_FILE_BEARER_TOKEN") {
  if (!is.null(token)) {
    return(as.character(token)[[1]])
  }
  if (is.null(env_var) || !nzchar(as.character(env_var)[[1]])) {
    return(NULL)
  }
  env_value <- Sys.getenv(as.character(env_var)[[1]], unset = '')
  if (!nzchar(env_value)) {
    return(NULL)
  }
  env_value
}

nova_file_decode_error_envelope <- function(body, status = NULL) {
  parsed_body <- nova_file_parse_json_body(body)
  if (!is.list(parsed_body) || is.null(parsed_body$error) || !is.list(parsed_body$error)) {
    fallback_status <- if (is.null(status)) 'unknown' else as.character(status)
    fallback_message <- if (is.null(body) || !nzchar(trimws(body))) {
      sprintf("HTTP %s response", fallback_status)
    } else {
      body
    }
    return(
      list(
        code = paste0("http_", fallback_status),
        message = fallback_message,
        details = list(),
        request_id = NULL
      )
    )
  }
  error_body <- parsed_body$error
  request_id <- error_body$request_id
  if (length(request_id) == 0L) {
    request_id <- NULL
  }
  list(
    code = as.character(error_body$code),
    message = as.character(error_body$message),
    details = nova_file_null_coalesce(error_body$details, list()),
    request_id = request_id
  )
}

nova_file_error_condition <- function(error, status, operation_id, method, path) {
  structure(
    list(
      message = error$message,
      call = NULL,
      code = error$code,
      status = status,
      request_id = error$request_id,
      details = error$details,
      operation_id = operation_id,
      method = method,
      path = path
    ),
    class = c("nova_file_api_error", "error", "condition")
  )
}

conditionMessage.nova_file_api_error <- function(c) {
  sprintf("[%s] %s", c$code, c$message)
}

nova_file_apply_request <- function(http_request, request_headers, bearer_token, user_agent) {
  if (length(request_headers) > 0L) {
    http_request <- do.call(httr2::req_headers, c(list(http_request), request_headers))
  }
  if (!is.null(user_agent) && nzchar(user_agent)) {
    http_request <- httr2::req_user_agent(http_request, user_agent)
  }
  has_authorization <- "Authorization" %in% names(request_headers)
  if (!is.null(bearer_token) && nzchar(bearer_token) && !has_authorization) {
    http_request <- httr2::req_auth_bearer_token(http_request, bearer_token)
  }
  http_request
}

nova_file_api_call <- function(
  client,
  operation_id,
  method,
  path,
  body = NULL,
  path_params = NULL,
  query = NULL,
  headers = NULL,
  content_type = NULL,
  request_content_types = character(0),
  requires_body = FALSE,
  accepts_body = FALSE
) {
  if (!inherits(client, "nova_file_client")) {
    stop("client must be created by create_nova_file_client()", call. = FALSE)
  }
  query <- nova_file_normalize_named_list(query, "query")
  request_headers <- nova_file_normalize_named_list(headers, "headers")
  merged_headers <- c(client$default_headers, request_headers)
  if (length(merged_headers) > 0L) {
    merged_headers <- merged_headers[!duplicated(names(merged_headers), fromLast = TRUE)]
  }
  merged_headers <- nova_file_prune_null_headers(merged_headers)
  resolved_path <- nova_file_resolve_path(path, path_params)
  selected_content_type <- nova_file_select_content_type(operation_id, request_content_types, content_type)
  if (is.null(body) && isTRUE(requires_body)) {
    stop(sprintf("operation %s requires a request body", operation_id), call. = FALSE)
  }
  if (!is.null(body) && !isTRUE(accepts_body)) {
    stop(sprintf("operation %s does not accept a request body", operation_id), call. = FALSE)
  }
  http_request <- httr2::request(paste0(client$base_url, resolved_path))
  http_request <- httr2::req_method(http_request, method)
  if (length(query) > 0L) {
    http_request <- do.call(httr2::req_url_query, c(list(http_request), query))
  }
  http_request <- nova_file_apply_request(http_request, merged_headers, client$bearer_token, client$user_agent)
  http_request <- httr2::req_options(http_request, timeout = client$timeout_seconds)
  encoded_body <- nova_file_encode_request_body(body, selected_content_type)
  if (!is.null(encoded_body)) {
    http_request <- httr2::req_body_raw(http_request, charToRaw(encoded_body))
    http_request <- do.call(
      httr2::req_headers,
      c(
        list(http_request),
        list("Content-Type" = selected_content_type)
      )
    )
  }
  response <- httr2::req_perform(
    httr2::req_error(http_request, is_error = function(resp) FALSE)
  )
  status <- httr2::resp_status(response)
  body_text <- httr2::resp_body_string(response)
  if (status >= 200L && status < 300L) {
    return(nova_file_parse_success_body(body_text))
  }
  error <- nova_file_decode_error_envelope(body_text, status = status)
  stop(
    nova_file_error_condition(
      error = error,
      status = status,
      operation_id = operation_id,
      method = method,
      path = resolved_path
    )
  )
}

create_nova_file_client <- function(
  base_url,
  bearer_token = NULL,
  bearer_token_env = "NOVA_FILE_BEARER_TOKEN",
  default_headers = NULL,
  timeout_seconds = 30,
  user_agent = NULL
) {
  base_url <- nova_file_normalize_base_url(base_url)
  if (!is.numeric(timeout_seconds) || length(timeout_seconds) != 1L || is.na(timeout_seconds) || !is.finite(timeout_seconds) || timeout_seconds <= 0) {
    stop("timeout_seconds must be a finite positive number", call. = FALSE)
  }
  default_headers <- nova_file_normalize_named_list(default_headers, "default_headers")
  client <- list(
    base_url = base_url,
    bearer_token = nova_file_bearer_token(token = bearer_token, env_var = bearer_token_env),
    default_headers = default_headers,
    timeout_seconds = timeout_seconds,
    user_agent = nova_file_null_coalesce(user_agent, nova_file_default_user_agent())
  )
  class(client) <- c("nova_file_client", "list")
  client
}
