# Code generated by scripts/release/generate_clients.py. DO NOT EDIT.

nova_file_null_coalesce <- function(value, fallback) {
  if (is.null(value)) {
    fallback
  } else {
    value
  }
}

nova_file_normalize_named_list <- function(value, label) {
  if (is.null(value)) {
    return(list())
  }
  if (is.atomic(value) && !is.list(value)) {
    value <- as.list(value)
  }
  if (!is.list(value)) {
    stop(sprintf("%s must be a named list", label), call. = FALSE)
  }
  item_names <- names(value)
  if (is.null(item_names)) {
    stop(sprintf("%s must be a named list", label), call. = FALSE)
  }
  cleaned <- list()
  for (index in seq_along(value)) {
    item_name <- item_names[[index]]
    if (is.na(item_name) || !nzchar(item_name)) {
      stop(sprintf("%s names must be non-empty", label), call. = FALSE)
    }
    item_value <- value[[index]]
    if (is.null(item_value)) {
      next
    }
    cleaned[[item_name]] <- item_value
  }
  cleaned
}

nova_file_prune_null_headers <- function(value) {
  if (length(value) == 0L) {
    return(value)
  }
  value[!vapply(value, is.null, logical(1))]
}

nova_file_normalize_base_url <- function(base_url) {
  if (!is.character(base_url) || length(base_url) != 1L || !nzchar(base_url)) {
    stop("base_url must be a non-empty string", call. = FALSE)
  }
  sub("/+$", "", base_url)
}

nova_file_resolve_path <- function(path, path_params) {
  path_params <- nova_file_normalize_named_list(path_params, "path_params")
  resolved_path <- path
  if (length(path_params) > 0L) {
    for (param_name in names(path_params)) {
      resolved_path <- gsub(
        sprintf("{%s}", param_name),
        utils::URLencode(as.character(path_params[[param_name]]), reserved = TRUE),
        resolved_path,
        fixed = TRUE
      )
    }
  }
  missing_path_params <- regmatches(
    resolved_path, gregexpr("\\{[^}]+\\}", resolved_path, perl = TRUE)
  )[[1]]
  if (length(missing_path_params) > 0L) {
    stop(sprintf("missing path parameter(s): %s", paste(missing_path_params, collapse = ", ")), call. = FALSE)
  }
  resolved_path
}

nova_file_parse_json_response <- function(response) {
  if (length(httr2::resp_body_raw(response)) == 0L) {
    return(NULL)
  }
  httr2::resp_body_json(response, simplifyVector = FALSE, check_type = FALSE)
}

nova_file_parse_success_response <- function(response) {
  nova_file_parse_json_response(response)
}

nova_file_response_body_text <- function(response) {
  if (length(httr2::resp_body_raw(response)) == 0L) {
    return("")
  }
  httr2::resp_body_string(response)
}

nova_file_default_user_agent <- function() {
  sprintf("nova.sdk.r.file/%s", utils::packageVersion("nova.sdk.r.file"))
}

nova_file_bearer_token <- function(token = NULL, env_var = "NOVA_FILE_BEARER_TOKEN") {
  if (!is.null(token)) {
    return(as.character(token)[[1]])
  }
  if (is.null(env_var) || !nzchar(as.character(env_var)[[1]])) {
    return(NULL)
  }
  env_value <- Sys.getenv(as.character(env_var)[[1]], unset = '')
  if (!nzchar(env_value)) {
    return(NULL)
  }
  env_value
}

nova_file_decode_error_envelope <- function(response, status = NULL) {
  parsed_body <- tryCatch(
    nova_file_parse_json_response(response),
    error = function(...) NULL
  )
  if (!is.list(parsed_body) || is.null(parsed_body$error) || !is.list(parsed_body$error)) {
    fallback_status <- if (is.null(status)) 'unknown' else as.character(status)
    fallback_message <- if (!nzchar(nova_file_response_body_text(response))) {
      sprintf("HTTP %s response", fallback_status)
    } else {
      nova_file_response_body_text(response)
    }
    return(
      list(
        code = paste0("http_", fallback_status),
        message = fallback_message,
        details = list(),
        request_id = NULL
      )
    )
  }
  error_body <- parsed_body$error
  request_id <- error_body$request_id
  if (length(request_id) == 0L) {
    request_id <- NULL
  }
  list(
    code = as.character(error_body$code),
    message = as.character(error_body$message),
    details = nova_file_null_coalesce(error_body$details, list()),
    request_id = request_id
  )
}

nova_file_error_body <- function(response) {
  error <- nova_file_decode_error_envelope(response, status = httr2::resp_status(response))
  sprintf("[%s] %s", error$code, error$message)
}

nova_file_error_condition <- function(error, status, operation_id, method, path) {
  structure(
    list(
      message = error$message,
      call = NULL,
      code = error$code,
      status = status,
      request_id = error$request_id,
      details = error$details,
      operation_id = operation_id,
      method = method,
      path = path
    ),
    class = c("nova_file_api_error", "error", "condition")
  )
}

conditionMessage.nova_file_api_error <- function(c) {
  sprintf("[%s] %s", c$code, c$message)
}

nova_file_apply_request <- function(http_request, request_headers, bearer_token, user_agent) {
  if (length(request_headers) > 0L) {
    http_request <- do.call(httr2::req_headers, c(list(http_request), request_headers))
  }
  if (!is.null(user_agent) && nzchar(user_agent)) {
    http_request <- httr2::req_user_agent(http_request, user_agent)
  }
  has_authorization <- "Authorization" %in% names(request_headers)
  if (!is.null(bearer_token) && nzchar(bearer_token) && !has_authorization) {
    http_request <- httr2::req_auth_bearer_token(http_request, bearer_token)
  }
  http_request
}

nova_file_api_call <- function(
  client,
  operation_id,
  method,
  path,
  body = NULL,
  path_params = NULL,
  query = NULL,
  headers = NULL,
  requires_body = FALSE,
  accepts_body = FALSE
) {
  if (!inherits(client, "nova_file_client")) {
    stop("client must be created by create_nova_file_client()", call. = FALSE)
  }
  query <- nova_file_normalize_named_list(query, "query")
  request_headers <- nova_file_normalize_named_list(headers, "headers")
  merged_headers <- c(client$default_headers, request_headers)
  if (length(merged_headers) > 0L) {
    merged_headers <- merged_headers[!duplicated(names(merged_headers), fromLast = TRUE)]
  }
  merged_headers <- nova_file_prune_null_headers(merged_headers)
  resolved_path <- nova_file_resolve_path(path, path_params)
  if (is.null(body) && isTRUE(requires_body)) {
    stop(sprintf("operation %s requires a request body", operation_id), call. = FALSE)
  }
  if (!is.null(body) && !isTRUE(accepts_body)) {
    stop(sprintf("operation %s does not accept a request body", operation_id), call. = FALSE)
  }
  http_request <- httr2::request(paste0(client$base_url, resolved_path))
  http_request <- httr2::req_method(http_request, method)
  if (length(query) > 0L) {
    http_request <- do.call(httr2::req_url_query, c(list(http_request), query))
  }
  http_request <- nova_file_apply_request(http_request, merged_headers, client$bearer_token, client$user_agent)
  http_request <- httr2::req_options(http_request, timeout = client$timeout_seconds)
  if (!is.null(body)) {
    http_request <- httr2::req_body_json(http_request, body, auto_unbox = TRUE, null = "null")
  }
  http_request <- httr2::req_error(http_request, body = function(resp) {
    nova_file_error_body(resp)
  })
  tryCatch(
    {
      response <- httr2::req_perform(http_request)
      nova_file_parse_success_response(response)
    },
    httr2_http = function(cnd) {
      error <- nova_file_decode_error_envelope(cnd$resp, status = cnd$status)
      stop(
        nova_file_error_condition(
          error = error,
          status = cnd$status,
          operation_id = operation_id,
          method = method,
          path = resolved_path
        )
      )
    }
  )
}

create_nova_file_client <- function(
  base_url,
  bearer_token = NULL,
  bearer_token_env = "NOVA_FILE_BEARER_TOKEN",
  default_headers = NULL,
  timeout_seconds = 30,
  user_agent = NULL
) {
  base_url <- nova_file_normalize_base_url(base_url)
  if (!is.numeric(timeout_seconds) || length(timeout_seconds) != 1L || is.na(timeout_seconds) || !is.finite(timeout_seconds) || timeout_seconds <= 0) {
    stop("timeout_seconds must be a finite positive number", call. = FALSE)
  }
  default_headers <- nova_file_normalize_named_list(default_headers, "default_headers")
  client <- list(
    base_url = base_url,
    bearer_token = nova_file_bearer_token(token = bearer_token, env_var = bearer_token_env),
    default_headers = default_headers,
    timeout_seconds = timeout_seconds,
    user_agent = nova_file_null_coalesce(user_agent, nova_file_default_user_agent())
  )
  class(client) <- c("nova_file_client", "list")
  client
}
