# Code generated by scripts/release/generate_clients.py. DO NOT EDIT.

nova_file_default_request_performer <- function(request) {
  if (!is.list(request)) {
    stop("request must be a list", call. = FALSE)
  }
  http_request <- httr2::request(request$url)
  http_request <- httr2::req_method(http_request, request$method)
  if (length(request$query) > 0L) {
    http_request <- do.call(httr2::req_url_query, c(list(http_request), request$query))
  }
  if (length(request$headers) > 0L) {
    http_request <- do.call(httr2::req_headers, c(list(http_request), request$headers))
  }
  http_request <- httr2::req_options(http_request, timeout = request$timeout_seconds)
  encoded_body <- nova_file_encode_request_body(request$body, request$content_type)
  if (!is.null(encoded_body)) {
    http_request <- httr2::req_body_raw(http_request, charToRaw(encoded_body))
    http_request <- do.call(
      httr2::req_headers,
      c(
        list(http_request),
        list("Content-Type" = request$content_type)
      )
    )
  }
  response <- httr2::req_perform(http_request)
  list(
    status = httr2::resp_status(response),
    headers = httr2::resp_headers(response),
    body = httr2::resp_body_string(response),
    url = request$url
  )
}

nova_file_request_descriptor <- function(
  client,
  operation_id,
  body = NULL,
  path_params = NULL,
  query = NULL,
  headers = NULL,
  content_type = NULL
) {
  if (!is.list(client) || is.null(client$operations)) {
    stop("client must be created by the package constructor", call. = FALSE)
  }
  operation <- client$operations[[operation_id]]
  if (is.null(operation)) {
    stop(sprintf("unknown operation_id: %s", operation_id), call. = FALSE)
  }
  path_params <- nova_file_normalize_named_list(path_params, "path_params")
  query <- nova_file_normalize_named_list(query, "query")
  request_headers <- nova_file_normalize_named_list(headers, "headers")
  merged_headers <- c(client$default_headers, request_headers)
  if (length(merged_headers) > 0L) {
    merged_headers <- merged_headers[!duplicated(names(merged_headers), fromLast = TRUE)]
  }
  merged_headers <- nova_file_prune_null_headers(merged_headers)
  resolved_path <- nova_file_resolve_path(operation$path, path_params)
  selected_content_type <- nova_file_select_content_type(operation, content_type)
  if (is.null(body)) {
    if (isTRUE(operation$has_request_body) && isTRUE(operation$has_required_request_body)) {
      stop(sprintf("operation %s requires a request body", operation_id), call. = FALSE)
    }
  } else if (!isTRUE(operation$has_request_body)) {
    stop(sprintf("operation %s does not accept a request body", operation_id), call. = FALSE)
  }
  list(
    operation_id = operation$operation_id,
    method = operation$method,
    path = resolved_path,
    url = paste0(client$base_url, resolved_path),
    body = body,
    content_type = selected_content_type,
    headers = merged_headers,
    query = query,
    timeout_seconds = client$timeout_seconds
  )
}

nova_file_execute_operation <- function(
  client,
  operation_id,
  body = NULL,
  path_params = NULL,
  query = NULL,
  headers = NULL,
  content_type = NULL
) {
  request <- nova_file_request_descriptor(
    client = client,
    operation_id = operation_id,
    body = body,
    path_params = path_params,
    query = query,
    headers = headers,
    content_type = content_type
  )
  response <- tryCatch(
    client$request_performer(request),
    error = function(error) {
      stop(
        sprintf(
          "request_performer failed for %s: %s",
          operation_id,
          conditionMessage(error)
        ),
        call. = FALSE
      )
    }
  )
  if (!is.list(response) || is.null(response$status)) {
    stop("request_performer must return a list with status", call. = FALSE)
  }
  status <- as.integer(response$status[[1]])
  if (is.na(status)) {
    stop("request_performer returned an invalid status code", call. = FALSE)
  }
  body_text <- response$body
  if (is.null(body_text)) {
    body_text <- ""
  }
  ok <- status >= 200L && status < 300L
  if (ok) {
    data <- nova_file_parse_json_body(body_text)
    error <- NULL
  } else {
    data <- NULL
    error <- nova_file_decode_error_envelope(body_text, status = status)
  }
  list(
    ok = ok,
    status = status,
    headers = response$headers,
    data = data,
    error = error,
    request = request,
    response = response
  )
}

create_nova_file_client <- function(
  base_url,
  request_performer = nova_file_default_request_performer,
  default_headers = NULL,
  timeout_seconds = 30
) {
  base_url <- nova_file_normalize_base_url(base_url)
  if (!is.function(request_performer)) {
    stop("request_performer must be a function", call. = FALSE)
  }
  if (!is.numeric(timeout_seconds) || length(timeout_seconds) != 1L || is.na(timeout_seconds) || !is.finite(timeout_seconds) || timeout_seconds <= 0) {
    stop("timeout_seconds must be a finite positive number", call. = FALSE)
  }
  default_headers <- nova_file_normalize_named_list(default_headers, "default_headers")
  operations <- nova_file_operation_catalog()
  client <- list(
    base_url = base_url,
    request_performer = request_performer,
    default_headers = default_headers,
    timeout_seconds = timeout_seconds,
    operations = operations
  )
  for (operation_id in names(operations)) {
    client[[operation_id]] <- local({
      bound_operation_id <- operation_id
      function(
        body = NULL,
        path_params = NULL,
        query = NULL,
        headers = NULL,
        content_type = NULL
      ) {
        nova_file_execute_operation(
          client = client,
          operation_id = bound_operation_id,
          body = body,
          path_params = path_params,
          query = query,
          headers = headers,
          content_type = content_type
        )
      }
    })
  }
  class(client) <- c("nova_file_client", "list")
  client
}
