# Code generated by scripts/release/generate_clients.py. DO NOT EDIT.

nova_file_metrics_summary <- function(
  client,
  headers = NULL
) {
  nova_file_api_call(
    client = client,
    operation_id = "metrics_summary",
    method = "GET",
    path = "/metrics/summary",
    headers = headers,
    requires_body = FALSE,
    accepts_body = FALSE
  )
}

nova_file_get_capabilities <- function(
  client,
  headers = NULL
) {
  nova_file_api_call(
    client = client,
    operation_id = "get_capabilities",
    method = "GET",
    path = "/v1/capabilities",
    headers = headers,
    requires_body = FALSE,
    accepts_body = FALSE
  )
}

nova_file_health_live <- function(
  client,
  headers = NULL
) {
  nova_file_api_call(
    client = client,
    operation_id = "health_live",
    method = "GET",
    path = "/v1/health/live",
    headers = headers,
    requires_body = FALSE,
    accepts_body = FALSE
  )
}

nova_file_health_ready <- function(
  client,
  headers = NULL
) {
  nova_file_api_call(
    client = client,
    operation_id = "health_ready",
    method = "GET",
    path = "/v1/health/ready",
    headers = headers,
    requires_body = FALSE,
    accepts_body = FALSE
  )
}

nova_file_list_jobs <- function(
  client,
  limit = NULL,
  headers = NULL
) {
  nova_file_api_call(
    client = client,
    operation_id = "list_jobs",
    method = "GET",
    path = "/v1/jobs",
    query = list(limit = limit),
    headers = headers,
    requires_body = FALSE,
    accepts_body = FALSE
  )
}

nova_file_create_job <- function(
  client,
  body,
  headers = NULL
) {
  nova_file_api_call(
    client = client,
    operation_id = "create_job",
    method = "POST",
    path = "/v1/jobs",
    body = body,
    headers = headers,
    requires_body = TRUE,
    accepts_body = TRUE
  )
}

nova_file_get_job_status <- function(
  client,
  job_id,
  headers = NULL
) {
  nova_file_api_call(
    client = client,
    operation_id = "get_job_status",
    method = "GET",
    path = "/v1/jobs/{job_id}",
    path_params = list(job_id = job_id),
    headers = headers,
    requires_body = FALSE,
    accepts_body = FALSE
  )
}

nova_file_cancel_job <- function(
  client,
  job_id,
  headers = NULL
) {
  nova_file_api_call(
    client = client,
    operation_id = "cancel_job",
    method = "POST",
    path = "/v1/jobs/{job_id}/cancel",
    path_params = list(job_id = job_id),
    headers = headers,
    requires_body = FALSE,
    accepts_body = FALSE
  )
}

nova_file_list_job_events <- function(
  client,
  job_id,
  headers = NULL
) {
  nova_file_api_call(
    client = client,
    operation_id = "list_job_events",
    method = "GET",
    path = "/v1/jobs/{job_id}/events",
    path_params = list(job_id = job_id),
    headers = headers,
    requires_body = FALSE,
    accepts_body = FALSE
  )
}

nova_file_retry_job <- function(
  client,
  job_id,
  headers = NULL
) {
  nova_file_api_call(
    client = client,
    operation_id = "retry_job",
    method = "POST",
    path = "/v1/jobs/{job_id}/retry",
    path_params = list(job_id = job_id),
    headers = headers,
    requires_body = FALSE,
    accepts_body = FALSE
  )
}

nova_file_get_release_info <- function(
  client,
  headers = NULL
) {
  nova_file_api_call(
    client = client,
    operation_id = "get_release_info",
    method = "GET",
    path = "/v1/releases/info",
    headers = headers,
    requires_body = FALSE,
    accepts_body = FALSE
  )
}

nova_file_plan_resources <- function(
  client,
  body,
  headers = NULL
) {
  nova_file_api_call(
    client = client,
    operation_id = "plan_resources",
    method = "POST",
    path = "/v1/resources/plan",
    body = body,
    headers = headers,
    requires_body = TRUE,
    accepts_body = TRUE
  )
}

nova_file_presign_download <- function(
  client,
  body,
  headers = NULL
) {
  nova_file_api_call(
    client = client,
    operation_id = "presign_download",
    method = "POST",
    path = "/v1/transfers/downloads/presign",
    body = body,
    headers = headers,
    requires_body = TRUE,
    accepts_body = TRUE
  )
}

nova_file_abort_upload <- function(
  client,
  body,
  headers = NULL
) {
  nova_file_api_call(
    client = client,
    operation_id = "abort_upload",
    method = "POST",
    path = "/v1/transfers/uploads/abort",
    body = body,
    headers = headers,
    requires_body = TRUE,
    accepts_body = TRUE
  )
}

nova_file_complete_upload <- function(
  client,
  body,
  headers = NULL
) {
  nova_file_api_call(
    client = client,
    operation_id = "complete_upload",
    method = "POST",
    path = "/v1/transfers/uploads/complete",
    body = body,
    headers = headers,
    requires_body = TRUE,
    accepts_body = TRUE
  )
}

nova_file_initiate_upload <- function(
  client,
  body,
  headers = NULL
) {
  nova_file_api_call(
    client = client,
    operation_id = "initiate_upload",
    method = "POST",
    path = "/v1/transfers/uploads/initiate",
    body = body,
    headers = headers,
    requires_body = TRUE,
    accepts_body = TRUE
  )
}

nova_file_introspect_upload <- function(
  client,
  body,
  headers = NULL
) {
  nova_file_api_call(
    client = client,
    operation_id = "introspect_upload",
    method = "POST",
    path = "/v1/transfers/uploads/introspect",
    body = body,
    headers = headers,
    requires_body = TRUE,
    accepts_body = TRUE
  )
}

nova_file_sign_upload_parts <- function(
  client,
  body,
  headers = NULL
) {
  nova_file_api_call(
    client = client,
    operation_id = "sign_upload_parts",
    method = "POST",
    path = "/v1/transfers/uploads/sign-parts",
    body = body,
    headers = headers,
    requires_body = TRUE,
    accepts_body = TRUE
  )
}
