# Code generated by scripts/release/generate_clients.py. DO NOT EDIT.

nova_file_operation_catalog <- function() {
  list(
    "metrics_summary" = list(
      operation_id = "metrics_summary",
      method = "GET",
      path = "/metrics/summary",
      summary = "Metrics Summary"
    ),
    "get_capabilities" = list(
      operation_id = "get_capabilities",
      method = "GET",
      path = "/v1/capabilities",
      summary = "Get Capabilities"
    ),
    "health_live" = list(
      operation_id = "health_live",
      method = "GET",
      path = "/v1/health/live",
      summary = "Health Live"
    ),
    "health_ready" = list(
      operation_id = "health_ready",
      method = "GET",
      path = "/v1/health/ready",
      summary = "Health Ready"
    ),
    "list_jobs" = list(
      operation_id = "list_jobs",
      method = "GET",
      path = "/v1/jobs",
      summary = "List Jobs"
    ),
    "create_job" = list(
      operation_id = "create_job",
      method = "POST",
      path = "/v1/jobs",
      summary = "Create Job"
    ),
    "get_job_status" = list(
      operation_id = "get_job_status",
      method = "GET",
      path = "/v1/jobs/{job_id}",
      summary = "Get Job Status"
    ),
    "cancel_job" = list(
      operation_id = "cancel_job",
      method = "POST",
      path = "/v1/jobs/{job_id}/cancel",
      summary = "Cancel Job"
    ),
    "list_job_events" = list(
      operation_id = "list_job_events",
      method = "GET",
      path = "/v1/jobs/{job_id}/events",
      summary = "List Job Events"
    ),
    "retry_job" = list(
      operation_id = "retry_job",
      method = "POST",
      path = "/v1/jobs/{job_id}/retry",
      summary = "Retry Job"
    ),
    "get_release_info" = list(
      operation_id = "get_release_info",
      method = "GET",
      path = "/v1/releases/info",
      summary = "Get Release Info"
    ),
    "plan_resources" = list(
      operation_id = "plan_resources",
      method = "POST",
      path = "/v1/resources/plan",
      summary = "Plan Resources"
    ),
    "presign_download" = list(
      operation_id = "presign_download",
      method = "POST",
      path = "/v1/transfers/downloads/presign",
      summary = "Presign Download"
    ),
    "abort_upload" = list(
      operation_id = "abort_upload",
      method = "POST",
      path = "/v1/transfers/uploads/abort",
      summary = "Abort Upload"
    ),
    "complete_upload" = list(
      operation_id = "complete_upload",
      method = "POST",
      path = "/v1/transfers/uploads/complete",
      summary = "Complete Upload"
    ),
    "initiate_upload" = list(
      operation_id = "initiate_upload",
      method = "POST",
      path = "/v1/transfers/uploads/initiate",
      summary = "Initiate Upload"
    ),
    "introspect_upload" = list(
      operation_id = "introspect_upload",
      method = "POST",
      path = "/v1/transfers/uploads/introspect",
      summary = "Introspect Upload"
    ),
    "sign_upload_parts" = list(
      operation_id = "sign_upload_parts",
      method = "POST",
      path = "/v1/transfers/uploads/sign-parts",
      summary = "Sign Upload Parts"
    )
  )
}
