name: Nova Release Plan

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  plan:
    if: github.ref == 'refs/heads/main'
    uses: ./.github/workflows/reusable-release-plan.yml
    with:
      checkout_ref: ${{ github.sha }}
